In [1]:
import pandas as pd
import numpy
import json
import os
from dotenv import load_dotenv
from copy import deepcopy
load_dotenv()
os.chdir(os.getenv('PARENT_DIR'))
from src.utils.eval_utils import metrics_instructabsa, parse_absa_string, parse_aoste, calculate_metrics

/home/ext_hanif_zhafran07_gmail_com/testing/absa-sft-comparison/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from typing import List, Dict
def calculate_metrics(predictions: List[List[Dict[str, str]]], targets: List[List[Dict[str, str]]], task='') -> Dict[str, float]:
	"""
	Calculate precision, recall, and F1 score for the given predictions and targets for ABSA.

	Args:
		predictions (List[List[Dict[str, str]]]): List of predicted triplets.
		targets (List[List[Dict[str, str]]]): List of target triplets.
		task (str): The task name for which metrics are calculated.
	
	Returns:
		Dict[str, float]: A dictionary containing precision, recall, and F1 score.
	"""
	true_positive = 0
	false_positive = 0
	false_negative = 0
	for prediction,target in zip(predictions,targets):
		for target_tuple in target:
			if target_tuple in prediction:
				true_positive += 1
			else:
				false_negative += 1
		false_positive += sum(1 for pred in prediction if pred not in target)
	precision = true_positive/(true_positive + false_positive) if (true_positive + false_positive) > 0 else 0
	recall = true_positive/(true_positive + false_negative) if (true_positive + false_negative) > 0 else 0
	f1 = (2 * recall * precision)/(recall + precision) if (recall + precision) > 0 else 0
	return {
		f"precision_{task}" : precision,
		f"recall_{task}" : recall,
		f"f1_{task}" : f1
	}

def form_aoste_triplet(triplets: List[List[Dict[str, str]]]) -> str:
	"""
	Form AOSTE triplets from the given predictions.

	Args:
		predictions (List[List[Dict[str, str]]]): List of predicted triplets.
	Returns:
		str: A string representation of the AOSTE triplets, the format is {aspect}:{opinion}:{sentiment},{aspect}:{opinion}:{sentiment}.
	"""
	aoste_triplets = []
	for triplet in triplets:
		aspect = triplet.get('A', '')
		opinion = triplet.get('O', '')
		sentiment = triplet.get('S', '')
		aoste_triplets.append(f"{aspect}:{opinion}:{sentiment}")
	return ', '.join(aoste_triplets)

In [3]:
form_aoste_triplet([{'A': 'over all', 'O': 'baik', 'S': 'positive'}, {'A': 'air hot waternya', 'O': 'akan lebih memuaskan jika air hot waternya bisa nyala 24jam', 'S': 'negative'}])

'over all:baik:positive, air hot waternya:akan lebih memuaskan jika air hot waternya bisa nyala 24jam:negative'

### InstructABSA to Exact Match

In [4]:
raw_instructabsa_path = 'dataset/aoste/googlemt5-base-hoasa_hotel-aoste-20260115_101411/raw_inference_results.csv'
raw_data = pd.read_csv(raw_instructabsa_path)
raw_data.head()

,text,labels,pred_labels
0,Definition: You will be given an Indonesian se...,pelayanan nya:sangat ramah:positive,pelayanan nya:sangat ramah:positive
1,Definition: You will be given an Indonesian se...,wifi:tidak bagus harus keluar kamar:negative,wifi:tidak bagus harus keluar kamar:negative
2,Definition: You will be given an Indonesian se...,kamarnya:beda:negative,kamarnya:beda:negative
3,Definition: You will be given an Indonesian se...,"over all:baik:positive, air hot waternya:akan ...","over all:baik:positive, air hot waternya:bisa ..."
4,Definition: You will be given an Indonesian se...,fasilatas:sesuia:positive,fasilitatas:suia:positive

In [5]:
raw_data['parsed_labels'] = raw_data['labels'].apply(lambda x: x.split(','))
raw_data['parsed_pred_labels'] = raw_data['pred_labels'].apply(lambda x: x.split(','))

In [6]:
results = calculate_metrics(raw_data['parsed_pred_labels'].to_list(), raw_data['parsed_labels'].to_list(), task='instructabsa')
for metric_name, metric_value in results.items():
	metric_value *= 100
	print(f"{metric_name}: {metric_value:.2f}%")

precision_instructabsa: 65.16%
recall_instructabsa: 63.79%
f1_instructabsa: 64.47%

In [7]:
metrics_instructabsa(raw_data['labels'], raw_data['pred_labels'])

(0.7145688800792864, 0.7, 0.7072094163805788, None)

In [8]:
raw_data['labels']

0                     pelayanan nya:sangat ramah:positive
1            wifi:tidak bagus harus keluar kamar:negative
2                                  kamarnya:beda:negative
3       over all:baik:positive, air hot waternya:akan ...
4                               fasilatas:sesuia:positive
                              ...
1281                            ac nya:gk dingin:negative
1282    kamarnya:enak luas:positive, sprei:masih lemba...
1283    kebersihan:sangat tidak baik:negative, kamar:b...
1284    pelayanan staf hotel:baik:positive, layanan ho...
1285    harga:cukup murah:positive, pelayanan:baik:pos...
Name: labels, Length: 1286, dtype: object

### Exact Match to InstructABSA

In [11]:
from glob import glob
paths = glob('outputs/evals/hotel_reviews/*/mvp/seed_*/*/*/*/*/voting_results.json')
paths += glob('outputs/evals/hotel_reviews/*/mvp_aos/seed_*/*/*/*/*/inference_results.json')
paths

['outputs/evals/hotel_reviews/jav/mvp/seed_123/20260402_134023_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/jav/mvp/seed_31415/20260402_152635_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/jav/mvp/seed_9584/20260402_124702_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/jav/mvp/seed_777/20260402_161858_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/jav/mvp/seed_2024/20260402_143335_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/eng/mvp/seed_123/20260402_091332_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/eng/mvp/seed_31415/20260402_110041_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/eng/mvp/seed_9584/20260402_082012_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/eng/mvp/seed_777/20260402_115352_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/eng/mvp/seed_2024/20260402_100706_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/min/mvp/seed_123/20260402_230212_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/min/mvp/seed_31415/20260403_005425_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/min/mvp/seed_9584/20260402_220427_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/min/mvp/seed_777/20260403_015104_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/min/mvp/seed_2024/20260402_235904_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/mad/mvp/seed_123/20260402_181248_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/mad/mvp/seed_31415/20260402_200945_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/mad/mvp/seed_9584/20260402_171544_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/mad/mvp/seed_777/20260402_210657_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/mad/mvp/seed_2024/20260402_191101_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/sun/mvp/seed_123/20260403_034245_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/sun/mvp/seed_31415/20260403_052815_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/sun/mvp/seed_9584/20260403_024718_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/sun/mvp/seed_777/20260403_062208_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/sun/mvp/seed_2024/20260403_043445_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_123/20260226_091905_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/constrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_123/20260226_091905_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_31415/20260226_115322_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/constrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_31415/20260226_115322_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_9584/20260226_073028_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/constrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_9584/20260226_073028_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_777/20260226_131009_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/constrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_777/20260226_131009_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_2024/20260226_103747_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/constrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/indo/mvp/seed_2024/20260226_103747_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-7760/checkpoint-7760/unconstrained_decoding/voting_results.json',
 'outputs/evals/hotel_reviews/jav/mvp_aos/seed_123/20260403_083308_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/jav/mvp_aos/seed_31415/20260403_085651_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/jav/mvp_aos/seed_9584/20260403_082151_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/jav/mvp_aos/seed_777/20260403_090813_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/jav/mvp_aos/seed_2024/20260403_084444_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/eng/mvp_aos/seed_123/20260403_073649_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/eng/mvp_aos/seed_31415/20260403_075927_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/eng/mvp_aos/seed_9584/20260403_072459_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/eng/mvp_aos/seed_777/20260403_081036_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/eng/mvp_aos/seed_2024/20260403_074819_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/min/mvp_aos/seed_123/20260403_102622_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/min/mvp_aos/seed_31415/20260403_104906_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/min/mvp_aos/seed_9584/20260403_101519_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/min/mvp_aos/seed_777/20260403_110033_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/min/mvp_aos/seed_2024/20260403_103746_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/mad/mvp_aos/seed_123/20260403_093055_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/mad/mvp_aos/seed_31415/20260403_095312_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/mad/mvp_aos/seed_9584/20260403_091943_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/mad/mvp_aos/seed_777/20260403_100416_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/mad/mvp_aos/seed_2024/20260403_094157_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/sun/mvp_aos/seed_123/20260403_112306_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/sun/mvp_aos/seed_31415/20260403_114527_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/sun/mvp_aos/seed_9584/20260403_111143_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/sun/mvp_aos/seed_777/20260403_115642_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/sun/mvp_aos/seed_2024/20260403_113407_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_123/20260226_054857_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/constrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_123/20260226_054857_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_31415/20260226_065122_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/constrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_31415/20260226_065122_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_9584/20260226_053118_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/constrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_9584/20260226_053118_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_777/20260226_070836_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/constrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_777/20260226_070836_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_2024/20260226_063347_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/constrained_decoding/inference_results.json',
 'outputs/evals/hotel_reviews/indo/mvp_aos/seed_2024/20260226_063347_train_model-Qwen2.5-0.5B_lr-5e-05_bs-4_epochs-10/checkpoint-1560/checkpoint-1560/unconstrained_decoding/inference_results.json']

In [12]:
data_metrics = []
for output_path in paths:
	lang = output_path.split('/')[3]
	seed = output_path.split('/')[5].split('_')[1]
	dataset_folder = output_path.split('/')[4]
	use_constrained_decoding = output_path.split('/')[-2]
	if use_constrained_decoding == 'constrained_decoding':
		use_constrained_decoding = True
	else:
		use_constrained_decoding = False
	with open(output_path, 'r') as f:
		data = json.load(f)
	df_data_output = pd.DataFrame(data)
	df_data_output['target_aoste'] = df_data_output['target'].apply(lambda x: form_aoste_triplet(parse_absa_string(x)))
	df_data_output['prediction_aoste'] = df_data_output['prediction'].apply(lambda x: form_aoste_triplet(parse_absa_string(x)))
	prec, rec, f1, _ = metrics_instructabsa(df_data_output['target_aoste'].to_list(), df_data_output['prediction_aoste'].to_list())
	data_metrics.append({
		'lang': lang,
		'seed': seed,
		'dataset_folder': dataset_folder,
		'use_constrained_decoding': use_constrained_decoding,
		'precision': prec,
		'recall': rec,
		'f1': f1
	})

In [13]:
df_metrics_aoste = pd.DataFrame(data_metrics)
df_metrics_aoste.loc[df_metrics_aoste['use_constrained_decoding'] == False]

,lang,seed,dataset_folder,use_constrained_decoding,precision,recall,f1
0,jav,123,mvp,False,0.614555,0.590100,0.602080
1,jav,31415,mvp,False,0.611392,0.586865,0.598878
2,jav,9584,mvp,False,0.613045,0.586865,0.599669
3,jav,777,mvp,False,0.621968,0.597218,0.609341
4,jav,2024,mvp,False,0.611545,0.582659,0.596753
5,eng,123,mvp,False,0.707161,0.692982,0.700000
6,eng,31415,mvp,False,0.706863,0.690476,0.698574
7,eng,9584,mvp,False,0.703928,0.690476,0.697137
8,eng,777,mvp,False,0.714102,0.696429,0.705155
9,eng,2024,mvp,False,0.716104,0.704887,0.710452
10,min,123,mvp,False,0.702782,0.689467,0.696061
11,min,31415,mvp,False,0.704515,0.681439,0.692785
12,min,9584,mvp,False,0.699106,0.678227,0.688509
13,min,777,mvp,False,0.695082,0.680796,0.687865
14,min,2024,mvp,False,0.709067,0.685613,0.697143
15,mad,123,mvp,False,0.520426,0.486990,0.503153
16,mad,31415,mvp,False,0.510431,0.471571,0.490232
17,mad,9584,mvp,False,0.530992,0.495342,0.512548
18,mad,777,mvp,False,0.520595,0.483135,0.501166
19,mad,2024,mvp,False,0.528946,0.493093,0.510391
20,sun,123,mvp,False,0.660415,0.637345,0.648675
21,sun,31415,mvp,False,0.666994,0.647507,0.657106
22,sun,9584,mvp,False,0.657791,0.635440,0.646422
23,sun,777,mvp,False,0.660210,0.638615,0.649233
24,sun,2024,mvp,False,0.671829,0.647507,0.659444
26,indo,123,mvp,False,0.721766,0.689216,0.705115
28,indo,31415,mvp,False,0.726130,0.698366,0.711977
30,indo,9584,mvp,False,0.723484,0.697712,0.710364
32,indo,777,mvp,False,0.725971,0.696078,0.710711
34,indo,2024,mvp,False,0.709634,0.683660,0.696405
35,jav,123,mvp_aos,False,0.589103,0.594630,0.591853
36,jav,31415,mvp_aos,False,0.605178,0.604982,0.605080
37,jav,9584,mvp_aos,False,0.598783,0.604982,0.601867
38,jav,777,mvp_aos,False,0.593443,0.585571,0.589481
39,jav,2024,mvp_aos,False,0.598957,0.594306,0.596622
40,eng,123,mvp_aos,False,0.695422,0.699561,0.697486
41,eng,31415,mvp_aos,False,0.698728,0.705514,0.702104
42,eng,9584,mvp_aos,False,0.705592,0.715539,0.710530
43,eng,777,mvp_aos,False,0.695774,0.701441,0.698596
44,eng,2024,mvp_aos,False,0.691783,0.698935,0.695341
45,min,123,mvp_aos,False,0.688020,0.689788,0.688903
46,min,31415,mvp_aos,False,0.680279,0.690109,0.685159
47,min,9584,mvp_aos,False,0.679532,0.689788,0.684622
48,min,777,mvp_aos,False,0.679949,0.684971,0.682451
49,min,2024,mvp_aos,False,0.681439,0.681439,0.681439
50,mad,123,mvp_aos,False,0.482613,0.477032,0.479806
51,mad,31415,mvp_aos,False,0.489307,0.485063,0.487175
52,mad,9584,mvp_aos,False,0.484273,0.474783,0.479481
53,mad,777,mvp_aos,False,0.495552,0.483135,0.489265
54,mad,2024,mvp_aos,False,0.483235,0.472213,0.477660
55,sun,123,mvp_aos,False,0.635076,0.640521,0.637787
56,sun,31415,mvp_aos,False,0.638056,0.642109,0.640076
57,sun,9584,mvp_aos,False,0.639432,0.643696,0.641557
58,sun,777,mvp_aos,False,0.636852,0.639886,0.638365
59,sun,2024,mvp_aos,False,0.650854,0.653541,0.652195
61,indo,123,mvp_aos,False,0.706874,0.699020,0.702925
63,indo,31415,mvp_aos,False,0.703012,0.701634,0.702323
65,indo,9584,mvp_aos,False,0.699836,0.698693,0.699264
67,indo,777,mvp_aos,False,0.697629,0.701961,0.699788
69,indo,2024,mvp_aos,False,0.705631,0.700327,0.702969

In [ ]:
# Store the metrics in a csv file