In [1]:
import pandas as pd
import numpy as np
import json
import re
from ast import literal_eval
import importlib
from dotenv import load_dotenv
import os
os.chdir('..')

In [2]:
# Load environment variables from .env file
load_dotenv()

True

In [3]:
# Set GEMINI_API_KEY environment variable with your API key
os.environ['GEMINI_API_KEY'] = os.getenv('GEMINI_API_KEY')

In [4]:
import base64
from google import genai
from google.genai import types
from copy import deepcopy

In [5]:
def generate(prompt):
	client = genai.Client(
			api_key=os.environ.get("GEMINI_API_KEY"),
		)

	model = "gemini-2.5-flash"
	contents = [
		types.Content(
			role="user",
			parts=[
				types.Part.from_text(
					text=prompt
				),
			],
		),
	]
	generate_content_config = types.GenerateContentConfig(
		temperature=0.75,
		top_p=0.9,
		top_k=40,
		max_output_tokens=8192,
		thinking_config=types.ThinkingConfig(thinking_budget=-1), # Dynamic thinking = -1, no thinking = 0
		response_mime_type="application/json",
		system_instruction=[
			types.Part.from_text(
				text="""You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and English."""
			),
		],
	)
		
	response = client.models.generate_content(
		model=model, contents=contents, config=generate_content_config
	)
	# print(response.text)
	return response

from typing import List, Dict
import re
def parse_absa_string(text: str) -> List[Dict[str, str]]:
    """
    Parses a string formatted as "[A] aspect [O] opinion [S] sentiment" into a list of dictionaries.
    Each dictionary contains the tag as the key and the corresponding value.
    For example, "[A] [O] [S] [A] harga [O] terjangkau [S] positive [SSEP] [A] fasilitas [O] nyaman [S] positive" becomes:
    [{'A': 'harga', 'S': 'positive', 'O': 'terjangkau'},
    {'A': 'fasilitas', 'S': 'positive', 'O': 'nyaman'}].

    Args:
        text (str): ABSA string output to be parsed.

    Returns:
        List[Dict[str, str]]: List of dictionaries of parsed ABSA output.

    """
    pattern = r"\[(\w+)\]\s*([^[]+)"
    matches = re.findall(pattern, text)

    result = []
    current_dict = {}

    for tag, content in matches:
        if tag == "SSEP":  # Sentence separator -> Start a new dictionary
            result.append(current_dict)
            current_dict = {}
        else:
            current_dict[tag] = content.strip()

    if current_dict:  # Append the last sentence if it exists
        result.append(current_dict)

    return result

In [14]:
dataset_folder = 'mvp_aos'
dataset_type = 'hotel_reviews'
lang = 'indo'
split = 'train'
dataset_path = f'dataset/{dataset_type}/{lang}/{dataset_folder}/{split}.json'
with open(dataset_path, 'r') as f:
	dataset = json.load(f)

In [15]:
dataset_unique = []
for instance in dataset:
	if instance['element_order'] == 'aos':
		dataset_unique.append(deepcopy(instance))

In [16]:
dataset_single_triplet = []
for instance in dataset_unique:
	triplets = parse_absa_string(instance['target'])
	for triplet in triplets:
		new_instance = deepcopy(instance)
		new_instance['target'] = f"[A] {triplet.get('A', '')} [O] {triplet.get('O', '')} [S] {triplet.get('S', '')}"
		dataset_single_triplet.append(new_instance)

In [17]:
df_dataset = pd.DataFrame(dataset_unique)
df_dataset

,sentence_id,instance_id,input,target,element_order,task_elements
0,0,0,kamar saya ada kendala di ac tidak berfungsi o...,[A] ac [O] tidak berfungsi optimal [S] negativ...,aos,aos
1,1,5,tempatnya bagus . kolam renangnya bersih . [A]...,[A] tempatnya [O] bagus [S] positive\n[A] kola...,aos,aos
2,2,10,"oke banget , tetapi ac nya tidak bisa diatur s...",[A] ac nya [O] tidak bisa diatur suhu nya [S] ...,aos,aos
3,3,15,keren . nyaman semuanya . [A] [O] [S],[A] semuanya [O] nyaman [S] positive\n[A] null...,aos,aos
4,4,20,"tidak dapat snack . setelah di keluhan , baru ...",[A] snack [O] tidak dapat [S] negative,aos,aos
...,...,...,...,...,...,...
2477,2495,12475,wifi kurang joss . [A] [O] [S],[A] wifi [O] kurang joss [S] negative,aos,aos
2478,2496,12480,"kamar cukup bersih , hanya sempit , . [A] [O] [S]",[A] kamar [O] cukup bersih [S] positive\n[A] k...,aos,aos
2479,2497,12485,"nyaman , bersih , dan pelayananya sangat ramah...",[A] pelayananya [O] sangat ramah [S] positive\...,aos,aos
2480,2498,12490,sangat kecewa dengan kamar dan pelayanan stafn...,[A] kamar [O] sangat kecewa [S] negative\n[A] ...,aos,aos
2481,2499,12495,"sayang , air panasnya tidak terlalu panas , ja...","[A] air panasnya [O] tidak terlalu panas , jad...",aos,aos

In [18]:
check_list = df_dataset['sentence_id'].to_list()
# Check if check_list is ordered from smallest to largest (missing indexes is allowed, just make sure the order is correct)
is_ordered = all(earlier <= later for earlier, later in zip(check_list, check_list[1:]))
print(f"Is the sentence_id list ordered? {is_ordered}")

Is the sentence_id list ordered? True

In [20]:
with open(f'notebooks/prompt_translate/translate-triplet-jav.txt', 'r') as f:
	prompt_template = f.read()
print(prompt_template)

### Instruction
You will be given input-output pairs of Aspect Sentiment Triplet Extraction.
Given an Indonesian text and triplets consist of aspect term, opinion term, and sentiment polarity, translate all of them to Ngoko-level of Javanese. Ngoko-level Javanese is the informal variety of Javanese used in daily conversations between friends or people of the same age.
The order of the triplet is (aspect term, opinion term, sentiment polarity).
Below is the definition of each element in the triplet:
- The aspect term refers to a specific feature, attribute, or aspect of a product or service on which a user can express an opinion. Explicit aspect terms appear explicitly as a substring of the given text. The aspect term might be “NULL” for the implicit aspect.
- The sentiment polarity refers to the degree of positivity, negativity or neutrality expressed in the opinion towards a particular aspect or feature of a product or service, and the available polarities include: “positive”, “negative” and “neutral”. “neutral” means mildly positive or mildly negative.
- The opinion term refers to the sentiment or attitude expressed by a user towards a particular aspect or feature of a product or service. Explicit opinion terms appear explicitly as a substring of the given text. The opinion term might be "NULL" for the implicit opinion.

For the special case when the triplets is empty, just return an empty list for the translated triplets component.

### Step-by-step Instruction
1. Carefully read the sentence and its triplets to understand the context.
2. Translate the sentence, maintaining the original meaning, tone, style, and cultural nuances.
3. Translate the triplets of the sentence. Ensure that all elements of the triplet still matches the sentence. The translated aspect term and the opinion term must exist literally in the translated sentence. Do not make up your own words for the triplet translation part.
4. Ensure that any idiomatic expressions are adapted appropriately to fit the target language.
5. Review the translation for any grammatical or syntactical errors.
6. Write the translations in json format.

### Example:
Text Input: "sebenarnya kamar baik tetapi kurang profesional , di kasih tahu sarapan nasi goreng , minta di antar jam 8.30 ehh datang jam 9 itu pun di telepon dulu dan yang datang bahkan mie muah telor . hm ."
Triplets: [(kamar, baik, positive), (null, kurang profesional, negative)]
Output:
{
    "translated_text": "Sakjane kamare apik, nanging kurang profesional, dikandani yen sarapan sego goreng, njaluk diterke jam 8.30 ehh tekone jam 9 iku wae kudu ditelpon disik lan sing teko malah mie godhog endhog . hm.",
    "translated_triplets": [
        {
            "aspect_term": "kamar",
            "opinion_term": "apik",
            "sentiment_polarity": "positive"
        },
        {
            "aspect_term": "null",
            "opinion_term": "kurang profesional",
            "sentiment_polarity": "negative"
        }
    ]
}

### Inference:

Text Input: {text-input}
Triplets: {input-triplets}
Output:

### Individual API request

In [36]:
from tqdm import tqdm
from time import sleep
from ast import literal_eval

outputs = {}
outputs_text = {}
for idx, row in tqdm(df_dataset.iterrows(), desc="Translating triplets", total=df_dataset.shape[0]):
	input_text = row['input'].replace('[A] [O] [S]', '').strip()
	triplets = parse_absa_string(row['target'])
	target_text = []
	for triplet in triplets:
		target_text.append(f"({triplet.get('A', 'err_empty')}, {triplet.get('O', 'err_empty')}, {triplet.get('S', 'err_empty')})")
	target_text = '[' + ', '.join(target_text) + ']'
	prompt = prompt_template.replace('{text-input}', input_text).replace('{input-triplets}', target_text)
	while True:
		try:
			output = generate(prompt)
			outputs[idx] = output
			outputs_text[idx] = literal_eval(output.text)
			outputs_text[idx]['text'] = input_text
			outputs_text[idx]['triplets'] = target_text
			break
		except Exception as e:
			print(f"Error: {e}")
			sleep(3.0)  # Wait for 3 seconds before retrying
			continue
	
	# Write to json file after each successful generation
	os.makedirs(f'temp/translation_output/eng/{dataset_folder}', exist_ok=True)
	with open(f'temp/translation_output/eng/{dataset_folder}/{os.path.basename(dataset_path)}', 'w') as f:
		json.dump(outputs_text, f, indent=4, ensure_ascii=False)
	
	if idx == 10:
		break

Translating triplets:   0%|          | 10/2482 [00:59<4:06:51,  5.99s/it]

### Batch API request

In [21]:
inline_requests = []
temp_for_jsonl = []
for idx, row in df_dataset.iterrows():
	input_text = row['input'].replace('[A] [O] [S]', '').strip()
	triplets = parse_absa_string(row['target'])
	target_text = []
	for triplet in triplets:
		target_text.append(f"({triplet.get('A', 'err_empty')}, {triplet.get('O', 'err_empty')}, {triplet.get('S', 'err_empty')})")
	target_text = '[' + ', '.join(target_text) + ']'
	prompt = prompt_template.replace('{text-input}', input_text).replace('{input-triplets}', target_text)
	
	inline_request = {
		"contents": [
			{
				"role": "user",
				"parts": [
					{
						"text": prompt
					}
				]
			}
		],
		"generation_config": {
			"temperature": 0.75,
			"top_p": 0.9,
			"top_k": 40,
			"max_output_tokens": 8192,
			"thinking_config": {
				"thinking_budget": -1
			},
			"response_mime_type": "application/json",
		},
		"system_instruction": {
			"parts": [
				{
					'text': "You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and Javanese."
				}
			]
		}
	}
	inline_requests.append(inline_request)

	temp_for_jsonl.append({
		'key': f'request-{row["sentence_id"]}',
		'request': inline_request
	})
	# if idx == 4:
	# 	break

In [22]:
len(inline_requests), len(temp_for_jsonl)

(2482, 2482)

In [23]:
# print(inline_requests[-10]['contents'][0]['parts'][0]['text'])
print(temp_for_jsonl[-1])

{'key': 'request-2499', 'request': {'contents': [{'role': 'user', 'parts': [{'text': '### Instruction\nYou will be given input-output pairs of Aspect Sentiment Triplet Extraction.\nGiven an Indonesian text and triplets consist of aspect term, opinion term, and sentiment polarity, translate all of them to Ngoko-level of Javanese. Ngoko-level Javanese is the informal variety of Javanese used in daily conversations between friends or people of the same age.\nThe order of the triplet is (aspect term, opinion term, sentiment polarity).\nBelow is the definition of each element in the triplet:\n- The aspect term refers to a specific feature, attribute, or aspect of a product or service on which a user can express an opinion. Explicit aspect terms appear explicitly as a substring of the given text. The aspect term might be “NULL” for the implicit aspect.\n- The sentiment polarity refers to the degree of positivity, negativity or neutrality expressed in the opinion towards a particular aspect or feature of a product or service, and the available polarities include: “positive”, “negative” and “neutral”. “neutral” means mildly positive or mildly negative.\n- The opinion term refers to the sentiment or attitude expressed by a user towards a particular aspect or feature of a product or service. Explicit opinion terms appear explicitly as a substring of the given text. The opinion term might be "NULL" for the implicit opinion.\n\nFor the special case when the triplets is empty, just return an empty list for the translated triplets component.\n\n### Step-by-step Instruction\n1. Carefully read the sentence and its triplets to understand the context.\n2. Translate the sentence, maintaining the original meaning, tone, style, and cultural nuances.\n3. Translate the triplets of the sentence. Ensure that all elements of the triplet still matches the sentence. The translated aspect term and the opinion term must exist literally in the translated sentence. Do not make up your own words for the triplet translation part.\n4. Ensure that any idiomatic expressions are adapted appropriately to fit the target language.\n5. Review the translation for any grammatical or syntactical errors.\n6. Write the translations in json format.\n\n### Example:\nText Input: "sebenarnya kamar baik tetapi kurang profesional , di kasih tahu sarapan nasi goreng , minta di antar jam 8.30 ehh datang jam 9 itu pun di telepon dulu dan yang datang bahkan mie muah telor . hm ."\nTriplets: [(kamar, baik, positive), (null, kurang profesional, negative)]\nOutput:\n{\n    "translated_text": "Sakjane kamare apik, nanging kurang profesional, dikandani yen sarapan sego goreng, njaluk diterke jam 8.30 ehh tekone jam 9 iku wae kudu ditelpon disik lan sing teko malah mie godhog endhog . hm.",\n    "translated_triplets": [\n        {\n            "aspect_term": "kamar",\n            "opinion_term": "apik",\n            "sentiment_polarity": "positive"\n        },\n        {\n            "aspect_term": "null",\n            "opinion_term": "kurang profesional",\n            "sentiment_polarity": "negative"\n        }\n    ]\n}\n\n### Inference:\n\nText Input: sayang , air panasnya tidak terlalu panas , jadi kalau mandi kedinginan . hhehe .\nTriplets: [(air panasnya, tidak terlalu panas , jadi kalau mandi kedinginan, negative)]\nOutput:\n'}]}], 'generation_config': {'temperature': 0.75, 'top_p': 0.9, 'top_k': 40, 'max_output_tokens': 8192, 'thinking_config': {'thinking_budget': -1}, 'response_mime_type': 'application/json'}, 'system_instruction': {'parts': [{'text': 'You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and Javanese.'}]}}}

In [24]:
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

In [25]:
lang_target = 'jav'

In [26]:
# Create a jsonl file for inline requests
os.makedirs(f'temp/translation_output/{lang_target}/{dataset_folder}', exist_ok=True)
with open(f'temp/translation_output/{lang_target}/{dataset_folder}/inline_requests_{lang_target}_{split}.jsonl', 'w') as f:
	for item in temp_for_jsonl:
		f.write(json.dumps(item, ensure_ascii=False) + '\n')

In [27]:
# Upload the file to the File API
uploaded_file = client.files.upload(
    file=f'temp/translation_output/{lang_target}/{dataset_folder}/inline_requests_{lang_target}_{split}.jsonl',
    config=types.UploadFileConfig(display_name=f'inline_requests_{lang_target}_{split}', mime_type='jsonl')
)

print(f"Uploaded file: {uploaded_file.name}")

Uploaded file: files/2r5jaouu9wdj

In [29]:
from google import genai

# Assumes `uploaded_file` is the file object from the previous step
file_batch_job = client.batches.create(
    model="gemini-2.5-flash",
    src=uploaded_file.name,
    config={
        'display_name': f"file-upload-job-translation-{lang_target}-{split}-fixed",
    },
)

print(f"Created batch job: {file_batch_job.name}")

Created batch job: batches/lpxh4xaknvxckykmrk9hjbazv87anyyklal4

In [30]:
# List all batches
batches = client.batches.list()
for batch in batches:
    print(f"Batch ID: {batch.name}, State: {batch.state.name}, Display Name: {batch.display_name}")

Batch ID: batches/lpxh4xaknvxckykmrk9hjbazv87anyyklal4, State: JOB_STATE_PENDING, Display Name: file-upload-job-translation-jav-train-fixed
Batch ID: batches/9udm06rnexogkfmqcxmav7oblt1g6lm467z3, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-jav-test
Batch ID: batches/jbu1m7rk7953auz9a0xipwxxl2bh14i0q42j, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-jav-dev
Batch ID: batches/675kvbrqpt3igvutlowozqsdjjxlalad5eaf, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-jav-train
Batch ID: batches/65azlnc2oetwg4x6np88dz9wgmwsyo98ki9o, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-sunda-dev-all
Batch ID: batches/mucz1j6fvlq0n4krwws4528xk181u4lxfnqy, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-eng-dev-all
Batch ID: batches/jyjjxzt3feea2hrx8ft25cpwu7e1mdxhge3r, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-sunda-train-all
Batch ID: batches/j64igjih81kj18rzkctzv5yfa7pk1arw0uaf, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-sunda-train
Batch ID: batches/ggref704rxuzp94z6nrqm5nkt1jwihae7n2n, State: JOB_STATE_SUCCEEDED, Display Name: aste-long-token-job
Batch ID: batches/s70rg9mcrhz1jgpmda0e4jfmz79n5324sh8s, State: JOB_STATE_SUCCEEDED, Display Name: hoasa-augment-job
Batch ID: batches/jklx0tqwvxnas5h5bfn3l6wk6wztv4ztebl6, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-sunda-train
Batch ID: batches/1qi0dsiovljruakbln7knfizvtpa43gthfn9, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/d14hsrjoulu7by2a1uin6rjiep6pzpl29zym, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/4uewhtitdcuub6z9663vc8t94subfq4n6qx6, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/mdmaao1nf2gpndgpa8pqzhgxvuwtktgj2e3u, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/dea1kpv8fspa9wpfz9h20xmx7uvnyazf8fnr, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/l17q9aj8zbhjk6znqc8jpo28jomk5izvnu3i, State: JOB_STATE_SUCCEEDED, Display Name: hoasa-batch-job
Batch ID: batches/pl3jwvqdf3olq9gq5cktudc2ufpcp7qeni7n, State: JOB_STATE_SUCCEEDED, Display Name: hoasa-batch-job
Batch ID: batches/y76wencie9ce0ul19qh2atajli6f6fi09zh9, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo_sunda-test
Batch ID: batches/7566g4tpokgt1intakwz09hvj6160li42202, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo_sunda-train
Batch ID: batches/asmmwwk6f8kfkavhj70cth2l60zwwaf3hl6s, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo-train-1000onwards
Batch ID: batches/5crm0h0t2580p641oyxpdhpku0q5h9o8ahzp, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo-1
Batch ID: batches/sde88za41ogfgscv3eg94ezopyjeirkhiu1x, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo-1
Batch ID: batches/evg9i1wyd8gvczvytcxt9omherlhibe0vtum, State: JOB_STATE_SUCCEEDED, Display Name: job-1-test
Batch ID: batches/xr5ky0oempio6kujvbxemftbm98goz78mw23, State: JOB_STATE_SUCCEEDED, Display Name: job-1-test

In [31]:
from time import sleep

# Use the name of the job you want to check
# e.g., inline_batch_job.name from the previous step
job_name = "batches/lpxh4xaknvxckykmrk9hjbazv87anyyklal4"  # (e.g. 'batches/your-batch-id')
batch_job = client.batches.get(name=job_name)

completed_states = set([
    'JOB_STATE_SUCCEEDED',
    'JOB_STATE_FAILED',
    'JOB_STATE_CANCELLED',
    'JOB_STATE_EXPIRED',
])

print(f"Polling status for job: {job_name}")
batch_job = client.batches.get(name=job_name) # Initial get
while batch_job.state.name not in completed_states:
  print(f"Current state: {batch_job.state.name}")
  sleep(30) # Wait for 30 seconds before polling again
  batch_job = client.batches.get(name=job_name)

print(f"Job finished with state: {batch_job.state.name}")
if batch_job.state.name == 'JOB_STATE_FAILED':
    print(f"Error: {batch_job.error}")

Polling status for job: batches/lpxh4xaknvxckykmrk9hjbazv87anyyklal4
Current state: JOB_STATE_PENDING
Current state: JOB_STATE_RUNNING
Current state: JOB_STATE_RUNNING
Current state: JOB_STATE_RUNNING
Job finished with state: JOB_STATE_SUCCEEDED

In [25]:
from tqdm import tqdm

In [26]:
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

# Use the name of the job you want to check
# e.g., inline_batch_job.name from the previous step
job_name = "batches/65azlnc2oetwg4x6np88dz9wgmwsyo98ki9o"
batch_job = client.batches.get(name=job_name)

outputs = {}
outputs_text = {}

if batch_job.state.name == 'JOB_STATE_SUCCEEDED':

	# If batch job was created with a file
	if batch_job.dest and batch_job.dest.file_name:
		# Results are in a file
		result_file_name = batch_job.dest.file_name
		print(f"Results are in file: {result_file_name}")

		print("Downloading result file content...")
		file_content = client.files.download(file=result_file_name)
		# Process file_content (bytes) as needed
		lines = file_content.decode('utf-8').splitlines()
		for i, line in tqdm(enumerate(lines)):
			result = json.loads(line)
			key = result['key'].split('-')[-1]

			# print(result)
			if 'response' in result:
				try:
					outputs_text[key] = literal_eval(result['response']['candidates'][0]['content']['parts'][0]['text'])
				except Exception as e:
					print(f"Error in Response {i+1}: {e}")
					outputs_text[key] = result['response']  # Fallback
					outputs_text[key] = {
						'translated_text': '',
						'translated_triplets': [],
					}
			elif 'error' in result:
				print(f"Error: {result['error']}")

	# If batch job was created with inline request
	# (for embeddings, use batch_job.dest.inlined_embed_content_responses)
	elif batch_job.dest and batch_job.dest.inlined_responses:
		# Results are inline
		print("Results are inline:")
		for i, inline_response in tqdm(enumerate(batch_job.dest.inlined_responses)):
			if inline_response.response:
				# Accessing response, structure may vary.
				try:
					outputs_text[i] = literal_eval(inline_response.response.text)
				except Exception as e:
					print(f"Error in Response {i+1}: {e}")
					outputs_text[i] = inline_response.response  # Fallback
					outputs_text[i] = {
						'translated_text': '',
						'translated_triplets': [],
					}
			elif inline_response.error:
				print(f"Error: {inline_response.error}")
	else:
		print("No results found (neither file nor inline).")
else:
	print(f"Job did not succeed. Final state: {batch_job.state.name}")
	if batch_job.error:
		print(f"Error: {batch_job.error}")

Results are in file: files/batch-65azlnc2oetwg4x6np88dz9wgmwsyo98ki9o
Downloading result file content...

1000it [00:00, 17495.15it/s]

In [27]:
# for i, inline_response in tqdm(enumerate(batch_job.dest.inlined_responses)):
# 	if inline_response.response:
# 		# Accessing response, structure may vary.
# 		try:
# 			print(f"----------------- Response {i+1} -----------------")
# 			print(literal_eval(inline_response.response.text))
# 			print(inline_requests[i]['contents'][0]['parts'][0]['text'].split('### Inference:')[-1].strip())
# 		except Exception as e:
# 			print(f"Error in Response {i+1}: {e}")
# 			# outputs[i] = inline_response.response  # Fallback
# 			print(inline_response.response.text)
# 	elif inline_response.error:
# 		print(f"Error: {inline_response.error}")

In [28]:
dataset_path

'hotel_dataset/indo/corrected_splitopinion_typocorrected_aos/hotel_aste_dev_augmented.json'

In [29]:
save_path = f'temp/translation_output/{lang_target}/{dataset_folder}/{os.path.basename(dataset_path)}'

In [30]:
save_path

'temp/translation_output/sunda/corrected_splitopinion_typocorrected_aos/hotel_aste_dev_augmented.json'

In [31]:
os.makedirs(f'temp/translation_output/{lang_target}/{dataset_folder}', exist_ok=True)
with open(save_path, 'w') as f:
	json.dump(outputs_text, f, indent=4, ensure_ascii=False)
print(f"Saved translated outputs to {save_path}")

Saved translated outputs to temp/translation_output/sunda/corrected_splitopinion_typocorrected_aos/hotel_aste_dev_augmented.json

## Preprocess

In [32]:
with open(save_path, 'r') as f:
	outputs_text = json.load(f)

In [33]:
def add_space_around_punctuation(text):
    # Except for '-'
    # Ensure space before punctuation
    text = re.sub(r'(\S)([.,!?\(\)\"\';:+/]+)', r'\1 \2', text)
    # Ensure space after punctuation
    text = re.sub(r'([.,!?\(\)\"\';:+/]+)(\S)', r'\1 \2', text)
    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)
    # Ensure punctuation sequences like '...' are split into spaced dots
    text = re.sub(r'([.]{2,})', lambda m: ' '.join(m.group(1)), text)
    return text.strip()

In [34]:
len(outputs_text)

1000

In [35]:
df_dataset

,sentence_id,instance_id,task_elements,input,target,element_order
0,2500,12500,aos,pintu geser kurang rapat . [A] [O] [S],[A] pintu geser [O] kurang rapat [S] negative,aos
1,2501,12505,aos,pelayanan lumayan baik . [A] [O] [S],[A] pelayanan [O] lumayan baik [S] positive,aos
2,2502,12510,aos,air bersih untuk mck tidak ada . [A] [O] [S],[A] air bersih [O] tidak ada [S] negative,aos
3,2503,12515,aos,ternyata ada makanan ringan gratis . [A] [O] [S],[A] makanan ringan gratis [O] ada [S] positive,aos
4,2504,12520,aos,wifi buruk suka down . [A] [O] [S],[A] wifi [O] buruk [S] negative,aos
...,...,...,...,...,...,...
995,3495,17475,aos,"strategis , dekat jalan raya . [A] [O] [S]",[A] null [O] strategis [S] positive [SSEP] [A]...,aos
996,3496,17480,aos,( - ) tempatnya kurang bersih . tipetipe pengi...,[A] tempatnya [O] kurang bersih [S] negative [...,aos
997,3497,17485,aos,"mantapp , pelayanan prima . [A] [O] [S]",[A] null [O] mantapp [S] positive [SSEP] [A] p...,aos
998,3498,17490,aos,"hotel lumayan nyaman sih , tetapi dikamar saya...",[A] hotel [O] lumayan nyaman [S] positive [SSE...,aos
999,3499,17495,aos,"tidak ada yang bertulisan airy di room 107 , r...",[A] remote tv [O] tidak bisa [S] negative [SSE...,aos

In [36]:
def check_mismatches_triplet_format(outputs_text):
	mismatch_indexes = []
	mismatch_notes = {}
	for key, instance in outputs_text.items():
		translated_text = add_space_around_punctuation(instance['translated_text'].lower()).strip()
		mismatched = False
		for triplet in instance['translated_triplets']:
			aspect_term = add_space_around_punctuation(triplet['aspect_term'].lower()).strip()
			opinion_term = add_space_around_punctuation(triplet['opinion_term'].lower()).strip()
			if aspect_term not in translated_text and aspect_term != 'null':
				print(f"Mismatch in instance {key}: aspect_term '{aspect_term}' not found in {translated_text}")
				mismatch_notes[key] = mismatch_notes.get(key, []) + [f"aspect_term '{aspect_term}' not found"]
				mismatched = True
			if opinion_term not in translated_text and opinion_term != 'null':
				print(f"Mismatch in instance {key}: opinion_term '{opinion_term}' not found in {translated_text}")
				mismatch_notes[key] = mismatch_notes.get(key, []) + [f"opinion_term '{opinion_term}' not found"]
				mismatched = True
		if mismatched:
			mismatch_indexes.append(key)
	print(f"Total mismatches found: {len(mismatch_indexes)}")
	return mismatch_indexes, mismatch_notes
mismatch_indexes, mismatch_notes = check_mismatches_triplet_format(outputs_text)

Mismatch in instance 2524: opinion_term 'err_empty' not found in harga kahontal jeung deukeut ka pusat kota bandung .
Mismatch in instance 2572: opinion_term 'angger wé kitu malah beuki parah' not found in kualitas wifina goréng pisan , malah kadang-kadang sok paéh sababaraha kali . urang ngéndong di dieu , tapi kualitas wifina angger wé kitu , malah beuki parah . tulung diperhatikeun .
Mismatch in instance 2632: opinion_term 'aya di lamping pasir' not found in lokasi nu alami , ayana di lamping pasir . matak nimbulkeun suasana alam nu kacida éndahna .
Mismatch in instance 2646: opinion_term 'deukeut ti supermarket' not found in ac-na teu tiis jeung panto kamar mandi bocor , tapi sacara umum mah alus , utamana dahareunana . deukeut ti tempat dahar di luar hotél jeung supermarket .
Mismatch in instance 2688: opinion_term 'loba cucunguk' not found in loba reungit jeung cucunguk . lanténa ogé kotor pisan !
Mismatch in instance 2702: opinion_term 'tulungan dioméan' not found in tempat runtah kamar mandi téh tulungan atuh dioméan atawa diganti nu anyar . kasurna ogé ceuk kuring mah geus teu pantes dipaké .
Mismatch in instance 2709: aspect_term 'palayananana' not found in mirah mériah , pelayananana kasep . kamarna mantep pisan .
Mismatch in instance 2778: opinion_term 'teu pati jauh ti kfc' not found in alus , teu ramé . teu pati jauh ti pizza hut , kfc , jeung mcd . beresih . kolamna alus .
Mismatch in instance 2778: opinion_term 'teu pati jauh ti mcd' not found in alus , teu ramé . teu pati jauh ti pizza hut , kfc , jeung mcd . beresih . kolamna alus .
Mismatch in instance 2790: opinion_term 'jauh ti puseur kota' not found in fasilitasna mah oke lah . jauh ti supermarket jeung tempat dahar .
Mismatch in instance 2838: opinion_term 'masih kénéh aya nodana' not found in kamar mah beresih , ac gé tiis , tapi sarung bantal jeung sepré mah teu beresih , masih kénéh aya noda . jadi wé kurang genah , ménta nu anyar gé angger wé aya nodana .
Mismatch in instance 2881: aspect_term 'pamenta husus tamu' not found in kamar bau , tisu méja euweuh , tisu toilét euweuh , saprai kasurna kotor . paménta husus tamu teu kacumponan , komo kalahka dipénta bayaran .
Mismatch in instance 2932: opinion_term 'rapéh' not found in rapih jeung bersih . alus .
Mismatch in instance 3028: opinion_term 'runtah ngabarak' not found in parkiran jauh . kolam renang hareupeun kamar yi2 bau , kotor . kakara gé rék asup kamar , runtah geus ngabarak di hareupeun panto . asup kamar , lantéy leueur , meureun téh ngéplélna loba teuing sabun . geus teu aya sandal hotél deui . kamar mandi showerna ogé potong .
Mismatch in instance 3032: aspect_term 'kafena' not found in kamarna beresih , karyawanna someah , kaféna alus , ngeunah keur tempat kumpul-kumpul , aksés ka hotél gampang , tempatna stratégis di puseur kota , deukeut jeung tempat wisata , harga pas , pisan disarankeun !
Mismatch in instance 3117: opinion_term 'pindah kamar teu dilayanan' not found in tamu kuring nyarioskeun yén palayanan kamarna téh teu nyugemakeun , dipasihan kamar nu teu tiasa dikonci ti luar . matak lamun kaluar néangan tuangeun , kudu mawa ranselna turun naék ka lantai 3 . pas komplén ménta pindah kamar téh teu dilayanan alias dicuekeun , padahal tamu kuring geus 3 kali nginep di dieu .
Mismatch in instance 3155: opinion_term 'hésé ka mana-mana' not found in pelayanan alus , tapi ari rék ka mana-mana mah hésé sabab grab teu meunang asup ka daérah dinya .
Mismatch in instance 3190: aspect_term 'perna kasur' not found in goréng pisan . kasur aya urut spérma , seprai ogé . cai bau karahaan . pernya kasur gé ruksak . sabun béak . password wifi teu apal .
Mismatch in instance 3210: opinion_term 'babari néangan travel' not found in genah pisan jang istirahat nungguan kapal ngapung isuk-isuk . babari deuih néangan travel ka bandara .
Mismatch in instance 3246: opinion_term 'rusak' not found in aya sababaraha fasilitas nu geus butut malah ruksak , jiga panto nu hésé dikonci , salah sahiji keran kamar mandi nu teu bisa dipaké , saluran tipi nu kawates , tapi keur harga mah lumayan murah jeung kabersihanana alus .
Mismatch in instance 3366: aspect_term 'simbutna' not found in kotor pisan , loba sireum , simbut jeung andukna leutik . palayanan beberesihna teu daék miceun runtah padahal kuring geus 2 peuting , diantepkeun waé numpuk . sprei ogé teu puguh diganti . lamun teu diparéntahkeun beberesih kamar mah moal diberesihan .
Mismatch in instance 3476: aspect_term 'résepsionis' not found in kotor . seprai loba nodana . anduk ogé , katingalina kamar jarang diberesihan . résépsionis ukur sorangan . jadi lila mun ménta parabot mandi . lanté kotor .
Mismatch in instance 3496: aspect_term 'penginepan' not found in ( - ) tempatna kurang beresih . tipe-tipe panginepan heubeul . kuring mah terus terang rada sieun . teu kaburu sarapan da kakara siap jam 7 , padahal geus kaburu indit . ( + ) pagawéna lumayan ramah .
Total mismatches found: 22

In [37]:
mismatch_indexes = list(set(mismatch_indexes))
len(mismatch_indexes)

22

In [38]:
input_eng = {}
for key, instance in outputs_text.items():
	translated_text = add_space_around_punctuation(instance['translated_text'].lower()).strip()
	input_eng[key] = f'{translated_text} [A] [O] [S]'

target_eng = {}
for key, instance in outputs_text.items():
	triplet_texts = []
	for triplet in instance['translated_triplets']:
		aspect_term = add_space_around_punctuation(triplet['aspect_term'].lower()).strip()
		opinion_term = add_space_around_punctuation(triplet['opinion_term'].lower()).strip()
		sentiment = triplet['sentiment_polarity'].lower().strip()
		triplet_texts.append(f"[A] {aspect_term} [O] {opinion_term} [S] {sentiment}")
	target_eng[key] = ' [SSEP] '.join(triplet_texts)
print(len(input_eng), len(target_eng))

1000 1000

In [39]:
# Sort input_eng and target_eng by key to match df_dataset order
input_eng = dict(sorted(input_eng.items(), key=lambda item: int(item[0])))
target_eng = dict(sorted(target_eng.items(), key=lambda item: int(item[0])))

In [40]:
list(input_eng.values())

['panto geser kurang rapet . [A] [O] [S]',
 'palayananana lumayan alus . [A] [O] [S]',
 'cai bersih keur mck euweuh . [A] [O] [S]',
 'geuning aya cemilan haratis . [A] [O] [S]',
 'wifi goréng , mindeng down . [A] [O] [S]',
 'punten , perhatikeun deui kalengkepan kamarna . [A] [O] [S]',
 'suasana na kurang ngeunah . pikeun ngéndong kudu deposit 300 rébu , tapi bisa diganti ku ktp . [A] [O] [S]',
 'kamar-kamar nu hawana lega di dieu téh pangnyaman-nyamanna . [A] [O] [S]',
 'cai panasna téh palsu . [A] [O] [S]',
 'harga murah . loba tempat wisata peuting di sabudeureunana . [A] [O] [S]',
 'butuh pangharum kamar mandi ? nu séjénna mah mantap . [A] [O] [S]',
 'ngan ari mawa mobil mah , parkirna hésé . [A] [O] [S]',
 'dahareun nu kurang nyugemakeun . [A] [O] [S]',
 'kabersihanana tingkatkeun deui . [A] [O] [S]',
 'pituduh lokasi kudu dioméan . [A] [O] [S]',
 'pas rék check out , pelayananana euweuh pisan , jadi kapaksa ngadagoan lila . [A] [O] [S]',
 'tempatna ngeunah keur istirahat . [A] [O] [S]',
 'kamar beresih . [A] [O] [S]',
 'andukna kurang lemes . [A] [O] [S]',
 'dina informasi cenah aya cai panasna , nyatana mah euweuh . caina angger tiis , geus dialirkeun nepi ka sajam . [A] [O] [S]',
 'aya deposit saratus rébu . check in gancang . [A] [O] [S]',
 'anduk can aya kénéh . [A] [O] [S]',
 'euweuh fasilitas akomodasi ka bandara , tempatna jauh ti jalan gedé . [A] [O] [S]',
 '2 . solokan cai kamar mandi remen mampet , kuring mandi nepi ka banjir ngocor kaluar panto cai na ! [A] [O] [S]',
 'harga kahontal jeung deukeut ka pusat kota bandung . [A] [O] [S]',
 'cai di wastafelna teu kaluar . [A] [O] [S]',
 'spréina kotor . [A] [O] [S]',
 'kamar nu didapatkeun téh teu pati beresih . [A] [O] [S]',
 'émang sarapan mah euweuh . ieu téh sigana urut kos-kosan , jeung geus jadi panginepan murah wungkul . [A] [O] [S]',
 'hotélna teu genah . [A] [O] [S]',
 'lampu kamar téh remeng-remeng teuing . [A] [O] [S]',
 'palayanan sakabéhna alus . [A] [O] [S]',
 'ieu tempatna alus . [A] [O] [S]',
 'lokasina mah , harga murah pisan . [A] [O] [S]',
 'hanjakalna cai panasna pareum . [A] [O] [S]',
 'tuluykeun servis nu alus ieu . [A] [O] [S]',
 'euweuh papan plang pituduh ka hotél ieu ! [A] [O] [S]',
 'hanjakal pisan pas datang ieu , teu meunang kamar nu standar airy room . [A] [O] [S]',
 'kaayaan rohanganana cukup alus , tapi aya sababaraha komponén di jero kamar saré jeung kamar mandi nu butuh dibenerkeun kulantaran ruksak . [A] [O] [S]',
 'bakal jadi tempat pavorit ku harga nu kahontal . ngan rék méré saran ka airy . harga di aplikasi téh kamahalan batan mayar langsung di tempat . bédana téh teu tanggung-tanggung , saratus rébu leuwih . tulungan atuh harga mun via aplikasi leuwih murah , ngarah sumanget maké airy . [A] [O] [S]',
 'euweuhna tempat parkir mobil kuduna mah diinfokeun dina profil hotél . éta téh bakal ngabantu pisan . [A] [O] [S]',
 'palayananana alus . [A] [O] [S]',
 'sarapanna kurang loba pilihan . [A] [O] [S]',
 'resepsionisna geulis . [A] [O] [S]',
 'kamar mandi kagénang . [A] [O] [S]',
 'palayanan alus . ngan saluran cai di wc kudu dibenerkeun . [A] [O] [S]',
 'sacara umum mah ngeunah . [A] [O] [S]',
 'palayanan nu kacida nguciwakeunana . [A] [O] [S]',
 'solusi hotél méwah harga mirah . [A] [O] [S]',
 'euweuh cai mineral di kamar . [A] [O] [S]',
 'tempatna mah ngeunah . [A] [O] [S]',
 'hanjakal euweuh sarapanna . hihihi . [A] [O] [S]',
 'suasana haneut . pertahankeun ciri has orientana nya . [A] [O] [S]',
 'kamar alus . [A] [O] [S]',
 'fasilitas kamar mandi perlu diremajakeun deui . [A] [O] [S]',
 'cai di kamar mandi mindeng pareum . [A] [O] [S]',
 'tempat ngéndong nu merenah . [A] [O] [S]',
 'kamarna leutik teuing . nepi ka euweuh rohangan keur solat di kamar . [A] [O] [S]',
 'tempatna ngeunah , enya sanajan rada asup gang leutik , tapi mobil mah angger bisa asup . deukeut ogé jeung malioboro . paling henteu mun urang ka jogja deui , sigana mah rék ngéndong di dieu deui . [A] [O] [S]',
 'palayanana téh teu nyenangkeun , ngan ditanya cai panas wungkul gé geus ngarengut beungeutna , jeung kawas kapaksa ngabantuanana . [A] [O] [S]',
 'kamar téh teu kawas biasana atawa standar airy , lantaran euweuh hiasan di tempat saré jeung snack . anduk ogé opat kali ditélépon kakara dianterkeun . [A] [O] [S]',
 'kamar mandi kurang beresih . [A] [O] [S]',
 'lemari nu disadiakeun lumayan gedé . [A] [O] [S]',
 'puas pisan ku fasilitas nu aya . [A] [O] [S]',
 'kanyamanan tempat saré téh kurang genah . [A] [O] [S]',
 'palayananana alus . nuhun . [A] [O] [S]',
 'desain rohangan lobi jero teuing . lamun bisa mah , sekat témbokna dibuka sangkan katempo pamandangan di luar . [A] [O] [S]',
 'kamari isuk-isuk caina kotor , teu bisa mandi , padahal rék aya acara . cenah mah aya perbaikan . meureun saran perbaikanana mah dilakukeunana pas jalma teu butuh cai , nuhun . [A] [O] [S]',
 'kulawarga kuring resepeun pisan ngéndong di dieu . betah pisan . [A] [O] [S]',
 'sarapan téh kurang . [A] [O] [S]',
 'urang biasa ngéndong di airy , tapi ayeuna mah resepsionis hotélna teu ramah . [A] [O] [S]',
 'per-na mah geus alus , ngan wafi mah can nepi ka kamar . tambahkeun menu keur dahareun di kantinna . [A] [O] [S]',
 'kualitas wifina goréng pisan , malah kadang-kadang sok paéh sababaraha kali . urang ngéndong di dieu , tapi kualitas wifina angger wé kitu , malah beuki parah . tulung diperhatikeun . [A] [O] [S]',
 'kamar jarang diberesihan . [A] [O] [S]',
 'kamar téh nyaman pisan . [A] [O] [S]',
 'kamarna teu rapih . tapi pikeun bufger mah cekapan . [A] [O] [S]',
 'lokasi stratégis ka kota tua , kari leumpang . [A] [O] [S]',
 'sarapan isukna standar . [A] [O] [S]',
 'listrikna mindeng pareum hurung . [A] [O] [S]',
 'hotélna nyaman pisan . [A] [O] [S]',
 'kabéhna alus pisan . [A] [O] [S]',
 'caina bocor . panto kudu dikonci . [A] [O] [S]',
 'pas rék check in téh kuring kudu ngadagoan ampir sajam . di kamar , ac kuring teu tiis . pas di jero kamar , ujug-ujug kamar kuring rék dibuka ti luar ku pagawé hotél , tétéla téh double booking , salahna ti hotél . [A] [O] [S]',
 'kungsi aya masalah pas rék checkin , alesanna kamar geus pinuh , tapi geus dibereskeun ku pihak hotél . [A] [O] [S]',
 'lokasi stratégis , deukeut alun-alun malang . loba tempat jajan . [A] [O] [S]',
 'dipindahkeun ka hotél séjén alatan sistimna éror nepi ka aya over booking . tapi fasilitas hotél gaganti téh di handapeun hotél nu dipesén ti mimiti . mugia ulah kajadian deui . [A] [O] [S]',
 'wc-na bocor , matak ubin baseuh ka mana-mana . [A] [O] [S]',
 'koleksi interiorna asli keren pisan , nepi ka bisa dipoto keur di ig . pasti balik deui mun ka jogja . nuhun nya airy babaranji . [A] [O] [S]',
 'alus pisan ti sagala rupa hal . [A] [O] [S]',
 'résepsionis friendly pisan ka konsuménna . [A] [O] [S]',
 'tempatna genah , deukeut masjid , kari leumpang mun rék solat . tuluy nu pasti , 7 garansi kapuasan kacumponan . [A] [O] [S]',
 'kabersihan kamar ( lanté ) perlu ditingkatkeun deui . [A] [O] [S]',
 'kamar kotor . [A] [O] [S]',
 'lokasi alus , deukeut stasion mangga besar . [A] [O] [S]',
 'tempat ngeunah pisan keur reureuh . deukeut ka bandara , bisa mesen antar . [A] [O] [S]',
 'hotélna alus da masih anyar kénéh , can bau apek . resep pisan mondok di dieu mah . [A] [O] [S]',
 'tempatna genah , lingkungan sabudeureunana ogé héjo , deukeut ka candi sambisari . [A] [O] [S]',
 'anduk jeung cai nginum dina botol mah kudu dipénta heula kakara disadiakeun . rasa kadaharan mah standar . [A] [O] [S]',
 'palayanan alus salila 24 jam . [A] [O] [S]',
 'kasurna teuas : ( . [A] [O] [S]',
 'nu ngajaga téh kurang someah . [A] [O] [S]',
 'ngeunah murah , jeung alus . [A] [O] [S]',
 'euweuh sandal di kamar . tapi pelayanan jeung roomy mah lumayan wéh ok lah . [A] [O] [S]',
 'kotor , euweuh cai , jorok , teu genah . [A] [O] [S]',
 'palayanan kacida hadéna . kabersihan kajaga . [A] [O] [S]',
 'kamar mandi téh panas , euweuh ékzosfan , ac tiisna teu rata , jeung jandéla katempo ti luar sabab euweuh gordén . [A] [O] [S]',
 'palayanan geus alus , tempat ogé alus . bakal leuwih alus deui mun tempat keur ngecas hp ditambah . nuhun . [A] [O] [S]',
 'murah pisan jeung ngeunah . [A] [O] [S]',
 'kamarna lega jeung ac-na ducting , keren pisan komo deui meunang diskon 50% ti airy . ngan kakuranganna téh konci panto nu hésé pisan , kawas geus ruksak jeung modél baheula . sarapan ngeunah , tapi sababaraha masakan téh kawas geus dipanaskeun sababaraha kali . tv-na indovision , pikeun harga diskon mah , kamar ieu téh alus pisan . [A] [O] [S]',
 'kamar téh matak kuciwa pisan . panto lomari téh ruksak . keran cai di toilét kamar mandi téh teu jalan bener . [A] [O] [S]',
 'wareg pisan ngabantu . [A] [O] [S]',
 'resep kamar teu bau roko . aya cai nginum panas di luar . lokasi strategis . tapi teu meunang snack kawas airy room di tempat séjén . [A] [O] [S]',
 'kamar rapih jeung lega . bersih . nyaman . ngan wcna ngeuyeumbeu jeung lap suku euweuh . [A] [O] [S]',
 'pelayananna mah lumayan nyugemakeun . beresih jeung genah . sarapanna gé ngeunah . [A] [O] [S]',
 'mun bisa mah liftna atuh hé , nu séjénna mah panghadéna ! [A] [O] [S]',
 'alus , tapi teu luyu jeung nu dipiharep . kamarna ukur hiji ranjang , tungtungna mah nambah . [A] [O] [S]',
 'pelayanan alus , kaayaan kamar ogé alus , suasana hotél alus . ngan waé fasilitas di kamar masih kurang . shower euweuh cai panas jeung tiis . sésana mah alus . harga ogé kahontal . [A] [O] [S]',
 'kamarna beresih , panjagana bageur . min hiji mun meunang kamar di luhur juru beulah katuhu , ac-na teu tiis . tiisna téh mun peuting wungkul . sésana mah sugema , nuhun . [A] [O] [S]',
 'hotélna alus , beresih , nyaman . [A] [O] [S]',
 'sakabéh fasilitasna jalan jeung alus , stafna someah jeung someah . [A] [O] [S]',
 'biasa wéh , heureut , teu jiga nu dipikiran ku kuring . lumayan lah mun keur istirahat mah teu gandéng . [A] [O] [S]',
 'fasilitas kotor , ac teu tiis , panto kamar mandi teu bisa ditutup , kulkas teu bisa dipaké , sépré . [A] [O] [S]',
 'deposit mah lumayan ngabeungbeuratan . [A] [O] [S]',
 'kamar mandina rada kotor , kadaharanana ogé rada ngécéwakeun . sarapan isuk kakara jam 8 tapi kabéh geus béak . [A] [O] [S]',
 'kamar beresih , ac tiis , cai panas keur pancuran lancar . [A] [O] [S]',
 'kamarna mah heureut pisan , rék ka kamar mandi gé leumpangna kudu nyangsaya , sabab posisi pantona pas pisan gigireun ranjang . [A] [O] [S]',
 'kamarna beresih , deukeut pisan ka bandara . [A] [O] [S]',
 'sacara umum mah oké kabéh , ngan taman hareupna lamun bisa mah jukutna dirapihkeun , sangkan katingalna éndah teu singup . [A] [O] [S]',
 'ménu sarapan kurang lengkep . [A] [O] [S]',
 'kamar téh kurang beresih , komo kamar mandina . [A] [O] [S]',
 'water heaterna teu jalan . [A] [O] [S]',
 'biasa wé . teu cocog jeung gambarna . rohangan poék , caangna kurang . [A] [O] [S]',
 'lokasi nu alami , ayana di lamping pasir . matak nimbulkeun suasana alam nu kacida éndahna . [A] [O] [S]',
 'kamar téh beresih , seungit . jadi mayar 80000 sabab maké voucer 100000 . [A] [O] [S]',
 'lantaran wangunanana beresih jeung tempat parkirna cukup alus , ngan hanjakalna mah teu sadia breakfast . [A] [O] [S]',
 'palayananana ramah pisan euy . kamar alus , cocog jeung harga , ac tiis , wifi tarik , kamar mandi di jero . rékoménded pisan ! [A] [O] [S]',
 'lampu kamar téh kurang caang . [A] [O] [S]',
 'kamar beresih , suasana merenah jeung tenang , cocok pisan keur liburan jeung kulawarga . [A] [O] [S]',
 'kuciwa euweuh cai panas atawa hot shower nu geus dijanjikeun ku airyrooms , teu bisa mandi peuting . euweuh béja atawa panyuhunkeun hampura ti saméméhna , boh ti résépsionis boh ti housekeeping yén water heater keur ruksak . skor goréng pisan . kuciwa . [A] [O] [S]',
 'pokona mah nyugemakeun . [A] [O] [S]',
 'kuring mesen 2 kamar . kamar nu kahiji mah euweuh masalah , tapi pas kamar nu kadua mah hawana bau pengap . sanggeus ditalungtik , tétéla aya bocor dina instalasi ac nu nyieun témbok kamar jadi lembab jeung bau teu ngeunah . ahirna kuring ménta ganti kamar , jeung diidinan gé , tapi sababaraha fasilitas nu dibéré ku airy teu dibikeun ( meureun pédah panik jeung dadakan kuring maksa hayang pindah kamar atawa ménta duit balik wéh ) . [A] [O] [S]',
 'palayananana mah nyugemakeun . ngan bantal airy-na kotor , siga nu teu dikumbah . jeung tempat nyimpen bantal biru airy-na gé kotor . [A] [O] [S]',
 'résepsionis kurang ramah . [A] [O] [S]',
 'beresih , genah , jeung stafna bageur . [A] [O] [S]',
 'sajalanana mah kamar téh alus , ngan kurang profésional . geus ngomong rék sarapan nasi goreng , ménta dianterkeun jam 8 . 30 , eh datangna jam 9 gé , éta ogé kudu ditélépon heula . nu datang téh malah mie muah jeung endog . hm . [A] [O] [S]',
 'ari ngeunaan kanyamanan mah rada kurang sabab ac-na kurang tiis , jeung tulung kamar mandina unggal kamar rajin dibersihan sabab kamari kuring nginep , aya jiga cacing hideung di handap ( kamar 202 ) . palayananana mah alus pisan , masna bageur , di dieu disadiakeun anduk . [A] [O] [S]',
 'ac-na teu tiis jeung panto kamar mandi bocor , tapi sacara umum mah alus , utamana dahareunana . deukeut ti tempat dahar di luar hotél jeung supermarket . [A] [O] [S]',
 'wifi-na gancang , jeung palayananana someah . [A] [O] [S]',
 'loba reungit , duit deposit leuwih mahal tibatan harga kamarna , ktp gé ditahan salila ngéndong . pisan-pisan teu nyarankeun pikeun ngéndong di dieu . [A] [O] [S]',
 'kamar alus . ngan wifina goréng . terus euweuh tempat runtah deui . jeung nu ngajaga jalmana kurang loyal . sarua palayanan ka tamu kurang alus , teuing cuek . [A] [O] [S]',
 'kamar teu didésain siga nu di gambar , sprei jeung simbut kusam , karahaan , teu pantes ditempo . snack jeung parabot mandi euweuh pas tamu datang , resepsionisna teu ramah . [A] [O] [S]',
 'hotélna kurang caang , kawas horor jeung angker . tapi palayananna nyugemakeun . [A] [O] [S]',
 'sajalanana mah pas kuring asup jeung ningali kaayaanana , kuring ngarasa cukup sugema lamun disaluyukeun jeung hargana . nu matak kuring kuciwa téh nyaéta , nu jaga euweuh di tempat ( keur indit ) jeung parangkat mandi ogé teu disadiakeun , utamana anduk . kuring meunang urut batur maké . meureun kamar nu ku kuring dipaké can kaburu diberesihan ku nu jagana saméméh manéhna indit . nuhun . [A] [O] [S]',
 'kamar nyaman , sarapanna cukup ngeunah , tenang . [A] [O] [S]',
 'ngéndong di dieu mah betah pisan . [A] [O] [S]',
 'kudu leuwih beresih deui , sabab kaberesihanana rada kurang . [A] [O] [S]',
 'harga kahontal , tempatna stratégi . pas meunang kamar , bau haseup roko , jeung panto kamar mandi ruksak . [A] [O] [S]',
 'matak kuciwa pisan . [A] [O] [S]',
 'lumayan . tapi kabersihanana mah masih kurang . simbut jeung bantalna konéng . muga bisa ditingkatkeun deui kabersihanana . [A] [O] [S]',
 'alus . tapi euweuh sinyal di jero kamar . wifi gé teu nepi . tapi genah . palayanan lumayan . [A] [O] [S]',
 'genah , jeung stafna bageur-bageur . nuhun . [A] [O] [S]',
 '2 . sandal hotél euweuh . [A] [O] [S]',
 'kabersihan kurang . kamar mandi di kamar ogé , keran westaferna teu hurung . mudah-mudahan fasilitasna dioméan deui . nuhun . [A] [O] [S]',
 'tempatna beresih , nyaman , palayananana ogé alus . [A] [O] [S]',
 'wangunan anyar nu lega jeung beresih . [A] [O] [S]',
 'teu luyu jeung paménta , ménta ranjang nu gedé , eh teu dibéré . [A] [O] [S]',
 'kamar lumayan beresih jeung ac tiis . ngan di bagian panto kamar mandi rada lecet , jadi hésé dibuka . hiji deui , témbokna kudu dicét deui sabab aya noda nu napel . tapi sacara sakabéhna mah cukup nyaman jeung lokasi cukup jempling . [A] [O] [S]',
 'mimitina mah wifina alus , poé kadua wifina paéh . sakabéhna mah oke . [A] [O] [S]',
 'kamar beresih , fasilitas lengkep , sarapan ngeunah . [A] [O] [S]',
 'hadé waé , komo deui kuring dipindahkeun ka kamar panghadéna maranéhna sanggeus aya kajadian mistis . [A] [O] [S]',
 'tempatna genah , jeung aksésna gampang kapanggih . jelemana someah . [A] [O] [S]',
 'sababaraha laci dina méja tipi jeung méja rias loba buukan . meureun buuk tamu nu saméméhna . sakabéhna mah rapih jeung beresih . meunang gratis snacks , gratis cai ngocor , jeung toiletris . tapi hanjakalna , nu ngajagana kurang informatif . misalna , aya dapur umum tapi teu aya inpormasi leuwih jéntré naha bisa dipaké ku tamu nu ngéndong atawa henteu . [A] [O] [S]',
 'hotélna alus , ngan wifina leuleus . panto kamar mandi gé aya nu ruksak . sabun jeung sikat huntu gé kadang aya kadang euweuh . [A] [O] [S]',
 'sarapanna ngeunah . aya réstoran di lokasi hotélna . [A] [O] [S]',
 'kamar kotor , pas datang di kamarna aya noda coklat , terus di bantalna aya noda hideung . kotor pisan kawas teu dikumbah , ngan dibalikkeun wungkul . pas rék check-out , dituduh ngotoran simbutna , padahal mah ti mimiti datang gé geus aya . jeung depositna rék dicokot . jadi , lamun maranéh datang aya noda atawa kokotor di kamar , langsung waé komplain , sabab engké maranéh dituduh ngotoran kamar éta jeung depositna bakal dicokot . check-in kakara bisa jam 2 . sarapan ngan nasi goreng maké endog . kamar mandi bau jeung solokan cai di handapna kotor pisan kawas aya buuk-buukna . moal deui ngéndong di hotél éta . [A] [O] [S]',
 'euweuh aqua . euweuh ogé alat mandi . [A] [O] [S]',
 'alus . kamarna ngeunah jeung beresih . [A] [O] [S]',
 'kamar beresih jeung genah . lokasi strategis , rék ka mana waé gampang jeung babari . [A] [O] [S]',
 'beresih , rapéh , aman , someah , jeung recommended pisan . [A] [O] [S]',
 'puas pisan . méwah pisan . [A] [O] [S]',
 'fasilitasna mah alus , oke . tapi sepréna kotor jeung ateul . lumayan lah , direkoméndasikeun , ngan nya éta sepréna . tamu ganti téh , sepréna gé kudu dikumbah atuh . [A] [O] [S]',
 'kamar beresih . ac kurang tiis . [A] [O] [S]',
 'harga mirah , fasilitas ngeunah , palayanan lumayan . [A] [O] [S]',
 'kamar , fasilitas nyukupan luyu jeung harga . [A] [O] [S]',
 'euweuh jaringan di kamar / wifi , telepon gé ruksak , jadi teu bisa pesen dahareun ka handap . tapi resepsionisna mah oke , gancang jeung someah . [A] [O] [S]',
 'lokasi strategis , palayananna ramah , kamar diberesihan unggal poé ( sakuduna mah aya persetujuan heula ) , snack sok dieusian deui unggal poéna . [A] [O] [S]',
 'lumayan jang ukuran backpacker . [A] [O] [S]',
 'tempatna ngeunah tur beresih . [A] [O] [S]',
 'loba reungit jeung cucunguk . lanténa ogé kotor pisan ! [A] [O] [S]',
 'palayananana lumayan bageur jeung gancang résponna . [A] [O] [S]',
 'lokasi babari dijangkau . loba dahareun murah nu ngeunah di sabudeureunana . [A] [O] [S]',
 'kamarna beresih , nyaman , kasurna badag , wifina gancang , alhamdulillah bisa late check-in subuh-subuh kénéh . [A] [O] [S]',
 'kamarna can dispreian . biasana unggal kuring check in maké airy rooms , kamar téh geus dispreian ti heula ( atribut airy ) siga bantal , dahareun , alat mandi . éta can disadiakeun ku pihak hotél . [A] [O] [S]',
 'tempatna beresih . palayananana someah pisan . tempatna strategis . pokona mah kuring resep . [A] [O] [S]',
 'palayananana mantep , tapi di kamar nu ku kuring dicicingan cai panasna teu jalan . punten dioméan . nuhun . [A] [O] [S]',
 'sarapan ngeunah , lokasi strategis . ari pancuran mah , méh debit cai na dileuwihgedékeun . [A] [O] [S]',
 'tempatna beresih jeung genah . stafna bageur . [A] [O] [S]',
 'alus , beresih . pokona mah puas , tapi aya saingan nu hargana leuwih miring . hehe . [A] [O] [S]',
 'teu nyugemakeun pisan ! kamar pinuh reungit , ménta obat reungit sémprot waé euweuh . [A] [O] [S]',
 'wifi-na teu hurung . [A] [O] [S]',
 'lokasina oké . deukeut jeung pusat kota . [A] [O] [S]',
 'ménu sarapanna loba jeung ngeunah , tapi hanjakalna kuring meunang kamar 222 gedong heubeul . sarang reungit , loba pisan reungit di kamar kulantaran asupna ti handapeun panto . [A] [O] [S]',
 'tempat runtah kamar mandi téh tulungan atuh dioméan atawa diganti nu anyar . kasurna ogé ceuk kuring mah geus teu pantes dipaké . [A] [O] [S]',
 'kamarna leutik pisan . [A] [O] [S]',
 'murah pisan , aya kolam renangna . [A] [O] [S]',

In [41]:
# df_dataset = df_dataset.loc[df_dataset['sentence_id'] >= 1006, :].copy()

In [42]:
# df_dataset.reset_index(drop=True, inplace=True)

In [43]:
df_dataset

,sentence_id,instance_id,task_elements,input,target,element_order
0,2500,12500,aos,pintu geser kurang rapat . [A] [O] [S],[A] pintu geser [O] kurang rapat [S] negative,aos
1,2501,12505,aos,pelayanan lumayan baik . [A] [O] [S],[A] pelayanan [O] lumayan baik [S] positive,aos
2,2502,12510,aos,air bersih untuk mck tidak ada . [A] [O] [S],[A] air bersih [O] tidak ada [S] negative,aos
3,2503,12515,aos,ternyata ada makanan ringan gratis . [A] [O] [S],[A] makanan ringan gratis [O] ada [S] positive,aos
4,2504,12520,aos,wifi buruk suka down . [A] [O] [S],[A] wifi [O] buruk [S] negative,aos
...,...,...,...,...,...,...
995,3495,17475,aos,"strategis , dekat jalan raya . [A] [O] [S]",[A] null [O] strategis [S] positive [SSEP] [A]...,aos
996,3496,17480,aos,( - ) tempatnya kurang bersih . tipetipe pengi...,[A] tempatnya [O] kurang bersih [S] negative [...,aos
997,3497,17485,aos,"mantapp , pelayanan prima . [A] [O] [S]",[A] null [O] mantapp [S] positive [SSEP] [A] p...,aos
998,3498,17490,aos,"hotel lumayan nyaman sih , tetapi dikamar saya...",[A] hotel [O] lumayan nyaman [S] positive [SSE...,aos
999,3499,17495,aos,"tidak ada yang bertulisan airy di room 107 , r...",[A] remote tv [O] tidak bisa [S] negative [SSE...,aos

In [44]:
mismatch_indexes

['2709',
 '3366',
 '3028',
 '3155',
 '3210',
 '3476',
 '3032',
 '2646',
 '2524',
 '2702',
 '2688',
 '3246',
 '3190',
 '3496',
 '2778',
 '3117',
 '2881',
 '2572',
 '2632',
 '2790',
 '2932',
 '2838']

In [45]:
index_check = df_dataset['sentence_id'].to_list()
df_dataset[f'input_{lang_target}'] = list(input_eng.values())
df_dataset[f'target_{lang_target}'] = list(target_eng.values())
df_dataset['aspect_or_opinion_not_in_input'] = [str(idx) in mismatch_indexes for idx in index_check]
df_dataset['mismatch_notes'] = [mismatch_notes.get(str(idx), []) for idx in index_check]
df_dataset['mismatch_notes_format'] = df_dataset['mismatch_notes'].apply(lambda x: '\n'.join(x))

In [46]:
df_dataset['target_format'] = df_dataset['target'].apply(lambda x: '\n'.join(x.split(' [SSEP] ')))
df_dataset[f'target_format_{lang_target}'] = df_dataset[f'target_{lang_target}'].apply(lambda x: '\n'.join(x.split(' [SSEP] ')))

In [47]:
df_dataset

,sentence_id,instance_id,task_elements,input,target,element_order,input_sunda,target_sunda,aspect_or_opinion_not_in_input,mismatch_notes,mismatch_notes_format,target_format,target_format_sunda
0,2500,12500,aos,pintu geser kurang rapat . [A] [O] [S],[A] pintu geser [O] kurang rapat [S] negative,aos,panto geser kurang rapet . [A] [O] [S],[A] panto geser [O] kurang rapet [S] negative,False,[],,[A] pintu geser [O] kurang rapat [S] negative,[A] panto geser [O] kurang rapet [S] negative
1,2501,12505,aos,pelayanan lumayan baik . [A] [O] [S],[A] pelayanan [O] lumayan baik [S] positive,aos,palayananana lumayan alus . [A] [O] [S],[A] palayanan [O] lumayan alus [S] positive,False,[],,[A] pelayanan [O] lumayan baik [S] positive,[A] palayanan [O] lumayan alus [S] positive
2,2502,12510,aos,air bersih untuk mck tidak ada . [A] [O] [S],[A] air bersih [O] tidak ada [S] negative,aos,cai bersih keur mck euweuh . [A] [O] [S],[A] cai bersih [O] euweuh [S] negative,False,[],,[A] air bersih [O] tidak ada [S] negative,[A] cai bersih [O] euweuh [S] negative
3,2503,12515,aos,ternyata ada makanan ringan gratis . [A] [O] [S],[A] makanan ringan gratis [O] ada [S] positive,aos,geuning aya cemilan haratis . [A] [O] [S],[A] cemilan haratis [O] aya [S] positive,False,[],,[A] makanan ringan gratis [O] ada [S] positive,[A] cemilan haratis [O] aya [S] positive
4,2504,12520,aos,wifi buruk suka down . [A] [O] [S],[A] wifi [O] buruk [S] negative,aos,"wifi goréng , mindeng down . [A] [O] [S]",[A] wifi [O] goréng [S] negative,False,[],,[A] wifi [O] buruk [S] negative,[A] wifi [O] goréng [S] negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3495,17475,aos,"strategis , dekat jalan raya . [A] [O] [S]",[A] null [O] strategis [S] positive [SSEP] [A]...,aos,"stratégis , deukeut jalan raya . [A] [O] [S]",[A] null [O] stratégis [S] positive [SSEP] [A]...,False,[],,[A] null [O] strategis [S] positive\n[A] null ...,[A] null [O] stratégis [S] positive\n[A] null ...
996,3496,17480,aos,( - ) tempatnya kurang bersih . tipetipe pengi...,[A] tempatnya [O] kurang bersih [S] negative [...,aos,( - ) tempatna kurang beresih . tipe-tipe pang...,[A] tempatna [O] kurang beresih [S] negative [...,True,[aspect_term 'penginepan' not found],aspect_term 'penginepan' not found,[A] tempatnya [O] kurang bersih [S] negative\n...,[A] tempatna [O] kurang beresih [S] negative\n...
997,3497,17485,aos,"mantapp , pelayanan prima . [A] [O] [S]",[A] null [O] mantapp [S] positive [SSEP] [A] p...,aos,"mantep pisan , palayananana gé alus pisan . [A...",[A] null [O] mantep pisan [S] positive [SSEP] ...,False,[],,[A] null [O] mantapp [S] positive\n[A] pelayan...,[A] null [O] mantep pisan [S] positive\n[A] pa...
998,3498,17490,aos,"hotel lumayan nyaman sih , tetapi dikamar saya...",[A] hotel [O] lumayan nyaman [S] positive [SSE...,aos,"hotél lumayan genah mah , tapi di kamar kuring...",[A] hotél [O] lumayan genah [S] positive [SSEP...,False,[],,[A] hotel [O] lumayan nyaman [S] positive\n[A]...,[A] hotél [O] lumayan genah [S] positive\n[A] ...
999,3499,17495,aos,"tidak ada yang bertulisan airy di room 107 , r...",[A] remote tv [O] tidak bisa [S] negative [SSE...,aos,"euweuh tulisan ' airy ' di kamar 107 , remot t...",[A] remot tv [O] teu bisa dipaké [S] negative ...,False,[],,[A] remote tv [O] tidak bisa [S] negative\n[A]...,[A] remot tv [O] teu bisa dipaké [S] negative\...

In [48]:
df_dataset[['sentence_id', 'input', f'input_{lang_target}', 'target_format', f'target_format_{lang_target}', 'aspect_or_opinion_not_in_input', 'mismatch_notes_format']].rename({'target_format': 'target', f'target_format_{lang_target}': f'target_{lang_target}', 'mismatch_notes_format': 'mismatch_notes'}).to_csv(f'temp/translation_output/{lang_target}/{dataset_folder}/translated_dataset_{lang}_{split}.csv', index=False)

### Check mismatches after annotation

In [33]:
def get_google_sheet(sheet_id: str, sheet_gid: str) -> pd.DataFrame:
	"""
	Downloads a specific sheet from a Google Sheet into a pandas DataFrame.

	Args:
		sheet_id: The ID of the Google Sheet.
		sheet_gid: The GID of the specific sheet to download.

	Returns:
		A pandas DataFrame containing the data from the specified sheet.
	"""
	url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={sheet_gid}'
	df = pd.read_csv(url)
	return df
google_sheet_id = '1_ZEFErp75wDNkXIvYflxv1d4nAQZrMlg_Vin4cgpyyY'  # Replace with your actual Google Sheet ID
gid_eng_train = '1363651964'  # Replace with the actual GID for the English sheet
gid_eng_test = '1183495517'
gid_sunda_test = '1775717233'
split = 'test'
lang_target = 'sunda'
try:
	df_translated_correction = get_google_sheet(google_sheet_id, gid_sunda_test)
	print("Successfully loaded data from the specific sheet:")
except Exception as e:
	print(f"An error occurred: {e}")
	print("Please ensure the Google Sheet is shared correctly and the IDs are correct.")

Successfully loaded data from the specific sheet:

In [34]:
df_translated_correction

,sentence_id,input,input_sunda,target_format,input_sunda_corrected,target_format_sunda,target_format_sunda_corrected,aspect_or_opinion_not_in_input,mismatch_notes_format
0,3500,pelayanan nya sangat ramah . [A] [O] [S],layananna someah pisan . [A] [O] [S],[A] pelayanan nya [O] sangat ramah [S] positive,palayananna someah pisan . [A] [O] [S],[A] layananna [O] someah pisan [S] positive,[A] palayananna [O] someah pisan [S] positive,FALSE,NaN
1,3501,sayang wifi tidak bagus harus keluar kamar . [...,"hanjakal wifi téh teu alus , kudu kaluar kamar...",[A] wifi [O] tidak bagus harus keluar kamar [S...,NaN,"[A] wifi [O] teu alus , kudu kaluar kamar [S] ...",NaN,FALSE,NaN
2,3502,"tulisannya twin bed , tetapi yang ada kamarnya...","tulisanana twin bed , tapi nu aya mah kamarna ...",[A] kamarnya [O] beda [S] negative,"tulisanna mah dua ranjang , ngan nu aya kamarn...",[A] kamarna [O] béda [S] negative,NaN,FALSE,NaN
3,3503,"over all baik , hanya sja akan lebih memuaskan...","sakabéhna mah alus , ngan wé bakal leuwih nyug...",[A] over all [O] baik [S] positive\n[A] air ho...,"sakabéhna mah alus , ngan bakal leuwih nyugema...",[A] sakabéhna [O] alus [S] positive\n[A] cai p...,NaN,FALSE,NaN
4,3504,fasilatas sesuia . [A] [O] [S],fasilitasna cocog . [A] [O] [S],[A] fasilitas [O] sesuai [S] positive,fasilitasna luyu . [A] [O] [S],[A] fasilitas [O] cocog [S] positive,[A] fasilitasna [O] luyu [S] positive,FALSE,NaN
...,...,...,...,...,...,...,...,...,...
995,4495,"lumayan , harga murah banged . [A] [O] [S]","lumayan , harga mirah pisan . [A] [O] [S]",[A] harga [O] murah banget [S] positive\n[A] n...,NaN,[A] harga [O] mirah pisan [S] positive\n[A] nu...,NaN,FALSE,NaN
996,4496,buat lakilaki dan perempuan yang belum menikah...,pikeun lalaki jeung awéwé anu can nikah ogé me...,[A] null [O] buat laki laki dan perempuan yang...,keur lalaki jeung awéwé anu can nikah ogé meun...,[A] null [O] pikeun lalaki jeung awéwé anu can...,[A] null [O] keur lalaki jeung awéwé anu can n...,FALSE,NaN
997,4497,"kamar sangat nyaman dan bersih , sungguh menye...","kamar téh genah pisan jeung beresih , matak pi...",[A] kamar [O] sangat nyaman [S] positive\n[A] ...,"kamar téh ngeunaheun pisan jeung beresih , mat...",[A] kamar [O] genah pisan [S] positive\n[A] ka...,[A] kamar [O] ngeunaheun pisan [S] positive\n[...,FALSE,NaN
998,4498,"kamarnya luas , kasurnya empuk , kamar mandiny...","kamarna lega , kasurna empuk , kamar mandina o...",[A] kamarnya [O] luas [S] positive\n[A] kasurn...,"kamarna lega , kasurna empuk , kamar mandina o...",[A] kamarna [O] lega [S] positive\n[A] kasurna...,[A] kamarna [O] lega [S] positive\n[A] kasurna...,FALSE,NaN
999,4499,"kamar tidak sesuai , tempat parkir kurang nyam...","kamar teu cocog , tempat parkir kurang ngeunah...",[A] kamar [O] tidak sesuai [S] negative\n[A] t...,"kamar teu luyu , tempat parkir kurang ngeunahe...",[A] kamar [O] teu cocog [S] negative\n[A] temp...,[A] kamar [O] teu luyu [S] negative\n[A] tempa...,FALSE,NaN

In [35]:
df_translated_correction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   sentence_id                     1000 non-null   int64
 1   input                           1000 non-null   object
 2   input_sunda                     1000 non-null   object
 3   target_format                   1000 non-null   object
 4   input_sunda_corrected           767 non-null    object
 5   target_format_sunda             1000 non-null   object
 6   target_format_sunda_corrected   697 non-null    object
 7   aspect_or_opinion_not_in_input  1000 non-null   object
 8   mismatch_notes_format           34 non-null     object
dtypes: int64(1), object(8)
memory usage: 70.4+ KB

In [36]:
df_translated_correction[f'target_format_{lang_target}'].fillna('[A] [O] [S]', inplace=True)

/tmp/ipykernel_3224141/3226597203.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_translated_correction[f'target_format_{lang_target}'].fillna('[A] [O] [S]', inplace=True)

In [37]:
df_translated_correction[f'input_{lang_target}_corrected'] = df_translated_correction[f'input_{lang_target}_corrected'].apply(lambda x: x.replace('’', "'") if isinstance(x, str) else x)
df_translated_correction[f'target_format_{lang_target}_corrected'] = df_translated_correction[f'target_format_{lang_target}_corrected'].apply(lambda x: x.replace('’', "'") if isinstance(x, str) else x)
df_translated_correction[f'input_{lang_target}'] = df_translated_correction[f'input_{lang_target}'].apply(lambda x: x.replace('’', "'"))
df_translated_correction[f'target_format_{lang_target}'] = df_translated_correction[f'target_format_{lang_target}'].apply(lambda x: x.replace('’', "'"))

In [38]:
list(df_translated_correction.loc[df_translated_correction['sentence_id'] == 433, f'input_{lang_target}_corrected'])

[]

In [39]:
# Strip strings of all _corrected columns
df_translated_correction[f'input_{lang_target}_corrected'] = df_translated_correction[f'input_{lang_target}_corrected'].apply(lambda x: x.strip() if isinstance(x, str) else x)
df_translated_correction[f'target_format_{lang_target}_corrected'] = df_translated_correction[f'target_format_{lang_target}_corrected'].apply(lambda x: x.strip() if isinstance(x, str) else x)

# Set to pandas nan if empty string
df_translated_correction[f'input_{lang_target}_corrected'] = df_translated_correction[f'input_{lang_target}_corrected'].apply(lambda x: x if x != '' else np.nan)
df_translated_correction[f'target_format_{lang_target}_corrected'] = df_translated_correction[f'target_format_{lang_target}_corrected'].apply(lambda x: x if x != '' else np.nan)

In [40]:
# Fill _corrected columns with input_eng if null
df_translated_correction[f'input_{lang_target}_corrected'] = df_translated_correction[f'input_{lang_target}_corrected'].fillna(df_translated_correction[f'input_{lang_target}'])
df_translated_correction[f'target_format_{lang_target}_corrected'] = df_translated_correction[f'target_format_{lang_target}_corrected'].fillna(df_translated_correction[f'target_format_{lang_target}'])

In [41]:
df_translated_correction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   sentence_id                     1000 non-null   int64
 1   input                           1000 non-null   object
 2   input_sunda                     1000 non-null   object
 3   target_format                   1000 non-null   object
 4   input_sunda_corrected           1000 non-null   object
 5   target_format_sunda             1000 non-null   object
 6   target_format_sunda_corrected   1000 non-null   object
 7   aspect_or_opinion_not_in_input  1000 non-null   object
 8   mismatch_notes_format           34 non-null     object
dtypes: int64(1), object(8)
memory usage: 70.4+ KB

In [42]:
def check_mismatches_triplet_format_sent_id(outputs_text):
	mismatch_indexes = []
	mismatch_notes = {}
	for key, instance in outputs_text.items():
		translated_text = add_space_around_punctuation(instance['translated_text'].lower()).strip()
		mismatched = False
		for triplet in instance['translated_triplets']:
			aspect_term = add_space_around_punctuation(triplet['aspect_term'].lower()).strip()
			opinion_term = add_space_around_punctuation(triplet['opinion_term'].lower()).strip()
			if aspect_term not in translated_text and aspect_term != 'null':
				print(f"Mismatch in instance sentence_id {instance['sentence_id']} key {key}: aspect_term '{aspect_term}' not found in {translated_text}")
				mismatch_notes[key] = mismatch_notes.get(key, []) + [f"aspect_term '{aspect_term}' not found"]
				mismatched = True
			if opinion_term not in translated_text and opinion_term != 'null':
				print(f"Mismatch in instance sentence_id {instance['sentence_id']} key {key}: opinion_term '{opinion_term}' not found in {translated_text}")
				mismatch_notes[key] = mismatch_notes.get(key, []) + [f"opinion_term '{opinion_term}' not found"]
				mismatched = True
		if mismatched:
			mismatch_indexes.append(key)
	print(f"Total mismatches found: {len(mismatch_indexes)}")
	return mismatch_indexes, mismatch_notes

In [43]:
outputs_text_correction = {}
for idx, row in df_translated_correction.iterrows():
	outputs_text_correction[idx] = {
		'sentence_id': row['sentence_id'],
		'translated_text': row[f'input_{lang_target}_corrected'],
		'translated_triplets': parse_absa_string(row[f'target_format_{lang_target}_corrected'].replace('\n', ' [SSEP] '))
	}
	# Change the keys of translated_triplets from A, O, S to aspect_term, opinion_term, sentiment_polarity
	for triplet in outputs_text_correction[idx]['translated_triplets']:
		triplet['aspect_term'] = triplet.pop('A', '')
		triplet['opinion_term'] = triplet.pop('O', '')
		triplet['sentiment_polarity'] = triplet.pop('S', '')

In [44]:
len(outputs_text_correction)

1000

In [45]:
outputs_text_correction[372]

{'sentence_id': 3872,
 'translated_text': 'kamar rapih , ngeunaheun , palayanan someah . direkomendasikeun pisan atuh . ngan hanjakal pas muka hordéng jandéla , pamandanganna kurang alus . [A] [O] [S]',
 'translated_triplets': [{'aspect_term': 'kamar',
   'opinion_term': 'rapih , ngeunaheun',
   'sentiment_polarity': 'positive'},
  {'aspect_term': 'palayanan',
   'opinion_term': 'someah',
   'sentiment_polarity': 'positive'},
  {'aspect_term': 'pamandanganana',
   'opinion_term': 'kurang alus',
   'sentiment_polarity': 'negative'},
  {'aspect_term': 'null',
   'opinion_term': 'direkomendasikeun pisan',
   'sentiment_polarity': 'positive'}]}

In [46]:
mismatch_indexes, mismatch_notes = check_mismatches_triplet_format_sent_id(outputs_text_correction)

Mismatch in instance sentence_id 3514 key 14: opinion_term 'genah' not found in tempatna ngeunaheun , jauh ti karaméan lalu lintas kandaraan . [a] [o] [s]
Mismatch in instance sentence_id 3552 key 52: opinion_term 'éksélén' not found in kamar nu alus pisan . [a] [o] [s]
Mismatch in instance sentence_id 3564 key 64: aspect_term 'palayananana' not found in palayananna kurang hadé . [a] [o] [s]
Mismatch in instance sentence_id 3573 key 73: opinion_term 'kasep' not found in alus kamarna . [a] [o] [s]
Mismatch in instance sentence_id 3596 key 96: aspect_term 'sandalna' not found in sendalna euweuh . cenah wifi gratis , ngan gening teu dibéré passwordna , anéh . [a] [o] [s]
Mismatch in instance sentence_id 3602 key 102: opinion_term 'genah' not found in ku harga nu kahontal , urang geus meunang fasilitas nu ngeunaheun . [a] [o] [s]
Mismatch in instance sentence_id 3607 key 107: aspect_term 'éksteriorna' not found in hotélna kawas kurang kaurus , boh éksterior atawa interiorna . punten benerkeun deui . nuhun . [a] [o] [s]
Mismatch in instance sentence_id 3617 key 117: opinion_term 'lantai 3 euweuh lift' not found in lokasina alus pisan di tengah kota . kamar beresih , ngan kamar mandina bau buruk . dahareun mah biasa waé . staf résepsionis teu someah . aksés internét euweuh , jeung kamar di lanté 3 euweuh lift . [a] [o] [s]
Mismatch in instance sentence_id 3620 key 120: opinion_term 'ramah' not found in palayanan nu someah jeung fasilitas nu nyukupan . direkomendasikeun pisan . [a] [o] [s]
Mismatch in instance sentence_id 3625 key 125: aspect_term 'cemilan' not found in mantep , rapih , aya ceminal , cai mineral , ac tiis pisan , aya pamanas cai keur mandi . [a] [o] [s]
Mismatch in instance sentence_id 3627 key 127: opinion_term 'mun ka malang pasti ka dieu deui' not found in palayananna pikaresepeun pisan jeung someah . mun ka malang , pasti ka dieu deui . [a] [o] [s]
Mismatch in instance sentence_id 3628 key 128: opinion_term 'teu luyu jeung nu di gambar . sinhoréng téh di ruang handapeun taneuh' not found in kamar teu luyu jeung nu di gambar . singhoréng téh di ruang handapeun taneuh . sinyal euweuh . parkir kahujanan . [a] [o] [s]
Mismatch in instance sentence_id 3629 key 129: opinion_term 'kirang tarik' not found in caina kurang tarik . [a] [o] [s]
Mismatch in instance sentence_id 3634 key 134: aspect_term 'palayananana' not found in tempatna stratégis , palayananna alus , ngeunaheun jeung lengkep . [a] [o] [s]
Mismatch in instance sentence_id 3636 key 136: opinion_term 'jauh ti karamean' not found in beresih , ngeunaheun , jauh ti karemean , stafna someah . alus , rékomén . [a] [o] [s]
Mismatch in instance sentence_id 3644 key 144: aspect_term 'résepsionisna' not found in hmm , teu luyu jeung ékspéktasi . wangunan geus kolot jeung kurang beresih . cai kamar mandina ngocor waé , matak gandéng . tv-na masih tabung . kecewa atuh ari harga sakitu ngan fasilitasna kitu mah . sarapanna ogé teu loba pilihan , pas rék didahar geus tiis . réesépsionisna teu someah . [a] [o] [s]
Mismatch in instance sentence_id 3683 key 183: opinion_term 'loba cet geus lapuk , kudu dicét deui' not found in sacara umum mah oké , ngan ac-na kurang tiis . loba cet ogé geus lapuk , kudu dicét deui . pagawéna someah , jeung deukeut ka mana-mana . [a] [o] [s]
Mismatch in instance sentence_id 3685 key 185: opinion_term 'punten diperhatikeun' not found in kamar mandi bau pisan , kamar poék . sacara umum mah lumayan lah keur harga sakitu . punten waé diperhatikeun lampuna jeung kamar mandina nya . nuhun ! [a] [o] [s]
Mismatch in instance sentence_id 3685 key 185: opinion_term 'punten diperhatikeun' not found in kamar mandi bau pisan , kamar poék . sacara umum mah lumayan lah keur harga sakitu . punten waé diperhatikeun lampuna jeung kamar mandina nya . nuhun ! [a] [o] [s]
Mismatch in instance sentence_id 3688 key 188: opinion_term 'nyaman' not found in kamar téh bérésih pisan jeung ngeunaheun . hotélna gé bérésih . bakal leuwih hadé mun aya hair dryer di kamar . [a] [o] [s]
Mismatch in instance sentence_id 3699 key 199: opinion_term 'someah' not found in palayanan ramah , hotél anyar , kamar mandi gedé , ngan hanjakalna cai panas keur peuting teu hurung ( rada kecewa ku ieu mah ) . [a] [o] [s]
Mismatch in instance sentence_id 3700 key 200: opinion_term 'kuring check in jam 6 magrib geus dititah check out jam 1' not found in anduk nu disadiakeun ukuranana leutik pisan , jeung urang check in jam 6 magrib geus dititah check out jam 1 . [a] [o] [s]
Mismatch in instance sentence_id 3702 key 202: opinion_term 'engap' not found in kamar eungap , euweuh ventilasi keur hawa . [a] [o] [s]
Mismatch in instance sentence_id 3712 key 212: opinion_term 'ngarep-ngarep kamar diberesihan unggal poé , ngan ieu mah teu diberesihan pisan salila kuring ngéndong' not found in palayananna mah alus , ngan urang téh ngarep-ngarep kamar diberesihan unggal poé , ngan ieu mah teu diberesihan pisan salila urang ngéndong . [a] [o] [s]
Mismatch in instance sentence_id 3715 key 215: opinion_term 'alus pisan dina sagala rupa , teu luyu jeung ékspektasi kuring' not found in alus pisan dina sagala rupa , teu luyu jeung ékspektasi urang . enyaan tempat nu matak nyugemakeun pisan . [a] [o] [s]
Mismatch in instance sentence_id 3745 key 245: opinion_term 'ramah' not found in kamarna alus pisan . beresih jeung soméah . direkomendasikeun pisan . [a] [o] [s]
Mismatch in instance sentence_id 3750 key 250: aspect_term 'kadaharan' not found in pas meunang kamar nu caina ngocor waé , matak hésé saré . dahareun mah nya alhamdulillah , lokasi strategis . lorong ka kamar téh bau hapeuk , ganti atawa piceun waé karpétna meureun leuwih alus . staf ? hm . [a] [o] [s]
Mismatch in instance sentence_id 3772 key 272: opinion_term 'bersih' not found in kamar lega jeung beresih , ngeunaheun . [a] [o] [s]
Mismatch in instance sentence_id 3778 key 278: opinion_term 'bersih' not found in kamar beresih , palayanan alus , stafna soméah kabéh . sarapanna kurang rupa-rupa . lokasina jauh . [a] [o] [s]
Mismatch in instance sentence_id 3782 key 282: opinion_term 'disada wae' not found in kamarna leutik , komo deui mun solat mah kudu di luhur ranjang . ranjangna disada war , jiga geus ménta diganti . sarua deuih , kurang beresih . ac-na teu pati tiis . padahal mah di tengah-tengah maskot bekantan , warung-warung dahareun mah gampang kénéh néanganana . [a] [o] [s]
Mismatch in instance sentence_id 3784 key 284: opinion_term 'jauh pisan padahal hayang ngojay ngan jauh turunna' not found in kamarna dibéré nu jauh pisan , padahal hayang ngojay ngan jauh turunna jeung jauh ogé ka lobi . ngan tenang jeung jauh ti karaméan wé hungkul . [a] [o] [s]
Mismatch in instance sentence_id 3785 key 285: opinion_term 'mirah' not found in murah , deukeut ka bandara jeung joger , gampang nyéwa motor , résépsionisna someah jeung bageur . [a] [o] [s]
Mismatch in instance sentence_id 3792 key 292: opinion_term 'bersih' not found in beresih jeung aman , lokasi strategis , deukeut ka tempat jajan jeung pasar di kawasan bsd . [a] [o] [s]
Mismatch in instance sentence_id 3801 key 301: opinion_term 'lila dieusian deuina' not found in sarapanna kurang rupa-rupa jeung lila pisan dieusian deuina . [a] [o] [s]
Mismatch in instance sentence_id 3809 key 309: aspect_term 'séngdok' not found in nyugemakeun , ngan séndok jeung garpu na kurang beresih . [a] [o] [s]
Mismatch in instance sentence_id 3819 key 319: opinion_term 'punten diperhatikeun deui kabersihanna' not found in kamar mandina puntwn diperhatikeun deui kaberesihanna , jeung rada bau saeutik , utamana klosétna . nuhun . [a] [o] [s]
Mismatch in instance sentence_id 3825 key 325: opinion_term 'kurang bersih' not found in kamar lumayan lega , ngan kurang beresih . aya sababaraha témbok nu lembab jeung aya cucunguk . [a] [o] [s]
Mismatch in instance sentence_id 3831 key 331: opinion_term 'perlu ditingkatkeun' not found in kasiapan perlengkapan kamar téh . kudu ditingkatkeun . [a] [o] [s]
Mismatch in instance sentence_id 3836 key 336: opinion_term 'nu kudu dioméan mah wifi lantai 2 , sok pegat-pegat' not found in nu kudu dioméan mah wifi lanté 2 , sok pegat-pegat . matak sok lag mun keur maén mobile legends . [a] [o] [s]
Mismatch in instance sentence_id 3842 key 342: opinion_term 'kamar teu disadiakeun teu dibéré palayanan ganti tempat , konsumén néangan sorangan' not found in kamar teu disadiakeun , teu dibéré palayanan ganti tempat , konsumén néangan sorangan . [a] [o] [s]
Mismatch in instance sentence_id 3847 key 347: opinion_term 'urang check-in tanggal 2 maret 2018 poé jumaah , ngan peutingna urang teu saré di kamar jeung konci tetep ku kuring dibawa . isukna kuring dihubungi ku pihak nu ngajaga yén kamar kuring diasupan ku maranéhna lantaran aya nu bocor dina pipa wastafel' not found in urang check-in tanggal 2 maret 2018 poé jumaah , ngan peutingna urang teu saré di kamar jeung konci tetep ku urang dibawa . isukna urang dihubungi ku pihak nu ngajaga yén kamar urang diasupan ku maranéhna lantaran aya nu bocor dina pipa wastafel . tuluy maranéhna ngaganti kamar urang jeung kamar nu diganti téh urut dipaké ku batur . lantaran aya anduk baseuh jeung kotor . [a] [o] [s]
Mismatch in instance sentence_id 3847 key 347: opinion_term 'maranéhna ngaganti kamar kuring jeung kamar nu diganti téh urut dipaké ku batur . lantaran aya anduk baseuh jeung kotor' not found in urang check-in tanggal 2 maret 2018 poé jumaah , ngan peutingna urang teu saré di kamar jeung konci tetep ku urang dibawa . isukna urang dihubungi ku pihak nu ngajaga yén kamar urang diasupan ku maranéhna lantaran aya nu bocor dina pipa wastafel . tuluy maranéhna ngaganti kamar urang jeung kamar nu diganti téh urut dipaké ku batur . lantaran aya anduk baseuh jeung kotor . [a] [o] [s]
Mismatch in instance sentence_id 3852 key 352: opinion_term 'euweuh cemilan alesanna airy kakara ngirim' not found in euweuh cemilan alesanana airy kakara ngirim , pamanas cai teu bisa dipaké . [a] [o] [s]
Mismatch in instance sentence_id 3853 key 353: opinion_term 'ku harga murah , urang bisa meunang leuwih pikeun barudak backpacker kawas kuring' not found in ku harga murah , urang bisa meunang leuwih keur barudak backpacker kawas urang . direkomendasikeun pisan euy . [a] [o] [s]
Mismatch in instance sentence_id 3861 key 361: opinion_term 'rada gandéng pas isuk-isuk meureun staf keur beberesih matak rada ngaganggu' not found in tempatna ngeunaheun beresih , ngan rada gandéng pas isuk-isuk , meureun staf keur beberesih matak rada ngaganggu . ngan sacara umum mah tempatna alus . [a] [o] [s]
Mismatch in instance sentence_id 3862 key 362: aspect_term 'staf kabersihan' not found in kamar nu dipaké ku urang téh kasurna ngeunaheun pisan , sanajan staf kaberesihan kudu ngaberesihan deui kamar nu rék dipaké ku urang téh lantaran aya nu tinggaleun . [a] [o] [s]
Mismatch in instance sentence_id 3862 key 362: opinion_term 'kudu ngabersihan deui kamar nu rék dipaké ku urang téh lantaran aya nu tinggaleun' not found in kamar nu dipaké ku urang téh kasurna ngeunaheun pisan , sanajan staf kaberesihan kudu ngaberesihan deui kamar nu rék dipaké ku urang téh lantaran aya nu tinggaleun . [a] [o] [s]
Mismatch in instance sentence_id 3872 key 372: aspect_term 'pamandanganana' not found in kamar rapih , ngeunaheun , palayanan someah . direkomendasikeun pisan atuh . ngan hanjakal pas muka hordéng jandéla , pamandanganna kurang alus . [a] [o] [s]
Mismatch in instance sentence_id 3890 key 390: aspect_term 'palayananana' not found in palayananna alus pisan , cocok pisan keur nu ngumbara nu hayang ngéndong di daérah ciputat . [a] [o] [s]
Mismatch in instance sentence_id 3908 key 408: opinion_term 'keuheul lantaran réstoran tempat sarapan rauanganna make ac , ngan bet diidinan udud' not found in keuheul lantaran réstoran tempat sarapan ruanganana make ac , ngan bet diidinan udud . bauna kacida ngaganggu napas keur nu teu udud . [a] [o] [s]
Mismatch in instance sentence_id 3911 key 411: aspect_term 'pelayanan' not found in palayanan nu soméah , ngan kaberesihan jeung kangeunaheunan kudu ditingkatkeun . [a] [o] [s]
Mismatch in instance sentence_id 3911 key 411: opinion_term 'ramah' not found in palayanan nu soméah , ngan kaberesihan jeung kangeunaheunan kudu ditingkatkeun . [a] [o] [s]
Mismatch in instance sentence_id 3911 key 411: opinion_term 'perlu ditingkatkeun' not found in palayanan nu soméah , ngan kaberesihan jeung kangeunaheunan kudu ditingkatkeun . [a] [o] [s]
Mismatch in instance sentence_id 3928 key 428: opinion_term 'jiga kadaharan ucing , jadi néangan sarapan di luar' not found in kamar bau , simbut jeung anduk buluk . stafna teu soméah . kamar teu luyu jeung ekspektasi , heurin jeung sumpek . sarapanana jiga dahareun ucing , matak néangan sarapan di luar . keur harga sakitu mah , teu pantes . [a] [o] [s]
Mismatch in instance sentence_id 3929 key 429: opinion_term 'mesen 2 kamar ngan meunang sendal 2 pasang' not found in mesen 2 kamar , ngan meunang sendal 2 pasang . kamarna bau . [a] [o] [s]
Mismatch in instance sentence_id 3935 key 435: aspect_term 'pemanas' not found in sacara umum mah ngeunaheun . lokasi deukeut stasion , loba warung dahar jeung laundry di sabudeureunna . ac tiis , kamar mandi lumayan sanajan euwuh pamanas , tv mah oke . ngan rada heurin wé jeung wifi teu bisa dipaké . [a] [o] [s]
Mismatch in instance sentence_id 3935 key 435: opinion_term 'euwueh pemanas' not found in sacara umum mah ngeunaheun . lokasi deukeut stasion , loba warung dahar jeung laundry di sabudeureunna . ac tiis , kamar mandi lumayan sanajan euwuh pamanas , tv mah oke . ngan rada heurin wé jeung wifi teu bisa dipaké . [a] [o] [s]
Mismatch in instance sentence_id 3939 key 439: aspect_term 'termos' not found in ieu téh alus pisan , ngeunaheun pisan . ngan nu kurang mah mun aya térmos nu téko keur masak cai panas jeung téh sasét jeung gula , ameh isuk-isuk bisa nyieun téh . ngan ieu gé geus alus sih . [a] [o] [s]
Mismatch in instance sentence_id 3949 key 449: opinion_term 'mesen kamar nu aya sarapan ngan kalah teu dibéré sarapan' not found in mesen kamar nu aya sarapan , ngan kalah teu dibéré sarapan . euweuh sabun , euweuh sampo , anduk gé teu diganti . hadeuh . [a] [o] [s]
Mismatch in instance sentence_id 3951 key 451: opinion_term 'geus lunas mayar tapi kamar teu aya nepi ka kudu ngadagoan' not found in geus lunas mayar , ngan kamar téh euweuh nepi ka kudu ngadagoan jeung rada parebut jeung palanggan séjén sangkan meunang kamar . [a] [o] [s]
Mismatch in instance sentence_id 3957 key 457: aspect_term 'lantai 4' not found in lamun wifi euweuh , ulah dijieun aya . lanté 4 gandéng , meureun aya kulawarga atawa naon wéh . kamar lega . [a] [o] [s]
Mismatch in instance sentence_id 3972 key 472: aspect_term 'kamar mandi flush owl-na' not found in teu bisa dibalikeun duitna . kamar mandi , flush owl-na jiga kopi . [a] [o] [s]
Mismatch in instance sentence_id 3980 key 480: opinion_term 'teu aya kawijakan diwaktu force majeure' not found in aya musibah , ngan pihak hotél teu méré toleransi keur ngarobah jadwal . ngarasa kaduhung geus mesen liwat airy , euweuh kawijakan diwaktu force majeure . [a] [o] [s]
Mismatch in instance sentence_id 3983 key 483: aspect_term 'kanal tipi na gambarna' not found in nu kudu dibenerkeun téh kanal tipi na , gambarna kurang alus . mun bisa mah maké tipi kabel wé hé . [a] [o] [s]
Mismatch in instance sentence_id 4031 key 531: aspect_term 'coffee maker' not found in wifi teu nyambung , suasana kurang tenang lantaran aya rénovasi di lobi . kamar leuwih leutik ti nu katingalina . euweuh mesin jang ninyuh kopi di kamar padahal dina fotona mah aya . aya laleur di kamar jeung hésé ngaluarkeunna sabab jandélana ukur kaca jeung teu bisa dibuka . [a] [o] [s]
Mismatch in instance sentence_id 4042 key 542: opinion_term 'teu bisa nutup sabab teu aya konci' not found in jandéla kamar teu bisa nutup sabab euweuh konci , matak loba reungit nu asup ka kamar . [a] [o] [s]
Mismatch in instance sentence_id 4056 key 556: aspect_term 'lantai kamar mandi' not found in meunang cemilan airy sanggeus checkout , sarapan meunang sangu kotak , lanté kamar mandi leueur , kamar rada bau . [a] [o] [s]
Mismatch in instance sentence_id 4056 key 556: aspect_term 'ceminal airy' not found in meunang cemilan airy sanggeus checkout , sarapan meunang sangu kotak , lanté kamar mandi leueur , kamar rada bau . [a] [o] [s]
Mismatch in instance sentence_id 4085 key 585: opinion_term 'poék da pan aya di péngkolan' not found in lampu panyaangan pas asup hotél poék , da pan aya di péngkolan , kudu leuwih jelas jeung caang . punten nuhun . [a] [o] [s]
Mismatch in instance sentence_id 4090 key 590: opinion_term 'luyu jeung budget' not found in hotélna biasa-biasa waé , luyu jeung anggaran . ngan kamari kudu mayar 100 rébu gara-gara nu ngendong tiluan . [a] [o] [s]
Mismatch in instance sentence_id 4092 key 592: opinion_term 'bersih' not found in beresih , leuwih ngeunaheun deui lamun disiapkeun cai panas di dispenser . hatur nuhun . [a] [o] [s]
Mismatch in instance sentence_id 4099 key 599: opinion_term 'rada heureut' not found in beresih , ngan kamar rada heurin . mun keur dua urang mah cocok . mun keur kulawarga nu geus boga budak mah , sigana karunya budakna . [a] [o] [s]
Mismatch in instance sentence_id 4105 key 605: aspect_term 'kabersihan' not found in palayanan alus jeung someah , kaberesihan jeung kangeunaheun kamar téh alus pisan , ari sarapan isuk-isuk mah standar wé . [a] [o] [s]
Mismatch in instance sentence_id 4111 key 611: opinion_term 'bersih' not found in tempatna beresih jeung seungit . panjagana someah . tempat parkirna lega jeung aman . [a] [o] [s]
Mismatch in instance sentence_id 4121 key 621: opinion_term 'parahna deui sinyal wifi ogé teu nepi . jadi komunikasi ka luar kapegat .' not found in kamar lumayan , ac cukupan , kamar mandi aya cai rada haneut . ngan hanjakal di kamar single standar nu euweuh pamandangan mah euweuh sinyal hp ( sabab di basemen ) jeung parahna deui sinyal wifi ogé teu nepi . matak komunikasi ka luar kapegat . [a] [o] [s]
Mismatch in instance sentence_id 4126 key 626: opinion_term 'dikuciwakeun terus-terusan' not found in sababaraha kali ngéndong ( langganan ) , kakara ayeuna dikecewakeun tuluy-tuluyan . hiji , panto kamar dipaksa dibuka kulantaran teu apal mun kamar nu éta téh geus kaeusian ( kaeusian ) . nu puguh mah , di front office konci kamar nu diséwa ku urang téh euweuh . [a] [o] [s]
Mismatch in instance sentence_id 4126 key 626: opinion_term 'dikecewakeun tuluy-tuluyan . hiji , panto kamar dipaksa dibuka kulantaran teu apal mun kamar nu éta téh geus kaeusian ( kauesian )' not found in sababaraha kali ngéndong ( langganan ) , kakara ayeuna dikecewakeun tuluy-tuluyan . hiji , panto kamar dipaksa dibuka kulantaran teu apal mun kamar nu éta téh geus kaeusian ( kaeusian ) . nu puguh mah , di front office konci kamar nu diséwa ku urang téh euweuh . [a] [o] [s]
Mismatch in instance sentence_id 4127 key 627: opinion_term 'bakal jadi langganan' not found in beresih pisan , kamar mandi beresih , kasur , tv , jeung aya cemilanna . reseup pisan ngéndong di dieu , bakal matak langganan . [a] [o] [s]
Mismatch in instance sentence_id 4128 key 628: opinion_term 'mani alus pisan' not found in kamar téh meni alus pisan keur biaya nu ékonomis . direkomendasikeun pisan . [a] [o] [s]
Mismatch in instance sentence_id 4140 key 640: opinion_term 'leuwih kékénan deui lamun aya sendal' not found in fasilitasna lengkep , palayananna ogé oke , ngan kolam renangna kurang beresih , teu meunang cemilan airy siga baheula , jeung leuwih keren deui lamun aya sendal . [a] [o] [s]
Mismatch in instance sentence_id 4156 key 656: opinion_term 'kurang bersih' not found in lumayan oké palayananna . ngan andukna kurang beresih . nuhun . [a] [o] [s]

In [47]:
df_translated_correction['aspect_or_opinion_not_in_input'] = [idx in mismatch_indexes for idx in df_translated_correction.index]
df_translated_correction['mismatch_notes'] = [mismatch_notes.get(idx, []) for idx in df_translated_correction.index]
df_translated_correction['mismatch_notes_format'] = df_translated_correction['mismatch_notes'].apply(lambda x: '\n'.join(x))

In [48]:
df_translated_correction[['aspect_or_opinion_not_in_input', 'mismatch_notes_format']].to_csv(f'temp/translation_output/{lang_target}/{dataset_folder}/translated_dataset_{lang}_{split}_correction_mismatches.csv', index=False)