In [1]:
import pandas as pd
import numpy as np
import json
import re
from ast import literal_eval
import importlib
from dotenv import load_dotenv
import os
os.chdir('..')

In [2]:
# Load environment variables from .env file
load_dotenv()

True

In [3]:
# Set GEMINI_API_KEY environment variable with your API key
os.environ['GEMINI_API_KEY'] = os.getenv('GEMINI_API_KEY')

In [4]:
import base64
from google import genai
from google.genai import types
from copy import deepcopy

In [5]:
def generate(prompt):
	client = genai.Client(
			api_key=os.environ.get("GEMINI_API_KEY"),
		)

	model = "gemini-2.5-flash"
	contents = [
		types.Content(
			role="user",
			parts=[
				types.Part.from_text(
					text=prompt
				),
			],
		),
	]
	generate_content_config = types.GenerateContentConfig(
		temperature=0.75,
		top_p=0.9,
		top_k=40,
		max_output_tokens=8192,
		thinking_config=types.ThinkingConfig(thinking_budget=-1), # Dynamic thinking = -1, no thinking = 0
		response_mime_type="application/json",
		system_instruction=[
			types.Part.from_text(
				text="""You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and English."""
			),
		],
	)
		
	response = client.models.generate_content(
		model=model, contents=contents, config=generate_content_config
	)
	# print(response.text)
	return response

from typing import List, Dict
import re
def parse_absa_string(text: str) -> List[Dict[str, str]]:
    """
    Parses a string formatted as "[A] aspect [O] opinion [S] sentiment" into a list of dictionaries.
    Each dictionary contains the tag as the key and the corresponding value.
    For example, "[A] [O] [S] [A] harga [O] terjangkau [S] positive [SSEP] [A] fasilitas [O] nyaman [S] positive" becomes:
    [{'A': 'harga', 'S': 'positive', 'O': 'terjangkau'},
    {'A': 'fasilitas', 'S': 'positive', 'O': 'nyaman'}].

    Args:
        text (str): ABSA string output to be parsed.

    Returns:
        List[Dict[str, str]]: List of dictionaries of parsed ABSA output.

    """
    pattern = r"\[(\w+)\]\s*([^[]+)"
    matches = re.findall(pattern, text)

    result = []
    current_dict = {}

    for tag, content in matches:
        if tag == "SSEP":  # Sentence separator -> Start a new dictionary
            result.append(current_dict)
            current_dict = {}
        else:
            current_dict[tag] = content.strip()

    if current_dict:  # Append the last sentence if it exists
        result.append(current_dict)

    return result

In [6]:
dataset_folder = 'mvp_aos'
dataset_type = 'hotel_reviews'
lang = 'indo'
split = 'train'
dataset_path = f'dataset/{dataset_type}/{lang}/{dataset_folder}/{split}.json'
with open(dataset_path, 'r') as f:
	dataset = json.load(f)

In [7]:
dataset_unique = []
for instance in dataset:
	if instance['element_order'] == 'aos':
		dataset_unique.append(deepcopy(instance))

In [8]:
dataset_single_triplet = []
for instance in dataset_unique:
	triplets = parse_absa_string(instance['target'])
	for triplet in triplets:
		new_instance = deepcopy(instance)
		new_instance['target'] = f"[A] {triplet.get('A', '')} [O] {triplet.get('O', '')} [S] {triplet.get('S', '')}"
		dataset_single_triplet.append(new_instance)

In [9]:
df_dataset = pd.DataFrame(dataset_unique)
df_dataset

,sentence_id,instance_id,input,target,element_order,task_elements
0,0,0,kamar saya ada kendala di ac tidak berfungsi o...,[A] ac [O] tidak berfungsi optimal [S] negativ...,aos,aos
1,1,5,tempatnya bagus . kolam renangnya bersih . [A]...,[A] tempatnya [O] bagus [S] positive [SSEP] [A...,aos,aos
2,2,10,"oke banget , tetapi ac nya tidak bisa diatur s...",[A] ac nya [O] tidak bisa diatur suhu nya [S] ...,aos,aos
3,3,15,keren . nyaman semuanya . [A] [O] [S],[A] semuanya [O] nyaman [S] positive [SSEP] [A...,aos,aos
4,4,20,"tidak dapat snack . setelah di keluhan , baru ...",[A] snack [O] tidak dapat [S] negative,aos,aos
...,...,...,...,...,...,...
2477,2495,12475,wifi kurang joss . [A] [O] [S],[A] wifi [O] kurang joss [S] negative,aos,aos
2478,2496,12480,"kamar cukup bersih , hanya sempit , . [A] [O] [S]",[A] kamar [O] cukup bersih [S] positive [SSEP]...,aos,aos
2479,2497,12485,"nyaman , bersih , dan pelayananya sangat ramah...",[A] pelayananya [O] sangat ramah [S] positive ...,aos,aos
2480,2498,12490,sangat kecewa dengan kamar dan pelayanan stafn...,[A] kamar [O] sangat kecewa [S] negative [SSEP...,aos,aos
2481,2499,12495,"sayang , air panasnya tidak terlalu panas , ja...","[A] air panasnya [O] tidak terlalu panas , jad...",aos,aos

In [10]:
check_list = df_dataset['sentence_id'].to_list()
# Check if check_list is ordered from smallest to largest (missing indexes is allowed, just make sure the order is correct)
is_ordered = all(earlier <= later for earlier, later in zip(check_list, check_list[1:]))
print(f"Is the sentence_id list ordered? {is_ordered}")

Is the sentence_id list ordered? True

In [11]:
lang_target = 'mad'
with open(f'notebooks/prompt_translate/translate-triplet-{lang_target}.txt', 'r') as f:
	prompt_template = f.read()
print(prompt_template)

### Instruction
You will be given input-output pairs of Aspect Sentiment Triplet Extraction.
Given an Indonesian text and triplets consist of aspect term, opinion term, and sentiment polarity, translate all of them to Enjek-Iye level of Madurese. Enjek-Iye level Madurese is the informal variety of Madurese used in daily conversations between friends or people of the same age.
The order of the triplet is (aspect term, opinion term, sentiment polarity).
Below is the definition of each element in the triplet:
- The aspect term refers to a specific feature, attribute, or aspect of a product or service on which a user can express an opinion. Explicit aspect terms appear explicitly as a substring of the given text. The aspect term might be “NULL” for the implicit aspect.
- The sentiment polarity refers to the degree of positivity, negativity or neutrality expressed in the opinion towards a particular aspect or feature of a product or service, and the available polarities include: “positive”, “negative” and “neutral”. “neutral” means mildly positive or mildly negative.
- The opinion term refers to the sentiment or attitude expressed by a user towards a particular aspect or feature of a product or service. Explicit opinion terms appear explicitly as a substring of the given text. The opinion term might be "NULL" for the implicit opinion.

For the special case when the triplets is empty, just return an empty list for the translated triplets component.

### Step-by-step Instruction
1. Carefully read the sentence and its triplets to understand the context.
2. Translate the sentence, maintaining the original meaning, tone, style, and cultural nuances.
3. Translate the triplets of the sentence. Ensure that all elements of the triplet still matches the sentence. The translated aspect term and the opinion term must exist literally in the translated sentence. Do not make up your own words for the triplet translation part.
4. Ensure that any idiomatic expressions are adapted appropriately to fit the target language.
5. Review the translation for any grammatical or syntactical errors.
6. Write the translations in json format.

### Example:
Text Input: "sebenarnya kamar baik tetapi kurang profesional , di kasih tahu sarapan nasi goreng , minta di antar jam 8.30 ehh datang jam 9 itu pun di telepon dulu dan yang datang bahkan mie muah telor . hm ."
Triplets: [(kamar, baik, positive), (null, kurang profesional, negative)]
Output:
{
    "translated_text": "Mun kamarra nyaman meske tape korang profesional. Eberri tao Mun Olle sarapan nasi goreng, minta e ateraghi kol 8:30 tape deteng kol 9 nambu e telpon gellu, sela se deteng mie kuah telor . hm",
    "translated_triplets": [
        {
            "aspect_term": "kamar",
            "opinion_term": "nyaman",
            "sentiment_polarity": "positive"
        },
        {
            "aspect_term": "null",
            "opinion_term": "korang profesional",
            "sentiment_polarity": "negative"
        }
    ]
}

### Inference:

Text Input: {text-input}
Triplets: {input-triplets}
Output:

### Individual API request

In [ ]:
from tqdm import tqdm
from time import sleep
from ast import literal_eval

outputs = {}
outputs_text = {}
for idx, row in tqdm(df_dataset.iterrows(), desc="Translating triplets", total=df_dataset.shape[0]):
	input_text = row['input'].replace('[A] [O] [S]', '').strip()
	triplets = parse_absa_string(row['target'])
	target_text = []
	for triplet in triplets:
		target_text.append(f"({triplet.get('A', 'err_empty')}, {triplet.get('O', 'err_empty')}, {triplet.get('S', 'err_empty')})")
	target_text = '[' + ', '.join(target_text) + ']'
	prompt = prompt_template.replace('{text-input}', input_text).replace('{input-triplets}', target_text)
	while True:
		try:
			output = generate(prompt)
			outputs[idx] = output
			outputs_text[idx] = literal_eval(output.text)
			outputs_text[idx]['text'] = input_text
			outputs_text[idx]['triplets'] = target_text
			break
		except Exception as e:
			print(f"Error: {e}")
			sleep(3.0)  # Wait for 3 seconds before retrying
			continue
	
	# Write to json file after each successful generation
	os.makedirs(f'temp/translation_output/eng/{dataset_folder}', exist_ok=True)
	with open(f'temp/translation_output/eng/{dataset_folder}/{os.path.basename(dataset_path)}', 'w') as f:
		json.dump(outputs_text, f, indent=4, ensure_ascii=False)
	
	if idx == 10:
		break

Translating triplets:   0%|          | 0/2482 [00:03<?, ?it/s]

KeyboardInterrupt:

### Batch API request

In [12]:
targetlang2langname = {
	'indo': 'Indonesian',
    'sunda': 'Sundanese',
    'jav': 'Javanese',
    'min': 'Minangkabau',
    'mad': 'Madurese',
}

In [13]:
inline_requests = []
temp_for_jsonl = []
for idx, row in df_dataset.iterrows():
	input_text = row['input'].replace('[A] [O] [S]', '').strip()
	triplets = parse_absa_string(row['target'])
	target_text = []
	for triplet in triplets:
		target_text.append(f"({triplet.get('A', 'err_empty')}, {triplet.get('O', 'err_empty')}, {triplet.get('S', 'err_empty')})")
	target_text = '[' + ', '.join(target_text) + ']'
	prompt = prompt_template.replace('{text-input}', input_text).replace('{input-triplets}', target_text)
	
	inline_request = {
		"contents": [
			{
				"role": "user",
				"parts": [
					{
						"text": prompt
					}
				]
			}
		],
		"generation_config": {
			"temperature": 0.75,
			"top_p": 0.9,
			"top_k": 40,
			"max_output_tokens": 8192,
			"thinking_config": {
				"thinking_budget": -1
			},
			"response_mime_type": "application/json",
		},
		"system_instruction": {
			"parts": [
				{
					'text': f"You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and {targetlang2langname[lang_target]}."
				}
			]
		}
	}
	inline_requests.append(inline_request)

	temp_for_jsonl.append({
		'key': f'request-{row["sentence_id"]}',
		'request': inline_request
	})
	# if idx == 4:
	# 	break

In [14]:
len(inline_requests), len(temp_for_jsonl)

(2482, 2482)

In [15]:
# print(inline_requests[-10]['contents'][0]['parts'][0]['text'])
print(temp_for_jsonl[-1])

{'key': 'request-2499', 'request': {'contents': [{'role': 'user', 'parts': [{'text': '### Instruction\nYou will be given input-output pairs of Aspect Sentiment Triplet Extraction.\nGiven an Indonesian text and triplets consist of aspect term, opinion term, and sentiment polarity, translate all of them to Enjek-Iye level of Madurese. Enjek-Iye level Madurese is the informal variety of Madurese used in daily conversations between friends or people of the same age.\nThe order of the triplet is (aspect term, opinion term, sentiment polarity).\nBelow is the definition of each element in the triplet:\n- The aspect term refers to a specific feature, attribute, or aspect of a product or service on which a user can express an opinion. Explicit aspect terms appear explicitly as a substring of the given text. The aspect term might be “NULL” for the implicit aspect.\n- The sentiment polarity refers to the degree of positivity, negativity or neutrality expressed in the opinion towards a particular aspect or feature of a product or service, and the available polarities include: “positive”, “negative” and “neutral”. “neutral” means mildly positive or mildly negative.\n- The opinion term refers to the sentiment or attitude expressed by a user towards a particular aspect or feature of a product or service. Explicit opinion terms appear explicitly as a substring of the given text. The opinion term might be "NULL" for the implicit opinion.\n\nFor the special case when the triplets is empty, just return an empty list for the translated triplets component.\n\n### Step-by-step Instruction\n1. Carefully read the sentence and its triplets to understand the context.\n2. Translate the sentence, maintaining the original meaning, tone, style, and cultural nuances.\n3. Translate the triplets of the sentence. Ensure that all elements of the triplet still matches the sentence. The translated aspect term and the opinion term must exist literally in the translated sentence. Do not make up your own words for the triplet translation part.\n4. Ensure that any idiomatic expressions are adapted appropriately to fit the target language.\n5. Review the translation for any grammatical or syntactical errors.\n6. Write the translations in json format.\n\n### Example:\nText Input: "sebenarnya kamar baik tetapi kurang profesional , di kasih tahu sarapan nasi goreng , minta di antar jam 8.30 ehh datang jam 9 itu pun di telepon dulu dan yang datang bahkan mie muah telor . hm ."\nTriplets: [(kamar, baik, positive), (null, kurang profesional, negative)]\nOutput:\n{\n    "translated_text": "Mun kamarra nyaman meske tape korang profesional. Eberri tao Mun Olle sarapan nasi goreng, minta e ateraghi kol 8:30 tape deteng kol 9 nambu e telpon gellu, sela se deteng\xa0mie\xa0kuah\xa0telor . hm",\n    "translated_triplets": [\n        {\n            "aspect_term": "kamar",\n            "opinion_term": "nyaman",\n            "sentiment_polarity": "positive"\n        },\n        {\n            "aspect_term": "null",\n            "opinion_term": "korang profesional",\n            "sentiment_polarity": "negative"\n        }\n    ]\n}\n\n### Inference:\n\nText Input: sayang , air panasnya tidak terlalu panas , jadi kalau mandi kedinginan . hhehe .\nTriplets: [(air panasnya, tidak terlalu panas , jadi kalau mandi kedinginan, negative)]\nOutput:\n'}]}], 'generation_config': {'temperature': 0.75, 'top_p': 0.9, 'top_k': 40, 'max_output_tokens': 8192, 'thinking_config': {'thinking_budget': -1}, 'response_mime_type': 'application/json'}, 'system_instruction': {'parts': [{'text': 'You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and Madurese.'}]}}}

In [16]:
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

In [17]:
# Create a jsonl file for inline requests
os.makedirs(f'temp/translation_output/{lang_target}/{dataset_folder}', exist_ok=True)
with open(f'temp/translation_output/{lang_target}/{dataset_folder}/inline_requests_{lang_target}_{split}.jsonl', 'w') as f:
	for item in temp_for_jsonl:
		f.write(json.dumps(item, ensure_ascii=False) + '\n')

In [18]:
# Upload the file to the File API
uploaded_file = client.files.upload(
    file=f'temp/translation_output/{lang_target}/{dataset_folder}/inline_requests_{lang_target}_{split}.jsonl',
    config=types.UploadFileConfig(display_name=f'inline_requests_{lang_target}_{split}', mime_type='jsonl')
)

print(f"Uploaded file: {uploaded_file.name}")

Uploaded file: files/ix88t08idmt2

In [21]:
from google import genai

# Assumes `uploaded_file` is the file object from the previous step
file_batch_job = client.batches.create(
    model="gemini-2.5-flash",
    src=uploaded_file.name,
    config={
        'display_name': f"file-upload-job-translation-{lang_target}-{split}-fixed",
    },
)

print(f"Created batch job: {file_batch_job.name}")

ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit. ', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}]}}

In [20]:
# List all batches
batches = client.batches.list()
for batch in batches:
    print(f"Batch ID: {batch.name}, State: {batch.state.name}, Display Name: {batch.display_name}")

Batch ID: batches/j8rg2se3a2hzp4ziaspq8n81f1l6687hdv0d, State: JOB_STATE_PENDING, Display Name: file-upload-job-translation-min-train
Batch ID: batches/94ipo9kv0sh5r0923lpiqib0onz3wvfjdqs3, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-mad-train
Batch ID: batches/aaodv2jutswgb1vrjs8sg2iikhluo5udboxe, State: JOB_STATE_SUCCEEDED, Display Name: None
Batch ID: batches/dfkyvx1ka9aj8xhh4zt6w47xgptxvbki75as, State: JOB_STATE_SUCCEEDED, Display Name: None
Batch ID: batches/40ogifgcu82d4tx1vk9gmg97mcoqlq3z7l94, State: JOB_STATE_SUCCEEDED, Display Name: None
Batch ID: batches/filprkchw3b7wpcl38haxk9p6fe9boj4dls2, State: JOB_STATE_SUCCEEDED, Display Name: hoasa-augment-job
Batch ID: batches/9neirboro5zb7gpqa4u3o99tztr6kj0kt67s, State: JOB_STATE_SUCCEEDED, Display Name: hoasa-augment-job
Batch ID: batches/lpxh4xaknvxckykmrk9hjbazv87anyyklal4, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-jav-train-fixed
Batch ID: batches/9udm06rnexogkfmqcxmav7oblt1g6lm467z3, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-jav-test
Batch ID: batches/jbu1m7rk7953auz9a0xipwxxl2bh14i0q42j, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-jav-dev
Batch ID: batches/675kvbrqpt3igvutlowozqsdjjxlalad5eaf, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-jav-train
Batch ID: batches/65azlnc2oetwg4x6np88dz9wgmwsyo98ki9o, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-sunda-dev-all
Batch ID: batches/mucz1j6fvlq0n4krwws4528xk181u4lxfnqy, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-eng-dev-all
Batch ID: batches/jyjjxzt3feea2hrx8ft25cpwu7e1mdxhge3r, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-sunda-train-all
Batch ID: batches/j64igjih81kj18rzkctzv5yfa7pk1arw0uaf, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-sunda-train
Batch ID: batches/ggref704rxuzp94z6nrqm5nkt1jwihae7n2n, State: JOB_STATE_SUCCEEDED, Display Name: aste-long-token-job
Batch ID: batches/s70rg9mcrhz1jgpmda0e4jfmz79n5324sh8s, State: JOB_STATE_SUCCEEDED, Display Name: hoasa-augment-job
Batch ID: batches/jklx0tqwvxnas5h5bfn3l6wk6wztv4ztebl6, State: JOB_STATE_SUCCEEDED, Display Name: file-upload-job-translation-sunda-train
Batch ID: batches/1qi0dsiovljruakbln7knfizvtpa43gthfn9, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/d14hsrjoulu7by2a1uin6rjiep6pzpl29zym, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/4uewhtitdcuub6z9663vc8t94subfq4n6qx6, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/mdmaao1nf2gpndgpa8pqzhgxvuwtktgj2e3u, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/dea1kpv8fspa9wpfz9h20xmx7uvnyazf8fnr, State: JOB_STATE_SUCCEEDED, Display Name: aste-augment-job
Batch ID: batches/l17q9aj8zbhjk6znqc8jpo28jomk5izvnu3i, State: JOB_STATE_SUCCEEDED, Display Name: hoasa-batch-job
Batch ID: batches/pl3jwvqdf3olq9gq5cktudc2ufpcp7qeni7n, State: JOB_STATE_SUCCEEDED, Display Name: hoasa-batch-job
Batch ID: batches/y76wencie9ce0ul19qh2atajli6f6fi09zh9, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo_sunda-test
Batch ID: batches/7566g4tpokgt1intakwz09hvj6160li42202, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo_sunda-train
Batch ID: batches/asmmwwk6f8kfkavhj70cth2l60zwwaf3hl6s, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo-train-1000onwards
Batch ID: batches/5crm0h0t2580p641oyxpdhpku0q5h9o8ahzp, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo-1
Batch ID: batches/sde88za41ogfgscv3eg94ezopyjeirkhiu1x, State: JOB_STATE_SUCCEEDED, Display Name: job-translation-indo-1
Batch ID: batches/evg9i1wyd8gvczvytcxt9omherlhibe0vtum, State: JOB_STATE_SUCCEEDED, Display Name: job-1-test
Batch ID: batches/xr5ky0oempio6kujvbxemftbm98goz78mw23, State: JOB_STATE_SUCCEEDED, Display Name: job-1-test

In [ ]:
from time import sleep

# Use the name of the job you want to check
# e.g., inline_batch_job.name from the previous step
job_name = "batches/9udm06rnexogkfmqcxmav7oblt1g6lm467z3"  # (e.g. 'batches/your-batch-id')
batch_job = client.batches.get(name=job_name)

completed_states = set([
    'JOB_STATE_SUCCEEDED',
    'JOB_STATE_FAILED',
    'JOB_STATE_CANCELLED',
    'JOB_STATE_EXPIRED',
])

print(f"Polling status for job: {job_name}")
batch_job = client.batches.get(name=job_name) # Initial get
while batch_job.state.name not in completed_states:
  print(f"Current state: {batch_job.state.name}")
  sleep(30) # Wait for 30 seconds before polling again
  batch_job = client.batches.get(name=job_name)

print(f"Job finished with state: {batch_job.state.name}")
if batch_job.state.name == 'JOB_STATE_FAILED':
    print(f"Error: {batch_job.error}")

Polling status for job: batches/9udm06rnexogkfmqcxmav7oblt1g6lm467z3
Job finished with state: JOB_STATE_SUCCEEDED

In [ ]:
from tqdm import tqdm

In [ ]:
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

# Use the name of the job you want to check
# e.g., inline_batch_job.name from the previous step
job_name = "batches/9udm06rnexogkfmqcxmav7oblt1g6lm467z3"
batch_job = client.batches.get(name=job_name)

outputs = {}
outputs_text = {}

if batch_job.state.name == 'JOB_STATE_SUCCEEDED':

	# If batch job was created with a file
	if batch_job.dest and batch_job.dest.file_name:
		# Results are in a file
		result_file_name = batch_job.dest.file_name
		print(f"Results are in file: {result_file_name}")

		print("Downloading result file content...")
		file_content = client.files.download(file=result_file_name)
		# Process file_content (bytes) as needed
		lines = file_content.decode('utf-8').splitlines()
		for i, line in tqdm(enumerate(lines)):
			result = json.loads(line)
			key = result['key'].split('-')[-1]

			# print(result)
			if 'response' in result:
				try:
					outputs_text[key] = literal_eval(result['response']['candidates'][0]['content']['parts'][0]['text'])
				except Exception as e:
					print(f"Error in Response {i+1}: {e}")
					outputs_text[key] = result['response']  # Fallback
					outputs_text[key] = {
						'translated_text': '',
						'translated_triplets': [],
					}
			elif 'error' in result:
				print(f"Error: {result['error']}")

	# If batch job was created with inline request
	# (for embeddings, use batch_job.dest.inlined_embed_content_responses)
	elif batch_job.dest and batch_job.dest.inlined_responses:
		# Results are inline
		print("Results are inline:")
		for i, inline_response in tqdm(enumerate(batch_job.dest.inlined_responses)):
			if inline_response.response:
				# Accessing response, structure may vary.
				try:
					outputs_text[i] = literal_eval(inline_response.response.text)
				except Exception as e:
					print(f"Error in Response {i+1}: {e}")
					outputs_text[i] = inline_response.response  # Fallback
					outputs_text[i] = {
						'translated_text': '',
						'translated_triplets': [],
					}
			elif inline_response.error:
				print(f"Error: {inline_response.error}")
	else:
		print("No results found (neither file nor inline).")
else:
	print(f"Job did not succeed. Final state: {batch_job.state.name}")
	if batch_job.error:
		print(f"Error: {batch_job.error}")

Results are in file: files/batch-9udm06rnexogkfmqcxmav7oblt1g6lm467z3
Downloading result file content...

1000it [00:00, 15343.74it/s]

Error in Response 400: 'content'

In [ ]:
# for i, inline_response in tqdm(enumerate(batch_job.dest.inlined_responses)):
# 	if inline_response.response:
# 		# Accessing response, structure may vary.
# 		try:
# 			print(f"----------------- Response {i+1} -----------------")
# 			print(literal_eval(inline_response.response.text))
# 			print(inline_requests[i]['contents'][0]['parts'][0]['text'].split('### Inference:')[-1].strip())
# 		except Exception as e:
# 			print(f"Error in Response {i+1}: {e}")
# 			# outputs[i] = inline_response.response  # Fallback
# 			print(inline_response.response.text)
# 	elif inline_response.error:
# 		print(f"Error: {inline_response.error}")

In [ ]:
dataset_path

'dataset/hotel_reviews/indo/mvp_aos/test.json'

In [ ]:
save_path = f'temp/translation_output/{lang_target}/{dataset_folder}/{os.path.basename(dataset_path)}'

In [ ]:
save_path

'temp/translation_output/jav/mvp_aos/test.json'

In [ ]:
os.makedirs(f'temp/translation_output/{lang_target}/{dataset_folder}', exist_ok=True)
with open(save_path, 'w') as f:
	json.dump(outputs_text, f, indent=4, ensure_ascii=False)
print(f"Saved translated outputs to {save_path}")

Saved translated outputs to temp/translation_output/jav/mvp_aos/test.json

## Preprocess

In [ ]:
with open(save_path, 'r') as f:
	outputs_text = json.load(f)

In [ ]:
def add_space_around_punctuation(text):
    # Except for '-'
    # Ensure space before punctuation
    text = re.sub(r'(\S)([.,!?\(\)\"\';:+/]+)', r'\1 \2', text)
    # Ensure space after punctuation
    text = re.sub(r'([.,!?\(\)\"\';:+/]+)(\S)', r'\1 \2', text)
    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)
    # Ensure punctuation sequences like '...' are split into spaced dots
    text = re.sub(r'([.]{2,})', lambda m: ' '.join(m.group(1)), text)
    return text.strip()

In [ ]:
len(outputs_text)

1000

In [ ]:
df_dataset

,sentence_id,instance_id,input,target,element_order,task_elements
0,3500,17500,pelayanan nya sangat ramah . [A] [O] [S],[A] pelayanan nya [O] sangat ramah [S] positive,aos,aos
1,3501,17505,sayang wifi tidak bagus harus keluar kamar . [...,[A] wifi [O] tidak bagus harus keluar kamar [S...,aos,aos
2,3502,17510,"tulisannya twin bed , tetapi yang ada kamarnya...",[A] kamarnya [O] beda [S] negative,aos,aos
3,3503,17515,"over all baik , hanya sja akan lebih memuaskan...",[A] over all [O] baik [S] positive [SSEP] [A] ...,aos,aos
4,3504,17520,fasilatas sesuia . [A] [O] [S],[A] fasilatas [O] sesuia [S] positive,aos,aos
...,...,...,...,...,...,...
995,4495,22475,"lumayan , harga murah banged . [A] [O] [S]",[A] harga [O] murah banged [S] positive [SSEP]...,aos,aos
996,4496,22480,buat lakilaki dan perempuan yang belum menikah...,[A] null [O] buat lakilaki dan perempuan yang ...,aos,aos
997,4497,22485,"kamar sangat nyaman dan bersih , sungguh menye...",[A] kamar [O] sangat nyaman [S] positive [SSEP...,aos,aos
998,4498,22490,"kamarnya luas , kasurnya empuk , kamar mandiny...",[A] kamarnya [O] luas [S] positive [SSEP] [A] ...,aos,aos
999,4499,22495,"kamar tidak sesuai , tempat parkir kurang nyam...",[A] kamar [O] tidak sesuai [S] negative [SSEP]...,aos,aos

In [ ]:
def check_mismatches_triplet_format(outputs_text):
	mismatch_indexes = []
	mismatch_notes = {}
	for key, instance in outputs_text.items():
		translated_text = add_space_around_punctuation(instance['translated_text'].lower()).strip()
		mismatched = False
		for triplet in instance['translated_triplets']:
			aspect_term = add_space_around_punctuation(triplet['aspect_term'].lower()).strip()
			opinion_term = add_space_around_punctuation(triplet['opinion_term'].lower()).strip()
			if aspect_term not in translated_text and aspect_term != 'null':
				print(f"Mismatch in instance {key}: aspect_term '{aspect_term}' not found in {translated_text}")
				mismatch_notes[key] = mismatch_notes.get(key, []) + [f"aspect_term '{aspect_term}' not found"]
				mismatched = True
			if opinion_term not in translated_text and opinion_term != 'null':
				print(f"Mismatch in instance {key}: opinion_term '{opinion_term}' not found in {translated_text}")
				mismatch_notes[key] = mismatch_notes.get(key, []) + [f"opinion_term '{opinion_term}' not found"]
				mismatched = True
		if mismatched:
			mismatch_indexes.append(key)
	print(f"Total mismatches found: {len(mismatch_indexes)}")
	return mismatch_indexes, mismatch_notes
mismatch_indexes, mismatch_notes = check_mismatches_triplet_format(outputs_text)

Mismatch in instance 3550: opinion_term 'ora isa refund utawa reschedule . berhubung aku bali menyang cireboné diundur nganti tanggal 12 okt dadine kamare hangus nèk isa mbesuké ben isa reschedule' not found in sakjane , nèk saka segi pelayanan airy pancèn wis apik banget nanging . sing dadi masalah ora isa refund utawa reschedule . berhubung aku bali menyang cireboné diundur nganti tanggal 12 okt , dadine kamare hangus . nèk isa mbesuké ben isa reschedule . suwun .
Mismatch in instance 3571: opinion_term 'nomer telpon lokasi anyar aku iso nemokake alamate mergo jadwal' not found in awale angel nggoleki alamate , ning nganggo nomer telpon lokasi anyar , aku iso nemokake alamate mergo jadwal .
Mismatch in instance 3622: aspect_term 'seprei' not found in sprei karo sarung bantal ora diganti , banyu mambu , kamar ora ana cendelane .
Mismatch in instance 3666: aspect_term 'alamate' not found in alamte wae sing angel digoleki . kabeh oke .
Mismatch in instance 3698: opinion_term 'kurang apik bolak-balik njaluk perlengkapan adus , andhuk . uga mung diwenehi ombenan gelas' not found in panggone kepenak nanging pelayanane kurang apik , bolak-balik njaluk perlengkapan adus , andhuk . uga mung diwenehi ombenan gelas .
Mismatch in instance 3813: opinion_term 'kulawarga keri kacamata maca nanging lagi sawetara jam banjur tak parani maneh informasi sing tak entuk malah nguciwani banget yen kacamata kuwi wis dibuwang' not found in kulawarga keri kacamata maca , nanging lagi sawetara jam banjur tak parani maneh , informasi sing tak entuk malah nguciwani banget yen kacamata kuwi wis dibuwang . bab iki sing banget diseseli , ora malah disimpen dhisik .
Mismatch in instance 3823: opinion_term 'kabeh kosong melompong , pegawe-ne lagi wae arep masak' not found in kamare sempit banget , nganti lawange wae menthok karo pucuk amben . terus pegawe-ne ora helpful . pas arep sarapan jam 7 esuk jebule durung siap apa-apa , kabeh kosong melompong . pegawe-ne lagi wae arep masak , teh karo kopi wae durung ana . tulung didandani maneh .
Mismatch in instance 3832: opinion_term 'gawe ngaso ora rame' not found in panggone resik , penak , tenang gawe ngaso , ora rame .
Mismatch in instance 3853: opinion_term 'kanthi rego murah awakdhewe iso entuk luwih kanggo kalangan arek backpacker' not found in kanthi rego murah , awakdhewe iso entuk luwih kanggo kalangan arek backpacker koyo aku . recommended banget .
Mismatch in instance 4005: opinion_term 'elek sinyale' not found in kamar amba lan rapi , nanging sayang kanggo tipi kebetulan sinyale lagi elek lan njaluk ganti menyang kamar liyane sing sinyale apik ora diidini amergo pesen saka airy rooms lan ora ana wifi .
Mismatch in instance 4071: opinion_term 'kerep mati listrik menawa pemanas banyu lan ac diuripake' not found in listrike kerep mati menawa pemanas banyu lan ac diuripake .
Mismatch in instance 4079: aspect_term 'proses cek in' not found in prosese cek in cepet tanpa deposit , cedhak ciwalk , overall apik .
Mismatch in instance 4079: aspect_term 'proses cek in' not found in prosese cek in cepet tanpa deposit , cedhak ciwalk , overall apik .
Mismatch in instance 4239: opinion_term 'wis bola-bali nginep durung tau kuciwa' not found in wis bola-bali nginep , durung tau kuciwa , oke suwun .
Mismatch in instance 4299: opinion_term 'cedhak bandara suta' not found in kamar resik , nyaman , springbed empuk , banyu panas mlaku normal , jedhing uga resik , lan sing penting akeh bakul panganan uga cedhak karo bandara suta .
Mismatch in instance 4319: aspect_term 'fasilitas banyu panase' not found in petugas hotel ramah banget kabeh , nanging eman fasilitase banyu panase ora iso dinikmati . jarene pihak hotel fasilitas kuwi iso dinikmati sesuke , nanging jebule ora cocok karo omongane . nek airy room dhewe menehi pelayanan sing istimewa . suwun airy room .
Mismatch in instance 4319: opinion_term 'jarene pihak hotel fasilitas kuwi iso dinikmati sesuke nanging jebule ora cocok karo omongane' not found in petugas hotel ramah banget kabeh , nanging eman fasilitase banyu panase ora iso dinikmati . jarene pihak hotel fasilitas kuwi iso dinikmati sesuke , nanging jebule ora cocok karo omongane . nek airy room dhewe menehi pelayanan sing istimewa . suwun airy room .
Mismatch in instance 4347: opinion_term 'nek butuh banyu panas ning teko isa njaluk petugas wae' not found in pelayanan apik banget , kabeh petugas ramah banget , pemandangan apik , kamar kepenak , ana cemilan karo banyu ngombe ning kamar . nek butuh banyu panas ning teko , isa njaluk petugas wae . rega murah . menu sarapan lumayan akeh . pas cek in telat 15 menit , lan pas mlebu kamar , lantai isih teles merga bar dipel lan isih mambu banget pengharum sing nyegrak .
Mismatch in instance 4494: aspect_term 'rego' not found in rega kejangkau karo fasilitas sing apik banget .
Total mismatches found: 17

In [ ]:
mismatch_indexes = list(set(mismatch_indexes))
len(mismatch_indexes)

17

In [ ]:
input_eng = {}
for key, instance in outputs_text.items():
	translated_text = add_space_around_punctuation(instance['translated_text'].lower()).strip()
	input_eng[key] = f'{translated_text} [A] [O] [S]'

target_eng = {}
for key, instance in outputs_text.items():
	triplet_texts = []
	for triplet in instance['translated_triplets']:
		aspect_term = add_space_around_punctuation(triplet['aspect_term'].lower()).strip()
		opinion_term = add_space_around_punctuation(triplet['opinion_term'].lower()).strip()
		sentiment = triplet['sentiment_polarity'].lower().strip()
		triplet_texts.append(f"[A] {aspect_term} [O] {opinion_term} [S] {sentiment}")
	target_eng[key] = ' [SSEP] '.join(triplet_texts)
print(len(input_eng), len(target_eng))

1000 1000

In [ ]:
# Sort input_eng and target_eng by key to match df_dataset order
input_eng = dict(sorted(input_eng.items(), key=lambda item: int(item[0])))
target_eng = dict(sorted(target_eng.items(), key=lambda item: int(item[0])))

In [ ]:
list(input_eng.values())

['pelayanane ramah banget . [A] [O] [S]',
 'eman , wifine ora apik kudu metu kamar . [A] [O] [S]',
 'tulisane twin bed , nanging sing ana kamare beda . [A] [O] [S]',
 'sakabehe apik , mung wae bakal luwih maremake menawa banyu panase iso murub 24 jam . wingi mung sedhela . [A] [O] [S]',
 'fasilitas cocok . [A] [O] [S]',
 'cedhak akses transportasi . [A] [O] [S]',
 'kamar apik cocog bujete . [A] [O] [S]',
 'pelayanane ramah , wis langganan kanggo nginep lan ngaso ing kene . [A] [O] [S]',
 'layanan kamar perlu ditingkatke . [A] [O] [S]',
 'sego gorengé enak . mbok menawa aku luwé . [A] [O] [S]',
 'ac-e kurang adem . [A] [O] [S]',
 'kamare butuh didandani . tembok kamar lan lawang-lawange . [A] [O] [S]',
 'regane pas neng kanthong , kamar wis nyukupi . [A] [O] [S]',
 'lokasi kamare terpencil . [A] [O] [S]',
 'tempate nyaman , adoh saka ramene lalu lintas kendaraan . [A] [O] [S]',
 'saben arep check in mesti ning hotel iki , amarga pelayanane apik banget . [A] [O] [S]',
 'pelayanane apik banget . [A] [O] [S]',
 'aku kerep banget nggunakake airy room , mula wis ngerti fasilitas apa wae sing biasane ana . cemilan sing ana uga mung separo saka biasane . [A] [O] [S]',
 'pas karo budget . cedhak bandara . cocok nggo sing penerbangan esuk . disediakake antar jemput menyang lan saka bandara . [A] [O] [S]',
 'pelayane ora sopan . [A] [O] [S]',
 'cukup mung lifte didandani . amerga wis ketok wis suwe banget . [A] [O] [S]',
 'mung wae ruangane sempit banget . [A] [O] [S]',
 'koneksi wifi luwih becik ditingkatke maneh . [A] [O] [S]',
 'pelayanane perlu ditingkatke maneh ben luwih apik maneh . [A] [O] [S]',
 'ac-ne kurang adhem ing kamar 515 . [A] [O] [S]',
 'keramahan staf hotèl ditingkatke manèh . [A] [O] [S]',
 'alhamdulillah layanane apik . [A] [O] [S]',
 'manajemené ora apik amarga wis tuku kamar nanging malah kamarku didol menyang pihak liya . [A] [O] [S]',
 'ngesani amerga cedhak menyang ngendi-endi , nanging sing gawe aku kuciwa kamare reged . [A] [O] [S]',
 'resepsionis mesthi ana . nanging , ora ngerti yen ana aturan sop gorden saka airy-ne . [A] [O] [S]',
 'eman , sarapane wis ora ana karo airy . [A] [O] [S]',
 'parkiran cukup amba . [A] [O] [S]',
 'ngopo sarapan ditiadakake hufft . [A] [O] [S]',
 'kamare biasa wae . [A] [O] [S]',
 'pas arep sarapan soto madura wis ora ana daginge blas , kuah yo keasinan , nanging untunge ana pilihan sarapan liyane . [A] [O] [S]',
 'ora ana hangere babar blas , angel kanggo nggantung klambi ing lemari . [A] [O] [S]',
 'sakabehe apik , cocok kanggo panggonan nginep . smoking area ning parkiran , sing ning lantai 2 ribet mudhun munggahe nek arep udud . remote tv-ne ning endi ya ? [A] [O] [S]',
 'ac ora adhem . [A] [O] [S]',
 'wifi elek . [A] [O] [S]',
 'pelayanane cepet . aku pas mrana lagi ana renovasi . [A] [O] [S]',
 'resepsionise kudu didandani supaya luwih ramah lan sopan , suwun . [A] [O] [S]',
 'ana kolam renange sing gawe bocah seneng . [A] [O] [S]',
 'alhamdulillah panggone penak . [A] [O] [S]',
 'tv sing disediakake luwih gedhe tinimbang airy room liyane ing kelase ( eco , lan regane padha ) . [A] [O] [S]',
 'diladèni apik . check in luwih awal ora kena biaya . [A] [O] [S]',
 'wifi tulung didandani kanggo penak . [A] [O] [S]',
 'banyu panas ora mlaku . [A] [O] [S]',
 'eman , jedhinge mambu . [A] [O] [S]',
 'kabeh apik . [A] [O] [S]',
 'lampune kurang padhang . [A] [O] [S]',
 'sakjane , nèk saka segi pelayanan airy pancèn wis apik banget nanging . sing dadi masalah ora isa refund utawa reschedule . berhubung aku bali menyang cireboné diundur nganti tanggal 12 okt , dadine kamare hangus . nèk isa mbesuké ben isa reschedule . suwun . [A] [O] [S]',
 'kamare cocok karo regane , apik banget . [A] [O] [S]',
 'kamar sing apik banget . [A] [O] [S]',
 'kamar sing hawane seger paling apik sing tau tak parani . [A] [O] [S]',
 'parkirane ora aman . helmku ilang lan ora ana tanggung jawab saka pihak parkir . [A] [O] [S]',
 'lokasine gampang dijangkau karo stasiun . tulung dipertahanke . [A] [O] [S]',
 'kran kamar mandi rusak wis lapor . ora ana dandanan . [A] [O] [S]',
 'kasure kebak bledug . [A] [O] [S]',
 'pesen kamar nggo wong 3 nanging amenities-e dicepakke mung nggo wong 2 . wifi-ne ora mlaku . dicepakke ngombe entheng sing ora diterangke gratis opo ora . dikira gratis jebule bayar . [A] [O] [S]',
 'kamare rada ciut dadine arep sholat rada angel amarga awakku dhuwur dadine rada angel . sinyal rada angel neng njero kamar . [A] [O] [S]',
 'cèt temboké ana sing nglupas sithik . [A] [O] [S]',
 'kamar resik mung ulasan bab anane kewan cilik nang kamar 307 durung ditindaklanjuti . [A] [O] [S]',
 'mbak-e apik , krasan manggon kene . matur nuwun ya airy promone . [A] [O] [S]',
 'sarapan biasa . [A] [O] [S]',
 'layanane kurang apik . [A] [O] [S]',
 'tempate apik . [A] [O] [S]',
 'mirip kos-kosan . pancen isih anyar sih . sakabehe , kabeh apik . mung miris banget pas mlebu kamar . hapeku langsung ora ana sinyal . neng kutha gedhe sing wis 4g nanging sinyal 2g uga ora ana . mosok awake dhewe ora isa komunikasi karo keluarga . yen arep nelpon kudu mlayu menyang teras kanggo entuk sinyal . [A] [O] [S]',
 'kamaré ciut banget . [A] [O] [S]',
 'biasa wae , kamar kurang resik . [A] [O] [S]',
 'kamare murah banget ing jakarta . [A] [O] [S]',
 'mung ora diwènèhi password wifi wae amarga ing kana angel sinyal . [A] [O] [S]',
 'awale angel nggoleki alamate , ning nganggo nomer telpon lokasi anyar , aku iso nemokake alamate mergo jadwal . [A] [O] [S]',
 'ora ana hanger uga ing lemari . [A] [O] [S]',
 'kamare apik . [A] [O] [S]',
 'ora ana snack . [A] [O] [S]',
 'kunci lawang jedhinge rusak . [A] [O] [S]',
 'pelayanane kurang . [A] [O] [S]',
 'ac-é ora mlaku sampurna dadi panas . [A] [O] [S]',
 'kolame iya wae sing lumayan direkomendasike . [A] [O] [S]',
 'bangunane durung siap . [A] [O] [S]',
 'pelayanane apik . nganti dianter menyang bandara barang . [A] [O] [S]',
 'kebersihane perlu ditingkatke maneh . [A] [O] [S]',
 'ac-e mung gawe pajangan wae ora adhem . [A] [O] [S]',
 'seneng banget karo fasilitas kamare , luwih apik yen ana sarapan isuke . [A] [O] [S]',
 'apik panggone , cedhak warung mangan . [A] [O] [S]',
 'kamar amba , ana kursi lipet , kurang pangilon wae ing kamar , pangilone mung sing ing jedhing dadi kudu ngenteni sing ing jedhing rampung lagi bisa dandan ? [A] [O] [S]',
 'kamare marem banget . sithik cathetan , eman , panggonan penginepan iki nang njero gang . mbok menawa rada angel ditemokake . [A] [O] [S]',
 'pambuangan banyu ing jedhing mampet . [A] [O] [S]',
 'pelayanane apik . akeh kuliner ing cedhak hotel kanggo nggampangke sing arep kulineran . [A] [O] [S]',
 'kahanan panggonane kurang apik dibandingke karo panggonan sing sekelas . [A] [O] [S]',
 'jarene ana hot showere jebule ora ana , digawe diwènèhi banyu ngombé nanging nyatane uga ora . tulung didandani manèh . suwun . [A] [O] [S]',
 'kamare ambune kurang wangi . yen diwenehi pengharum ruangan luwih apik . [A] [O] [S]',
 'wektu check in ora cocog karo informasi penting saka hotel , kasebut check in jam 14 nyatane lagi iso check in jam 17 luwih . [A] [O] [S]',
 'pegawai kurang grapyak . [A] [O] [S]',
 'eman , lift-e ora mlaku . [A] [O] [S]',
 'kamare jembar , lokasine lumayan adoh seko dalan gedhe , nanging nek arep menyang endi-endi nganggo angkutan online . [A] [O] [S]',
 'sandale ora ana . gratis wifi jarene , jebule ora diwènèhi sandine anèh . [A] [O] [S]',
 "kuciwa penjagane amarga awake dhewe tekane wis wengi lan isih ana gawean bali maneh menyang hotel wis jam 11 wengi , amarga kawanen tangi jam 11 awan , lagi golek mangan nalika jam 12 lagi adus , wis digedhork-gedhork karo penjagane kanthi rai kecut lan ora grapyak , nalika awake dhewe ngomong isih siyap-siyap dhisik , kanthi galake dheweke ngomong ' aja suwe-suwe lan kuwi wong ngenteni ing ngarep kamar ' . [A] [O] [S]",
 'banyu kanggo adus esuk ora ana , kanthi alesan entek saka pihak penginepan , jadwal awakdewe dadi molor merga kuwi . konfirmasi kapisan , awakdewe dijaluk ngenteni 15 menit , jebule isih durung ana . konfirmasi kapindho , awakdewe diwènèhi info manèh proses pengecekan karo pihak penginepan lan asile durung uga lancar banyu menyang kamar awakdewe . [A] [O] [S]',
 'ruangan cukup kepenak . [A] [O] [S]',
 'pelayanane ramah , kamare kepenak lan fasilitasé komplit . mung banyune showeré kurang panas . [A] [O] [S]',
 'ora pati adoh saka punjering kutha . [A] [O] [S]',
 'kanthi rega terjangkau , awake dhewe wis entuk fasilitas sing nyaman . [A] [O] [S]',
 'kondisine cukup apik , mung entuk panggonan sing paling dhuwur dadi lumayan abot uga pas nggawa travel bag . amarga ora ana lift . [A] [O] [S]',
 'kamar resik , bentuke unik , nanging sinyal tv ora bening . [A] [O] [S]',
 'kamar resik nanging eman linen reged , tilas ana totol-totol , jedhing mambu , anduk wis wayahe diganti jalaran wernane putih rada ireng , wifi angel ( sinyal ana nanging ora gelem nyambung ) . [A] [O] [S]',
 'banyu anget ing kamar mandi ora fungsi , wis komplain nanging ora ana solusi , bengi lan isuk adus . [A] [O] [S]',
 'hotèlé kaya kurang krawat , apik njaba utawa njero . tulung didandani manèh . suwun . [A] [O] [S]',
 'apik , nanging wis ora dianakake neng aplikasi airy . [A] [O] [S]',
 'bantal atos lan kandel , gordèn ora iso ditutup rapet , ora ana banyu panas , kran rusak . ora ana wastafel . selimut cilik . saka njaba , ora kaya hotèl . kaya kos-kosan . resepsionis semrawut . nek kamar kaya ngene paling ora regane 120 èwu . matur nuwun . [A] [O] [S]',
 'cukup resik lan wifi oke wae . [A] [O] [S]',
 'wis cukup apik . rega semono mung kanggo ngaso wis apik banget . mung wae banyu angete kurang fungsi apik . [A] [O] [S]',
 'ac-ne kurang adhem lan saluran tv-ne akèh sing ilang . [A] [O] [S]',
 'enak banget oleh sarapan , nanging wifine kurang banter . [A] [O] [S]',
 'pelayanan apik nanging kesane reged , utamane ing lobi saben-saben lantai lan koridore . [A] [O] [S]',
 'kamare kurang dirumat nanging lumayan apik dinggo transit . [A] [O] [S]',
 'apik panggone , resik lan penak . [A] [O] [S]',
 'lokasi apik tengah kutha . kamar resik mung wae jedhinge mambu bacin , panganan biasa wae , staf resepsionis ora ramah , akses internet ora ana lan kamar lantai 3 ora ana lift . [A] [O] [S]',
 'hotel resik , senajan hotel lawas , lan saka njaba dekorasine rada tuwa lan medeni , nanging ya apik kok pas m . [A] [O] [S]',
 'wifine elek . wis lapor . nanging ora didandani . [A] [O] [S]',
 'pelayanan sing ramah lan fasilitas sing nyukupi . direkomendasike . [A] [O] [S]',
 'proses check in suwe , kamar durung disiapke , pesen kamar airy nanging delok kamare dudu airy , rame . [A] [O] [S]',
 'sprei karo sarung bantal ora diganti , banyu mambu , kamar ora ana cendelane . [A] [O] [S]',
 'rekomended banget kanggo rego semono . [A] [O] [S]',
 'panggonan sing apik mung wifi lagi rusak pas nginep . [A] [O] [S]',
 'mantep , rapi , ana cemilane banyu mineral , ac adem banget , ana water heater gawe adus . [A] [O] [S]',
 'langit ing kamar isih ana omah laba-laba , shower-e kurang apik . [A] [O] [S]',
 'pelayanan nyenengake banget lan ramah . yen menyang malang mesti mrene maneh . [A] [O] [S]',
 'kamar ora cocok karo sing nang gambar . jebule nang ruang ngisor lemah . sinyal ora ana . parkiran kudanan . [A] [O] [S]',
 'banyune kurang banter . [A] [O] [S]',
 'karyawane ramah , kos-e cukup cedhak dalan gedhe , transportasi gampang arep lunga menyang ngendi-endi . nanging kamare durung resik , ana bantal guling sing mambu ana ing njero lemari ora diresiki . [A] [O] [S]',
 'hotel apik banget lan resik . [A] [O] [S]',
 'resik lan penak . letake strategis . direkomendasikake . [A] [O] [S]',
 'angel golek sabun kanggo adus , sing duwe seneng ngilang-ngilang . [A] [O] [S]',
 'panggone strategis , pelayanane apik , nyaman lan jangkep . [A] [O] [S]',
 'cocok kanggo kulawarga , kaya guest house , resik . [A] [O] [S]',
 'resik , penak , adoh saka ramene , stafé ramah . apik rekomendasi . [A] [O] [S]',
 'sakabehe apik kabeh , pancen rekomen tenan . [A] [O] [S]',
 'regane terjangkau , nanging entuk fasilitas sing maremke , kamar resik , entuk cemilan , kak . [A] [O] [S]',
 'apik , lokasi strategis . [A] [O] [S]',
 'sakabehe marem , minusé ora ana lift . [A] [O] [S]',
 'lantai jedhing lunyu , ora disediakake shower cap , lawang jedhing gagange abot / angel diputer kuwatir ora iso dibuka / kekunci saka njero , luwih becike disediakake petunjuk arah kiblat ing njero kamar . [A] [O] [S]',
 'resepsionise lagi tangi . pelayanane kurang grapyak , nganti tekan kono wae kamar durung disiapke , padahal wis adoh banget saka jam check in , terus ac-ne ora murub lan kudu ngenteni maneh , pas check out yo ngecewakke . aku ora pengen nginep ing hotel iki maneh . [A] [O] [S]',
 'kurang resik wae . nanging sakabehe lumayan lah . [A] [O] [S]',
 'hmm , ora cocok karo ekspektasi , bangunan lawas lan kurang resik , kamar mandine banyune mili terus dadi rame , tv isih tabung , kecewa sih kanggo rega semono nanging fasilitas kaya ngono , sarapane ya ora akeh pilihan , pas arep dipangan wis adhem , resepsionis ora ramah . [A] [O] [S]',
 'kamare penak karo nuansa biru . [A] [O] [S]',
 'tempate apik , nyaman , pokoke recommended . [A] [O] [S]',
 'layanan apik . kamar nyaman banget . [A] [O] [S]',
 'oke ibune apik lan ana kolam renang . [A] [O] [S]',
 'resik , nyaman , aman . [A] [O] [S]',
 'hotele resik , wifi-ne mlaku lancar , panggonane sepi penak gawe ngaso . [A] [O] [S]',
 'apik lan resik . [A] [O] [S]',
 'elek banget . wis pesen lan bayar nanging dibatalake sepihak karo airy . ora bakal nganggo airy maneh . [A] [O] [S]',
 'panggone apik , penak lan cedhak menyang endi-endi , menu sarapane enak . [A] [O] [S]',
 'karo rego semono , iso oleh kamar penginepan sing fasilitasé komplit . wiwit banyu anget , ac , lan tv sing salurané pepak . [A] [O] [S]',
 'lumayan terjangkau , puteran banyu krané kadhang panas kadhang adhem . [A] [O] [S]',
 'pelayanane mantep , suasanane penak , iso dolanan karo keluarga lan anak . kanggo mbesuke tulung luwih resik maneh ruangan kamare , kalebu kamar mandine . [A] [O] [S]',
 'penak nginep nang kene , mas sing jaga wengi apik . [A] [O] [S]',
 'kamare ora cocog karo gambar , kamar lan kamar aduse reged , sepraie kaya bekas dinggo ana rambute , ac mati saben 30 menit pisan ( ora iso direset timere ) , listrik kamar mati jam 1 esuk . [A] [O] [S]',
 'pelayane grapyak , lan panggonane resik . [A] [O] [S]',
 'kepenak sih . mung rada ciut . panganan lumayan lah kanggo weteng luwe . nanging kopine ora enak banget . pelayanan ramah . kamar resik . luwih milih tuku neskafe sachet timbang ngombe kopine hotel . [A] [O] [S]',
 'ac-e parah . ramé suarane . gawe ora iso turu babar blas . lokasine angel banget ditemokake . [A] [O] [S]',
 'check in wiwit jam 8 bengi , cek out jam 11 bengi . jalaran ora ana banyu . wc reged . [A] [O] [S]',
 'fasilitase komplit karo rega murah . [A] [O] [S]',
 'apik kabeh , komplit lan reservasi apik , pelayanan ramah lan apik kanggo airy . [A] [O] [S]',
 'hotelé resik , layanané grapyak lan apik . [A] [O] [S]',
 'alamte wae sing angel digoleki . kabeh oke . [A] [O] [S]',
 'pilih kamar sing kasure muat wong 2 . awale apik nanging tengah wengi listrike entek lan dikon pindah kamar sing kasure luwih cilik . ora ana disediakake pouch sing isine perlengkapan adus . rada kuciwa sakjane . [A] [O] [S]',
 'wifi gratis nguciwani amarga ora iso dinggo , instalasi listrik kurang rapi . [A] [O] [S]',
 'ora ana fasilitas airy . [A] [O] [S]',
 'layanan grapyak , nanging banyu panas shower perlu didandani . [A] [O] [S]',
 'layanane maremake , kamare resik lan rapi . mung wae sarapane ora cocog karo kapasitas kamare , alias cepet entek . [A] [O] [S]',
 'banyu kamar mandine asin . [A] [O] [S]',
 'sepisanan ketok mewah nanging akeh sing kurang , toilet reged , anduk cilik banget kaya lap jedhing , kamar akeh nyamuke , mosok kamar mewah ora entuk kemul . payah ! [A] [O] [S]',
 'panggone resik lan penak , apik , seneng . [A] [O] [S]',
 'hotele nyaman lan panganane lumayan enak . [A] [O] [S]',
 'lampune kadhang mati dhewe . nanging sakliyane iku kabeh apik lan resik . [A] [O] [S]',
 'jedhinge ciyut , showere kurang banter , chanel tvne akeh gangguane . liyane apik . [A] [O] [S]',
 'kamare apik lan resik . [A] [O] [S]',
 '1 . kontake mandheg saka 6 bolongan sing ana , sing isa dinggo mung 1 bolongan , 2 bolongan gawe tv lan kulkas . kok medit listrik tenan , terus pas nganggo kompor listrik malah medhun daya . [A] [O] [S]',
 'lumayan wae lah . sanajan kesel munggah mudhun undhak-undhakan , mantep . [A] [O] [S]',
 'kolam renange reged tenan . nanging pelayanane lumayan kanggo budget banget . [A] [O] [S]',
 'ac-e ora adhem lan ora ana lift menyang kamar ndhuwur ! [A] [O] [S]',
 'sakabehe oke , mung ac-ne kurang adhem , akeh cèt wis lungset kudu dicèt manèh , pegawéne ramah , cedhak menyang ngendi-endi . [A] [O] [S]',
 'cocok wae kanggo mampir sedina rong dina . penak lan ora mambu jedinge . [A] [O] [S]',
 'jedhinge mambu banget , kamar peteng , sakabehe apik kanggo rega semono . tulung digatekke lampune lan jedhinge ya . suwun ! [A] [O] [S]',
 'kanggo aqua banyu ngombe supaya diwènèhi saben dina marang tamu hotel , matur nuwun . [A] [O] [S]',
 'andhuk ora diwènèhi , banyu anget ora metu , tulung ditingkatké pelayanane lan fasilitasé . [A] [O] [S]',
 'kamar resik banget lan kepenak , hotel resik , bakal luwih apik yen ana hair dryer ing kamar . [A] [O] [S]',
 'dadi pengalaman sing ngesani banget . [A] [O] [S]',
 'panggone penak , tansah seneng nginep neng kene . [A] [O] [S]',
 'seneng banget nganggo airy . nang hotèlé ya nyaman , mung waé sinyalé sing angèl . nanging , pelayanané seneng karo rega semono , wis cukup banget . sesuk aku nganggo airy manèh yèn pesen-pesen hotèl . [A] [O] [S]',
 'cukup apik , mung lagi direnovasi dadi ketok reged , pelayanane oke . [A] [O] [S]',
 'apik , kamare rada ciut , pelayane ya lumayan . [A] [O] [S]',
 'aku njaluk ngombe maneh kena cas . tak kira bakal entuk saben dinane kaya ing hotel liyane . [A] [O] [S]',
 'ramah banget , resik banget , maremake banget . [A] [O] [S]',
 'entuk diskon , kamar resik , ac lan water heater oke , ana free snack lan banyu mineral . [A] [O] [S]',
 'sarapan isuk enak . sayange kamar mambu asep rokok , kebersihan kamar lan kamar adus kudu ditingkatke . resepsionis ramah . suwun . [A] [O] [S]',
 'panggone kepenak nanging pelayanane kurang apik , bolak-balik njaluk perlengkapan adus , andhuk . uga mung diwenehi ombenan gelas . [A] [O] [S]',
 'layanane ramah , hotel anyar , kamar mandine gedhe , nanging eman-emane banyu panas kanggo wengi ora murub ( rada kuciwa karo iki ) . [A] [O] [S]',
 'ukuran anduke sing ana cilik banget , lan aku check in jam 6 magrib wis dikongkon check out jam 1 . [A] [O] [S]',
 'panggone resik , rapi , pelayanane grapyak , regane terjangkau . [A] [O] [S]',
 'kamar pengap ora ana ventilasi udarane . [A] [O] [S]',
 'kamare apik , nyaman , nanging eman andhuk mung diwenehi siji . [A] [O] [S]',
 'marem banget . panggonane penak , resik , sing jaga grapyak , cedhak karo prawirotaman . regane terjangkau . [A] [O] [S]',
 'enak sih . apik . nanging jedhinge mambu banget , nganti ora betah ambune . tulung didandani ya piye carane ben ora mambu . [A] [O] [S]',
 'murah meriah , kamare nyaman , rekomended lah . [A] [O] [S]',
 'resik , bangunane apik , fasilitase cocok , layanane apik . nanging kamaré ora cocog karo foto sing dipajang ning airy . [A] [O] [S]',
 'kanggo kamar budget lumayan wae , cocok karo regane . [A] [O] [S]',
 'hotelé apik lan pemandangane ya apik . nanging khusus kanggo kamar airyné pancen beda banget karo kamar liyane , kamar airyné akeh omah lawa-lawa , panggon turu sing wis ora kepenak amarga peré krasa banget ing awak lan wis miring-miring , ac ing kamar ya ora adhem apa maneh kamar ora ana ventilasi blas dadi saya krasa sumuk . [A] [O] [S]',
 'aku seneng nang kene . entuk jajan pasar sing super enak lan ana kopi sing super enak . [A] [O] [S]',
 'ora kepenak , ac-ne uga manual . [A] [O] [S]',

In [ ]:
# df_dataset = df_dataset.loc[df_dataset['sentence_id'] >= 1006, :].copy()

In [ ]:
# df_dataset.reset_index(drop=True, inplace=True)

In [ ]:
df_dataset

,sentence_id,instance_id,input,target,element_order,task_elements
0,3500,17500,pelayanan nya sangat ramah . [A] [O] [S],[A] pelayanan nya [O] sangat ramah [S] positive,aos,aos
1,3501,17505,sayang wifi tidak bagus harus keluar kamar . [...,[A] wifi [O] tidak bagus harus keluar kamar [S...,aos,aos
2,3502,17510,"tulisannya twin bed , tetapi yang ada kamarnya...",[A] kamarnya [O] beda [S] negative,aos,aos
3,3503,17515,"over all baik , hanya sja akan lebih memuaskan...",[A] over all [O] baik [S] positive [SSEP] [A] ...,aos,aos
4,3504,17520,fasilatas sesuia . [A] [O] [S],[A] fasilatas [O] sesuia [S] positive,aos,aos
...,...,...,...,...,...,...
995,4495,22475,"lumayan , harga murah banged . [A] [O] [S]",[A] harga [O] murah banged [S] positive [SSEP]...,aos,aos
996,4496,22480,buat lakilaki dan perempuan yang belum menikah...,[A] null [O] buat lakilaki dan perempuan yang ...,aos,aos
997,4497,22485,"kamar sangat nyaman dan bersih , sungguh menye...",[A] kamar [O] sangat nyaman [S] positive [SSEP...,aos,aos
998,4498,22490,"kamarnya luas , kasurnya empuk , kamar mandiny...",[A] kamarnya [O] luas [S] positive [SSEP] [A] ...,aos,aos
999,4499,22495,"kamar tidak sesuai , tempat parkir kurang nyam...",[A] kamar [O] tidak sesuai [S] negative [SSEP]...,aos,aos

In [ ]:
mismatch_indexes

['3622',
 '3571',
 '3853',
 '4005',
 '4347',
 '4239',
 '3666',
 '4299',
 '4319',
 '4071',
 '3832',
 '4494',
 '3550',
 '3813',
 '4079',
 '3823',
 '3698']

In [ ]:
index_check = df_dataset['sentence_id'].to_list()
df_dataset[f'input_{lang_target}'] = list(input_eng.values())
df_dataset[f'target_{lang_target}'] = list(target_eng.values())
df_dataset['aspect_or_opinion_not_in_input'] = [str(idx) in mismatch_indexes for idx in index_check]
df_dataset['mismatch_notes'] = [mismatch_notes.get(str(idx), []) for idx in index_check]
df_dataset['mismatch_notes_format'] = df_dataset['mismatch_notes'].apply(lambda x: '\n'.join(x))

In [ ]:
df_dataset['target_format'] = df_dataset['target'].apply(lambda x: '\n'.join(x.split(' [SSEP] ')))
df_dataset[f'target_format_{lang_target}'] = df_dataset[f'target_{lang_target}'].apply(lambda x: '\n'.join(x.split(' [SSEP] ')))

In [ ]:
df_dataset

,sentence_id,instance_id,input,target,element_order,task_elements,input_jav,target_jav,aspect_or_opinion_not_in_input,mismatch_notes,mismatch_notes_format,target_format,target_format_jav
0,3500,17500,pelayanan nya sangat ramah . [A] [O] [S],[A] pelayanan nya [O] sangat ramah [S] positive,aos,aos,pelayanane ramah banget . [A] [O] [S],[A] pelayanane [O] ramah banget [S] positive,False,[],,[A] pelayanan nya [O] sangat ramah [S] positive,[A] pelayanane [O] ramah banget [S] positive
1,3501,17505,sayang wifi tidak bagus harus keluar kamar . [...,[A] wifi [O] tidak bagus harus keluar kamar [S...,aos,aos,"eman , wifine ora apik kudu metu kamar . [A] [...",[A] wifi [O] ora apik kudu metu kamar [S] nega...,False,[],,[A] wifi [O] tidak bagus harus keluar kamar [S...,[A] wifi [O] ora apik kudu metu kamar [S] nega...
2,3502,17510,"tulisannya twin bed , tetapi yang ada kamarnya...",[A] kamarnya [O] beda [S] negative,aos,aos,"tulisane twin bed , nanging sing ana kamare be...",[A] kamare [O] beda [S] negative,False,[],,[A] kamarnya [O] beda [S] negative,[A] kamare [O] beda [S] negative
3,3503,17515,"over all baik , hanya sja akan lebih memuaskan...",[A] over all [O] baik [S] positive [SSEP] [A] ...,aos,aos,"sakabehe apik , mung wae bakal luwih maremake ...",[A] sakabehe [O] apik [S] positive [SSEP] [A] ...,False,[],,[A] over all [O] baik [S] positive\n[A] air ho...,[A] sakabehe [O] apik [S] positive\n[A] banyu ...
4,3504,17520,fasilatas sesuia . [A] [O] [S],[A] fasilatas [O] sesuia [S] positive,aos,aos,fasilitas cocok . [A] [O] [S],[A] fasilitas [O] cocok [S] positive,False,[],,[A] fasilatas [O] sesuia [S] positive,[A] fasilitas [O] cocok [S] positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4495,22475,"lumayan , harga murah banged . [A] [O] [S]",[A] harga [O] murah banged [S] positive [SSEP]...,aos,aos,"lumayan , regane murah banget . [A] [O] [S]",[A] rega [O] murah banget [S] positive [SSEP] ...,False,[],,[A] harga [O] murah banged [S] positive\n[A] n...,[A] rega [O] murah banget [S] positive\n[A] nu...
996,4496,22480,buat lakilaki dan perempuan yang belum menikah...,[A] null [O] buat lakilaki dan perempuan yang ...,aos,aos,kanggo lanang karo wadon sing durung rabi ya o...,[A] null [O] kanggo lanang karo wadon sing dur...,False,[],,[A] null [O] buat lakilaki dan perempuan yang ...,[A] null [O] kanggo lanang karo wadon sing dur...
997,4497,22485,"kamar sangat nyaman dan bersih , sungguh menye...",[A] kamar [O] sangat nyaman [S] positive [SSEP...,aos,aos,"kamar nyaman banget lan resik , nyenengake ten...",[A] kamar [O] nyaman banget [S] positive [SSEP...,False,[],,[A] kamar [O] sangat nyaman [S] positive\n[A] ...,[A] kamar [O] nyaman banget [S] positive\n[A] ...
998,4498,22490,"kamarnya luas , kasurnya empuk , kamar mandiny...",[A] kamarnya [O] luas [S] positive [SSEP] [A] ...,aos,aos,"kamare jembar , kasure empuk , kamar mandine y...",[A] kamare [O] jembar [S] positive [SSEP] [A] ...,False,[],,[A] kamarnya [O] luas [S] positive\n[A] kasurn...,[A] kamare [O] jembar [S] positive\n[A] kasure...
999,4499,22495,"kamar tidak sesuai , tempat parkir kurang nyam...",[A] kamar [O] tidak sesuai [S] negative [SSEP]...,aos,aos,"kamar ora cocok , panggon parkir kurang penak ...",[A] kamar [O] ora cocok [S] negative [SSEP] [A...,False,[],,[A] kamar [O] tidak sesuai [S] negative\n[A] t...,[A] kamar [O] ora cocok [S] negative\n[A] pang...

In [ ]:
df_dataset[['sentence_id', 'input', f'input_{lang_target}', 'target_format', f'target_format_{lang_target}', 'aspect_or_opinion_not_in_input', 'mismatch_notes_format']].rename({'target_format': 'target', f'target_format_{lang_target}': f'target_{lang_target}', 'mismatch_notes_format': 'mismatch_notes'}).to_csv(f'temp/translation_output/{lang_target}/{dataset_folder}/translated_dataset_{lang}_{split}.csv', index=False)

### Check mismatches after annotation

In [ ]:
def get_google_sheet(sheet_id: str, sheet_gid: str) -> pd.DataFrame:
	"""
	Downloads a specific sheet from a Google Sheet into a pandas DataFrame.

	Args:
		sheet_id: The ID of the Google Sheet.
		sheet_gid: The GID of the specific sheet to download.

	Returns:
		A pandas DataFrame containing the data from the specified sheet.
	"""
	url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={sheet_gid}'
	df = pd.read_csv(url)
	return df
google_sheet_id = '1_ZEFErp75wDNkXIvYflxv1d4nAQZrMlg_Vin4cgpyyY'  # Replace with your actual Google Sheet ID
gid_eng_train = '1363651964'  # Replace with the actual GID for the English sheet
gid_eng_test = '1183495517'
gid_eng_dev = '390220786'
gid_sunda_train = '557914217'
gid_sunda_dev = '736485835'
gid_sunda_test = '1775717233'
split = 'dev'
lang_target = 'eng'
try:
	df_translated_correction = get_google_sheet(google_sheet_id, globals()[f'gid_{lang_target}_{split}'])
	print("Successfully loaded data from the specific sheet:")
except Exception as e:
	print(f"An error occurred: {e}")
	print("Please ensure the Google Sheet is shared correctly and the IDs are correct.")

Successfully loaded data from the specific sheet:

In [ ]:
df_translated_correction

,sentence_id,input,input_eng,input_eng_corrected,target_format,target_format_eng,target_format_eng_corrected,aspect_or_opinion_not_in_input,mismatch_notes_format
0,2500,pintu geser kurang rapat . [A] [O] [S],the sliding door is not tight enough . [A] [O]...,the sliding door doesn't close properly . [A] ...,[A] pintu geser [O] kurang rapat [S] negative,[A] sliding door [O] not tight enough [S] nega...,[A] the sliding door [O] doesn't close properl...,False,NaN
1,2501,pelayanan lumayan baik . [A] [O] [S],the service is quite good . [A] [O] [S],NaN,[A] pelayanan [O] lumayan baik [S] positive,[A] service [O] quite good [S] positive,NaN,False,NaN
2,2502,air bersih untuk mck tidak ada . [A] [O] [S],clean water for sanitary facilities is not ava...,there is no clean water for the sanitary facil...,[A] air bersih [O] tidak ada [S] negative,[A] clean water [O] not available [S] negative,[A] clean water for the sanitary facilities [O...,False,NaN
3,2503,ternyata ada makanan ringan gratis . [A] [O] [S],it turns out there are free snacks . [A] [O] [S],NaN,[A] makanan ringan gratis [O] ada [S] positive,[A] free snacks [O] there are [S] positive,NaN,False,NaN
4,2504,wifi buruk suka down . [A] [O] [S],"the wifi is bad , it often goes down . [A] [O]...",NaN,[A] wifi [O] buruk [S] negative,[A] wifi [O] bad [S] negative,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...
995,3495,"strategis , dekat jalan raya . [A] [O] [S]","strategic , close to the main road . [A] [O] [S]",NaN,[A] null [O] strategis [S] positive\n[A] null ...,[A] null [O] strategic [S] positive\n[A] null ...,NaN,False,NaN
996,3496,( - ) tempatnya kurang bersih . tipetipe pengi...,the place is not very clean . it ' s an old-fa...,"the downside is, the place is not very clean ....",[A] tempatnya [O] kurang bersih [S] negative\n...,[A] place [O] not very clean [S] negative\n[A]...,[A] place [O] not very clean [S] negative\n[A]...,False,NaN
997,3497,"mantapp , pelayanan prima . [A] [O] [S]","awesome , excellent service . [A] [O] [S]",NaN,[A] null [O] mantapp [S] positive\n[A] pelayan...,[A] null [O] awesome [S] positive\n[A] service...,NaN,False,NaN
998,3498,"hotel lumayan nyaman sih , tetapi dikamar saya...","the hotel was quite comfortable , but in my ro...","the hotel was quite comfortable , but in my ro...",[A] hotel [O] lumayan nyaman [S] positive\n[A]...,[A] hotel [O] quite comfortable [S] positive\n...,[A] hotel [O] quite comfortable [S] positive\n...,False,NaN
999,3499,"tidak ada yang bertulisan airy di room 107 , r...",nothing was labeled ' airy ' in room 107 . the...,none items in room 107 were labeled ' airy ' ....,[A] remote tv [O] tidak bisa [S] negative\n[A]...,[A] tv remote [O] couldn ' t be used [S] negat...,[A] tv remote [O] couldn ' t be used [S] negat...,False,NaN

In [ ]:
df_translated_correction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   sentence_id                     1000 non-null   int64
 1   input                           1000 non-null   object
 2   input_eng                       1000 non-null   object
 3   input_eng_corrected             534 non-null    object
 4   target_format                   1000 non-null   object
 5   target_format_eng               999 non-null    object
 6   target_format_eng_corrected     544 non-null    object
 7   aspect_or_opinion_not_in_input  1000 non-null   bool
 8   mismatch_notes_format           40 non-null     object
dtypes: bool(1), int64(1), object(7)
memory usage: 63.6+ KB

In [ ]:
df_translated_correction[f'target_format_{lang_target}'].fillna('[A] [O] [S]', inplace=True)

/tmp/ipykernel_2375546/3226597203.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_translated_correction[f'target_format_{lang_target}'].fillna('[A] [O] [S]', inplace=True)

In [ ]:
df_translated_correction[f'input_{lang_target}_corrected'] = df_translated_correction[f'input_{lang_target}_corrected'].apply(lambda x: x.replace('’', "'") if isinstance(x, str) else x)
df_translated_correction[f'target_format_{lang_target}_corrected'] = df_translated_correction[f'target_format_{lang_target}_corrected'].apply(lambda x: x.replace('’', "'") if isinstance(x, str) else x)
df_translated_correction[f'input_{lang_target}'] = df_translated_correction[f'input_{lang_target}'].apply(lambda x: x.replace('’', "'"))
df_translated_correction[f'target_format_{lang_target}'] = df_translated_correction[f'target_format_{lang_target}'].apply(lambda x: x.replace('’', "'"))

In [ ]:
list(df_translated_correction.loc[df_translated_correction['sentence_id'] == 433, f'input_{lang_target}_corrected'])

[]

In [ ]:
# Strip strings of all _corrected columns
df_translated_correction[f'input_{lang_target}_corrected'] = df_translated_correction[f'input_{lang_target}_corrected'].apply(lambda x: x.strip() if isinstance(x, str) else x)
df_translated_correction[f'target_format_{lang_target}_corrected'] = df_translated_correction[f'target_format_{lang_target}_corrected'].apply(lambda x: x.strip() if isinstance(x, str) else x)

# Set to pandas nan if empty string
df_translated_correction[f'input_{lang_target}_corrected'] = df_translated_correction[f'input_{lang_target}_corrected'].apply(lambda x: x if x != '' else np.nan)
df_translated_correction[f'target_format_{lang_target}_corrected'] = df_translated_correction[f'target_format_{lang_target}_corrected'].apply(lambda x: x if x != '' else np.nan)

In [ ]:
# Fill _corrected columns with input_eng if null
df_translated_correction[f'input_{lang_target}_corrected'] = df_translated_correction[f'input_{lang_target}_corrected'].fillna(df_translated_correction[f'input_{lang_target}'])
df_translated_correction[f'target_format_{lang_target}_corrected'] = df_translated_correction[f'target_format_{lang_target}_corrected'].fillna(df_translated_correction[f'target_format_{lang_target}'])

In [ ]:
df_translated_correction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   sentence_id                     1000 non-null   int64
 1   input                           1000 non-null   object
 2   input_eng                       1000 non-null   object
 3   input_eng_corrected             1000 non-null   object
 4   target_format                   1000 non-null   object
 5   target_format_eng               1000 non-null   object
 6   target_format_eng_corrected     1000 non-null   object
 7   aspect_or_opinion_not_in_input  1000 non-null   bool
 8   mismatch_notes_format           40 non-null     object
dtypes: bool(1), int64(1), object(7)
memory usage: 63.6+ KB

In [ ]:
def check_mismatches_triplet_format_sent_id(outputs_text):
	mismatch_indexes = []
	mismatch_notes = {}
	for key, instance in outputs_text.items():
		translated_text = add_space_around_punctuation(instance['translated_text'].lower()).strip()
		mismatched = False
		for triplet in instance['translated_triplets']:
			aspect_term = add_space_around_punctuation(triplet['aspect_term'].lower()).strip()
			opinion_term = add_space_around_punctuation(triplet['opinion_term'].lower()).strip()
			if aspect_term not in translated_text and aspect_term != 'null':
				print(f"Mismatch in instance sentence_id {instance['sentence_id']} key {key}: aspect_term '{aspect_term}' not found in {translated_text}")
				mismatch_notes[key] = mismatch_notes.get(key, []) + [f"aspect_term '{aspect_term}' not found"]
				mismatched = True
			if opinion_term not in translated_text and opinion_term != 'null':
				print(f"Mismatch in instance sentence_id {instance['sentence_id']} key {key}: opinion_term '{opinion_term}' not found in {translated_text}")
				mismatch_notes[key] = mismatch_notes.get(key, []) + [f"opinion_term '{opinion_term}' not found"]
				mismatched = True
		if mismatched:
			mismatch_indexes.append(key)
	print(f"Total mismatches found: {len(mismatch_indexes)}")
	return mismatch_indexes, mismatch_notes

In [ ]:
outputs_text_correction = {}
for idx, row in df_translated_correction.iterrows():
	outputs_text_correction[idx] = {
		'sentence_id': row['sentence_id'],
		'translated_text': row[f'input_{lang_target}_corrected'],
		'translated_triplets': parse_absa_string(row[f'target_format_{lang_target}_corrected'].replace('\n', ' [SSEP] '))
	}
	# Change the keys of translated_triplets from A, O, S to aspect_term, opinion_term, sentiment_polarity
	for triplet in outputs_text_correction[idx]['translated_triplets']:
		triplet['aspect_term'] = triplet.pop('A', '')
		triplet['opinion_term'] = triplet.pop('O', '')
		triplet['sentiment_polarity'] = triplet.pop('S', '')

In [ ]:
len(outputs_text_correction)

1000

In [ ]:
outputs_text_correction[372]

{'sentence_id': 2872,
 'translated_text': 'my body became itchy after staying here . the room did not match the picture . [A] [O] [S]',
 'translated_triplets': [{'aspect_term': 'body',
   'opinion_term': 'itchy after staying here',
   'sentiment_polarity': 'negative'},
  {'aspect_term': 'room',
   'opinion_term': 'did not match the picture',
   'sentiment_polarity': 'negative'}]}

In [ ]:
mismatch_indexes, mismatch_notes = check_mismatches_triplet_format_sent_id(outputs_text_correction)

Mismatch in instance sentence_id 2515 key 15: opinion_term 'wait a long time' not found in when we checked out , there was no staff available , so we had to wait for a long time . [a] [o] [s]
Mismatch in instance sentence_id 2566 key 66: aspect_term 'the partition wall' not found in the lobby space is too far in . if possible , the partitition wall could be opened so that the outside view can be seen . [a] [o] [s]
Mismatch in instance sentence_id 2584 key 84: opinion_term 'strategic' not found in the location is convenient , near malang city square , with many culinary places . [a] [o] [s]
Mismatch in instance sentence_id 2614 key 114: opinion_term 'the best' not found in please arrange the maintainance for the elevator , but everything else was excellent ! [a] [o] [s]
Mismatch in instance sentence_id 2623 key 123: opinion_term 'soomewhat disappointing' not found in the bathroom was a bit dirty , and the food was also somewhat disappointing . i had breakfast at 8 am , but all of the food was already gone . [a] [o] [s]
Mismatch in instance sentence_id 2636 key 136: opinion_term 'not very bright' not found in the room light isn ' t very bright . [a] [o] [s]
Mismatch in instance sentence_id 2646 key 146: opinion_term 'close to supermarkets' not found in the ac is not cold and the bathroom door leaks , but overall it ' s good , especially the food . it ' s close to eateries outside the hotel and supermarkets . [a] [o] [s]
Mismatch in instance sentence_id 2665 key 165: opinion_term 'not met the request' not found in it didn ' t met the request , i asked for a large bed but it wasn ' t provided . [a] [o] [s]
Mismatch in instance sentence_id 2688 key 188: opinion_term 'many cockroaches' not found in there are many mosquitoes and cockroaches . the floor is also very dirty ! [a] [o] [s]
Mismatch in instance sentence_id 2698 key 198: opinion_term 'no' not found in very dissapointing ! the room was full of mosquitoes . we asked for mosquito spray , but they don ' t have any . [a] [o] [s]
Mismatch in instance sentence_id 2727 key 227: opinion_term 'extremely hot' not found in the water coming out of the shower is quite weak , and the hot water is too hot to shower with . [a] [o] [s]
Mismatch in instance sentence_id 2745 key 245: aspect_term 'attitude' not found in as soon as we arrived , we immediately met the owner of this place . and they didn ' t seem very welcoming . [a] [o] [s]
Mismatch in instance sentence_id 2745 key 245: opinion_term 'not friendly' not found in as soon as we arrived , we immediately met the owner of this place . and they didn ' t seem very welcoming . [a] [o] [s]
Mismatch in instance sentence_id 2750 key 250: opinion_term 'no' not found in the experience was pleasant . the room was comfortable and tidy , and the staff were friendly . however , a telephone and dining facilities were unavailable , so we have to leave the room . [a] [o] [s]
Mismatch in instance sentence_id 2750 key 250: opinion_term 'no' not found in the experience was pleasant . the room was comfortable and tidy , and the staff were friendly . however , a telephone and dining facilities were unavailable , so we have to leave the room . [a] [o] [s]
Mismatch in instance sentence_id 2753 key 253: opinion_term 'not come out of the shower' not found in everything was fine , except in the morning , the water didn ' t come out of the shower . i couldn ' t take a shower until check-out at 10 am , so i ended up skipping my shower . [a] [o] [s]
Mismatch in instance sentence_id 2753 key 253: opinion_term 'skipping shower' not found in everything was fine , except in the morning , the water didn ' t come out of the shower . i couldn ' t take a shower until check-out at 10 am , so i ended up skipping my shower . [a] [o] [s]
Mismatch in instance sentence_id 2761 key 261: opinion_term 'affordble' not found in for an affordable price , the service is good and the location is pretty accessible . [a] [o] [s]
Mismatch in instance sentence_id 2766 key 266: opinion_term 'shoule be replaced' not found in the bed sheets , pillowcases , and towels should be replaced . the shower also needs to be repaired . [a] [o] [s]
Mismatch in instance sentence_id 2776 key 276: opinion_term 'not as comfortable as it looked in the photos' not found in the room wasn ' t as comfortable as it looked in the photos . [a] [o] [s]
Mismatch in instance sentence_id 2778 key 278: opinion_term 'not too far from kfc' not found in good , not crowded . not too far from pizza hut , kfc , and mcdonald ' s . it ' s clean . and the pool is good . [a] [o] [s]
Mismatch in instance sentence_id 2778 key 278: opinion_term 'not too far from mcdonald ' s' not found in good , not crowded . not too far from pizza hut , kfc , and mcdonald ' s . it ' s clean . and the pool is good . [a] [o] [s]
Mismatch in instance sentence_id 2786 key 286: opinion_term 'need to be replaced' not found in one of the most impressive things was that the hotel staff were willing to provide suhoor ( as a replacement for breakfast ) when i stayed here during ramadan . however , one thing that needs to be improved is that the towels should be replaced , the ceiling needs to be repainted to be clean ( there are black stains ) , and perhaps the room needs to be re-inspected ( it seems there ' s leaking ac water dripping in the room ) . otherwise , it ' s good . [a] [o] [s]
Mismatch in instance sentence_id 2790 key 290: opinion_term 'far from restaurants' not found in the facilities are just fine . but it ' s far from supermarkets and restaurants . [a] [o] [s]
Mismatch in instance sentence_id 2793 key 293: opinion_term 'not look like in the picture' not found in it doesn ' t look like the picture .
Mismatch in instance sentence_id 2825 key 325: opinion_term 'very good' not found in the room matches the photo , it ' s good and comfortable , but unfortunately , we cannot use cold water in the shower , it ' s too hot , probably broken . but the rest is very great . [a] [o] [s]
Mismatch in instance sentence_id 2831 key 331: aspect_term 'rooms' not found in friendly service and clean room , airy is always my choice . [a] [o] [s]
Mismatch in instance sentence_id 2833 key 333: opinion_term 'not bright' not found in the ac was not cold , the room walls had water leaks that made the room damp , and the room ' s lighting was dim rather than bright . [a] [o] [s]
Mismatch in instance sentence_id 2837 key 337: opinion_term 'good' not found in it was great and enjoyable , but there were still a few problems . when i booked airy rooms , i selected one bed , but at check-in , i was given a room with two beds . please look into this . thank you , airy rooms . [a] [o] [s]
Mismatch in instance sentence_id 2842 key 342: opinion_term 'not match with the room price and facilities' not found in there were many cockroaches , and the room deposit doesn ' t match the room price and facilities . [a] [o] [s]
Mismatch in instance sentence_id 2843 key 343: aspect_term 'equipment' not found in room 1131 ' s tower was on a different floor , and the aminities was dirty . [a] [o] [s]
Mismatch in instance sentence_id 2853 key 353: opinion_term 'not as described' not found in the toilet ' s bidet spray was stuck , and the water from the toilet ' s washing button was slow . the receptionist is not 24 hours available . it wasn ' t as described in the listing . [a] [o] [s]
Mismatch in instance sentence_id 2857 key 357: opinion_term 'not properly cleaned' not found in the room was not clean enough , the towels were dirty , and the bathroom was also dirty and hadn ' t been properly cleaned . [a] [o] [s]
Mismatch in instance sentence_id 2859 key 359: opinion_term 'not enough' not found in there isn ' t enough drinking water . [a] [o] [s]
Mismatch in instance sentence_id 2876 key 376: opinion_term 'smell of kitchen spices' not found in the room is behind the restaurant , so there ' s are smells of smoke and kitchen spices , it ' s stuffy , and you have to go up and down by stairs . [a] [o] [s]
Mismatch in instance sentence_id 2881 key 381: aspect_term 'table tissues' not found in the room smelled , there were no tissues on the table , no toilet paper either , and the bed sheets were dirty . special guest requests were not provided , and they even charged us . [a] [o] [s]
Mismatch in instance sentence_id 2889 key 389: opinion_term 'not receive' not found in usually , i get snacks . but i didn ' t receive any in this room . also , the ac smells like vinegar ( i don ' t know if it ' s really a vinegar , but it ' s very strange ) . [a] [o] [s]
Mismatch in instance sentence_id 2894 key 394: aspect_term 'room door' not found in the room smelled , the bathroom was dirty , the walls and ceiling were moldy , the tv was just static , there was also a hole in the room , and the door was a bit difficult to close . [a] [o] [s]
Mismatch in instance sentence_id 2903 key 403: opinion_term 'not really working' not found in it ' s quite good . but the only thing is , at night , the water flow is weak , and the hot water isn ' t really working . [a] [o] [s]
Mismatch in instance sentence_id 2904 key 404: aspect_term 'we' not found in the hotel is clean , there is no bad smell at all . the room ' s interior is modern made us feel comfortable , and the service is also pleasing . [a] [o] [s]
Mismatch in instance sentence_id 2912 key 412: opinion_term 'not clean' not found in indeed , it is very cheap for me . it was a pity that it wasn ' t clean , especially in the bathroom . it seems like it hasn ' t been cleaned properly for months , only rinsed with water . [a] [o] [s]
Mismatch in instance sentence_id 2917 key 417: opinion_term 'one for two people' not found in the place is tidy and clean . but they only provided one towel , one toothpaste , and also one soap for two people . [a] [o] [s]
Mismatch in instance sentence_id 2926 key 426: opinion_term 'there ' s a superindo in front of the hotel' not found in i didn ' t expect that the hotel would be very clean , good , and comfortable . there ' s also a superindo in front the hotel . [a] [o] [s]
Mismatch in instance sentence_id 2938 key 438: opinion_term 'there ' s cockroaches' not found in the hotel lobby smelled of fried food , it was hot , the kitchen was in the front office , it ' s my first time seeing a small kitchen in the fo . the elevator was not working , and there were cockroaches on the pillow in the room , which was very disgusting . i requested to cancel and get a refund for my 2-night booking here . [a] [o] [s]
Mismatch in instance sentence_id 2945 key 445: opinion_term 'not stable enough' not found in the wi-fi connection isn ' t stable enough . [a] [o] [s]
Mismatch in instance sentence_id 2946 key 446: opinion_term 'only 1 towel provided' not found in it ' s comfortable and clean , but unfortunately there ' s no bathroom mat and only 1 towel is provided . [a] [o] [s]
Mismatch in instance sentence_id 2963 key 463: opinion_term 'couldn ' t find' not found in the cake at the breakfast time was delicious . but it was not very impressive because the staff didn ' t smile much . when we arrived , we could ' t find the hotel entrance door , so we had to knock on the door , and then a staff came to inform us with a somewhat harsh tone . [a] [o] [s]
Mismatch in instance sentence_id 2963 key 463: aspect_term 'staff member' not found in the cake at the breakfast time was delicious . but it was not very impressive because the staff didn ' t smile much . when we arrived , we could ' t find the hotel entrance door , so we had to knock on the door , and then a staff came to inform us with a somewhat harsh tone . [a] [o] [s]
Mismatch in instance sentence_id 2972 key 472: opinion_term 'late , still welcomed us' not found in the room is nice and the service is good . even though our check-in was late , they still welcomed us . [a] [o] [s]
Mismatch in instance sentence_id 2974 key 474: aspect_term 'bathroom lighting' not found in the internet network needs improvement , as do the bathroom and room lighting , the drinking water in the room should be 1 . 5 liters , and the pillowcases need to be replaced as they already have yellow stains . [a] [o] [s]
Mismatch in instance sentence_id 2974 key 474: opinion_term 'need improvement' not found in the internet network needs improvement , as do the bathroom and room lighting , the drinking water in the room should be 1 . 5 liters , and the pillowcases need to be replaced as they already have yellow stains . [a] [o] [s]
Mismatch in instance sentence_id 2974 key 474: opinion_term 'need to be improved' not found in the internet network needs improvement , as do the bathroom and room lighting , the drinking water in the room should be 1 . 5 liters , and the pillowcases need to be replaced as they already have yellow stains . [a] [o] [s]
Mismatch in instance sentence_id 2990 key 490: aspect_term 'its location' not found in it ' s clean and white . but the location is a bit tucked away , as it ' s located in a housing area . [a] [o] [s]
Mismatch in instance sentence_id 2990 key 490: aspect_term 'its location' not found in it ' s clean and white . but the location is a bit tucked away , as it ' s located in a housing area . [a] [o] [s]
Mismatch in instance sentence_id 3006 key 506: opinion_term 'not seem like it ' s cheap' not found in the room is good . it doesn ' t seem like it ' s cheap . [a] [o] [s]
Mismatch in instance sentence_id 3035 key 535: opinion_term 'pleaasing' not found in facilities and service are pleasing . [a] [o] [s]
Mismatch in instance sentence_id 3043 key 543: opinion_term 'at night there are many mosquitoes' not found in the place is good and worth it , but there are many mosquitoes at night . [a] [o] [s]
Mismatch in instance sentence_id 3046 key 546: opinion_term 'work well' not found in the service from the hotel was satisfying , the bedroom and bathroom were clean . the hot water shower worked well . [a] [o] [s]
Mismatch in instance sentence_id 3075 key 575: opinion_term 'includes' not found in considering the price , it was good , since the breakfast was also included . [a] [o] [s]
Mismatch in instance sentence_id 3083 key 583: opinion_term 'not adequate' not found in the service was unfriendly , and the bathroom facilities weren ' t adequate . [a] [o] [s]
Mismatch in instance sentence_id 3100 key 600: opinion_term 'available' not found in it ' s good , complete privacy and snacks provided . [a] [o] [s]
Mismatch in instance sentence_id 3108 key 608: aspect_term 'atmosphere' not found in the room is spacious , clean , the surrounding is comfortable , and the service is fast . [a] [o] [s]
Mismatch in instance sentence_id 3109 key 609: opinion_term 'not very good' not found in the bathroom condition isn ' t very good , and the water is a bit sticky . perhaps it ' s because it ' s an old building . the room ' s of cleanliness also needs improvement . otherwise , everything is okay . thank you . [a] [o] [s]
Mismatch in instance sentence_id 3109 key 609: aspect_term 'the room ' s cleanliness' not found in the bathroom condition isn ' t very good , and the water is a bit sticky . perhaps it ' s because it ' s an old building . the room ' s of cleanliness also needs improvement . otherwise , everything is okay . thank you . [a] [o] [s]
Mismatch in instance sentence_id 3141 key 641: opinion_term 'not very good' not found in the hotel is great , well-comfort , but the service isn ' t very good , and facilities are somewhat lacking . the faucet is leaking , but breakfast was served on time . [a] [o] [s]
Mismatch in instance sentence_id 3143 key 643: aspect_term 'paint on the wall' not found in for a price under 200 , 000 , this room is exceptionally good ! however , for the future , please fix the peeling paint on the corner of the wall . [a] [o] [s]
Mismatch in instance sentence_id 3145 key 645: opinion_term 'if a trash can was added in each room' not found in the room is clean and tidy . it would be better if a trash can was provided in each room . [a] [o] [s]
Mismatch in instance sentence_id 3189 key 689: aspect_term 'water' not found in the shower was broken and couldn ' t work properly . the bed was quite comfortable , but the pillows were too thin and uncomfortable . the ac was not cold enough . thank you , airy . [a] [o] [s]
Mismatch in instance sentence_id 3190 key 690: opinion_term 'unknown' not found in bad . the bed had sperm stains , the bed sheets smelled like rust . the bed springs were also broken . the soap was empty . the wifi password was uknown . [a] [o] [s]
Mismatch in instance sentence_id 3192 key 692: aspect_term 'surrounding' not found in the ambiance is comfortable , the place is very clean , the staff are friendly , i want to come again . [a] [o] [s]
Mismatch in instance sentence_id 3217 key 717: opinion_term 'close to bandung indah plaza' not found in comfortable , very close to gedung sate , bandung indah plaza , and so on , with an affordable price , especially if using a promo . recommended for those who want to vacation in bandung city . [a] [o] [s]
Mismatch in instance sentence_id 3223 key 723: opinion_term 'more than expected' not found in more than i expected for a budget hotel . [a] [o] [s]
Mismatch in instance sentence_id 3228 key 728: opinion_term 'fuly equipped' not found in perfect . fully equipped facilities , affordable price ! thank you airy : ) [a] [o] [s]
Mismatch in instance sentence_id 3252 key 752: aspect_term 'facilities for watching tv' not found in there is no facilitaties for watching tv . everything else was pleasing , great . [a] [o] [s]
Mismatch in instance sentence_id 3257 key 757: opinion_term 'not like the picture' not found in the room wasn ' t like the picture , it was very small . the ac was leaking , and there was water leakage in the room as well . the bathroom was small and dark , and there was no doormat . very disappointing . [a] [o] [s]
Mismatch in instance sentence_id 3269 key 769: aspect_term 'platforms' not found in the receptionist ' s response when the bathroom ceiling fell was very good , a replacement room was immediately found . the room facilities were good , but the only problem is just the condition of the hotel , many spots and ceiling were damp . [a] [o] [s]
Mismatch in instance sentence_id 3282 key 782: opinion_term 'good' not found in the place is comfortable , quiet , and suitable for a family vacation . it ' s very recommended . [a] [o] [s]
Mismatch in instance sentence_id 3319 key 819: opinion_term 'close to eating places in depok' not found in the hotel ' s location is convenient , close to food stalls in depok and easily accessible . however , the room is too small , to the point that it ' s difficult to even open the room door because it hits the bed . that ' s the only thing that made it uncomfortable , but the service was good . [a] [o] [s]
Mismatch in instance sentence_id 3326 key 826: opinion_term 'there ' s pillar inside , making it uncomfortable' not found in there ' s a pillar inside the room 306 , making it uncomfortable . no kettle was provided . but the service was friendly , clean , and calm . [a] [o] [s]
Mismatch in instance sentence_id 3326 key 826: opinion_term 'quiet' not found in there ' s a pillar inside the room 306 , making it uncomfortable . no kettle was provided . but the service was friendly , clean , and calm . [a] [o] [s]
Mismatch in instance sentence_id 3328 key 828: opinion_term 'not matched the pictures' not found in the room doesn ' t match the pictures , it ' s not clean . [a] [o] [s]
Mismatch in instance sentence_id 3329 key 829: opinion_term 'not good enough' not found in it ' s great , but the bathroom isn ' t good enough . [a] [o] [s]
Mismatch in instance sentence_id 3349 key 849: opinion_term 'want to come back again' not found in good . the environment is convenient and clean . i want come back again . [a] [o] [s]
Mismatch in instance sentence_id 3350 key 850: opinion_term 'many are blurry' not found in it ' s quite good , but many of the tv channels are blurry . [a] [o] [s]

In [ ]:
df_translated_correction['aspect_or_opinion_not_in_input'] = [idx in mismatch_indexes for idx in df_translated_correction.index]
df_translated_correction['mismatch_notes'] = [mismatch_notes.get(idx, []) for idx in df_translated_correction.index]
df_translated_correction['mismatch_notes_format'] = df_translated_correction['mismatch_notes'].apply(lambda x: '\n'.join(x))

In [ ]:
os.makedirs(f'temp/translation_output/{lang_target}/{dataset_folder}', exist_ok=True)
df_translated_correction[['aspect_or_opinion_not_in_input', 'mismatch_notes_format']].to_csv(f'temp/translation_output/{lang_target}/{dataset_folder}/translated_dataset_{lang}_{split}_correction_mismatches.csv', index=False)